newrelic/terraform-provider-newrelic

newrelic/resource_newrelic_alert_condition.go, newrelic/resource_newrelic_alert_condition_test.go, vendor/github.com/paultyng/go-newrelic/api/client.go, vendor/github.com/paultyng/go-newrelic/api/types.go, vendor/vendor.json, website/docs/index.html.markdown
Adds a test to verify a zero-value for term thresholds
```
$ make testacc TEST=./newrelic TESTARGS="-run=TestAccNewRelicAlertCondition_ZeroThreshold"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./newrelic -v -run=TestAccNewRelicAlertCondition_ZeroThreshold -timeout 120m
=== RUN   TestAccNewRelicAlertCondition_ZeroThreshold
--- PASS: TestAccNewRelicAlertCondition_ZeroThreshold (12.52s)
PASS
ok      github.com/terraform-providers/terraform-provider-newrelic/newrelic     12.528s
```
Depends on fix: https://github.com/paultyng/go-newrelic/issues/6
Fixes: #12
=> r/newrelic_alert_condition: Allow zero threshold value for terms

newrelic/resource_newrelic_alert_condition_test.go, newrelic/resource_newrelic_nrql_alert_condition_test.go
This is to make tests in TeamCity work. It looks odd, but we have a script which `grep`s for test names to run them in parallel. It's not ideal and it was created long time before `go test -list` was a thing. We plan to fix it eventually, so such workarounds aren't necessary.
For now this is the easiest way to get it working again 🤷‍♂️
=> test: Ignore tests which are commented out

newrelic/import_newrelic_dashboard_test.go, newrelic/provider.go, newrelic/resource_newrelic_dashboard.go, newrelic/resource_newrelic_dashboard_test.go, vendor/github.com/paultyng/go-newrelic/LICENSE, vendor/github.com/paultyng/go-newrelic/api/dashboards.go, vendor/github.com/paultyng/go-newrelic/api/key_transactions.go, vendor/github.com/paultyng/go-newrelic/api/types.go, vendor/vendor.json, website/docs/r/dashboard.html.markdown, website/newrelic.erb
Depends on: https://github.com/paultyng/go-newrelic/pull/14
Adds support for the new Dashboard API, this will let people write and manage dashboards as code.
still needs:
Docs: https://docs.newrelic.com/docs/insights/insights-api/manage-dashboards/insights-dashboard-api
Announcement: https://blog.newrelic.com/2018/01/08/insights-dashboard-api/
=> Add support for dashboards API

newrelic/config.go, newrelic/data_source_newrelic_application.go, newrelic/data_source_newrelic_key_transaction.go, newrelic/provider.go, newrelic/resource_newrelic_alert_channel.go, newrelic/resource_newrelic_alert_channel_test.go, newrelic/resource_newrelic_alert_condition.go, newrelic/resource_newrelic_alert_condition_test.go, newrelic/resource_newrelic_alert_policy.go, newrelic/resource_newrelic_alert_policy_channel.go, newrelic/resource_newrelic_alert_policy_channel_test.go, newrelic/resource_newrelic_alert_policy_test.go, newrelic/resource_newrelic_dashboard.go, newrelic/resource_newrelic_dashboard_test.go, newrelic/resource_newrelic_infra_alert_condition.go, newrelic/resource_newrelic_infra_alert_condition_test.go, newrelic/resource_newrelic_nrql_alert_condition.go, newrelic/resource_newrelic_nrql_alert_condition_test.go, vendor/github.com/paultyng/go-newrelic/api/alert_infra_conditions.go, vendor/github.com/paultyng/go-newrelic/api/client.go, vendor/github.com/paultyng/go-newrelic/api/types.go, vendor/vendor.json, website/docs/r/infra_alert_condition.html.markdown, website/newrelic.erb
My attempt at adding support for New Relic Infrastructure alert conditions. Adding this was complicated by the fact that New Relic has a separate endpoint for anything Infrastructure related.
I basically just forked paultyng/go-newrelic into paul91/go-newrelic-infra and made it Infrastructure specific. This allowed me to export it as a secondary client for the provider.
Happy to fix/change whatever. Thanks!
=> Add New Relic Infrastructure alert condition support

newrelic/data_source_newrelic_alert_channel.go, newrelic/data_source_newrelic_alert_channel_test.go, newrelic/provider.go, newrelic/provider_test.go, website/docs/d/alert_channel.html.markdown, website/newrelic.erb
This Pull request add support for retrieving existing newrelic alert channel and re-using the id by associating it to an alert policy channel.
This becomes useful when associating an alert policy to newrelic users instead of creating an email channel or re-using an existing channel (e.g slack) in another policy.
=> Add support for data alert channel

website/docs/r/nrql_alert_condition.html.markdown
this fixes the `nrql_alert_condition.html` page that does not display the `NRQL` section properly.
=> include space to `format nrql_alert_condition.html.markdown` properly

newrelic/resource_newrelic_alert_condition.go
I would propose to use TypeSet instead of TypeList for the terms of the Alertconditions. https://www.terraform.io/docs/extend/schemas/schema-types.html#typeset
This should fix issue #4 
Results of the acceptance tests:
```
TF_ACC=1 go test -v github.com/terraform-providers/terraform-provider-newrelic/newrelic -run '^TestAccNewRelicInfraAlertCondition*'  -count=1 
=== RUN   TestAccNewRelicInfraAlertCondition_Basic
--- PASS: TestAccNewRelicInfraAlertCondition_Basic (11.28s)
provider_test.go:66:
=== RUN   TestAccNewRelicInfraAlertCondition_Where
--- PASS: TestAccNewRelicInfraAlertCondition_Where (6.89s)
provider_test.go:66:
=== RUN   TestAccNewRelicInfraAlertCondition_Thresholds
--- PASS: TestAccNewRelicInfraAlertCondition_Thresholds (11.25s)
provider_test.go:66:
PASS
ok …
```
=> Use TypeSet instead of TypeList

newrelic/resource_newrelic_alert_condition.go, newrelic/resource_newrelic_alert_condition_test.go
This PR is depends on changes from https://github.com/paultyng/go-newrelic/pull/27 which has been merged, but not released and pulled into this project.  I've tested by manually pulling in the change and it works as expected.  Without the dependent change, you can't update a condition to switch from enabled to disabled.
@bridgetlane, I may need help from you and/or @paultyng to release and pull in the dependent change in the go-newrelic module. 
As a side note, your README is out of date and still references the use of govendor, but it seems you've switched over to go modules, so that might need an update.
=> #3 Make resource_newrelic_alert_condition enabled status configurable

newrelic/resource_newrelic_alert_condition.go, newrelic/resource_newrelic_alert_condition_test.go, website/docs/r/alert_condition.html.markdown
The New Relic API enforces a 64 character limit on alert condition
names as described in [the documentation](https://docs.newrelic.com/docs/alerts/new-relic-alerts/defining-conditions/define-alert-conditions#rename-condition). This pull request validates the alert condition name before making a request to the API.
=> add alert condition name validation

newrelic/data_source_newrelic_synthetics_monitor_test.go, newrelic/provider.go, newrelic/resource_newrelic_alert_channel.go, newrelic/resource_newrelic_alert_condition.go, newrelic/resource_newrelic_alert_policy.go, newrelic/resource_newrelic_alert_policy_channel.go, newrelic/resource_newrelic_dashboard.go, newrelic/resource_newrelic_infra_alert_condition.go, newrelic/resource_newrelic_nrql_alert_condition.go, newrelic/resource_newrelic_synthetics_alert_condition.go, newrelic/resource_newrelic_synthetics_alert_condition_test.go, newrelic/resource_newrelic_synthetics_monitor.go, newrelic/resource_newrelic_synthetics_monitor_script.go, newrelic/resource_newrelic_synthetics_monitor_script_test.go, newrelic/resource_newrelic_synthetics_monitor_test.go, website/docs/r/synthetics_monitor.html.markdown, website/docs/r/synthetics_monitor_script.html.markdown, website/newrelic.erb
This adds two new resources for maintaining synthetics monitor scripts:
```
newrelic_synthetics_monitor
newrelic_synthetics_monitor_script
```
Closes #65.
Things I left out of this PR:
- Some validation around required/unsupported options based on the monitor type
- Monitor script locations (describing HMACs for secure locations)
And some quirks:
- I defined the script separately from the monitor since it uses a different endpoint, but New Relic doesn't support deleting a script from a monitor, so instead I just set it to `" "`. The script also doesn't have a real ID, so I'm relying on the monitor ID.
Happy to hear of better ways to do ^ or to improve the proposed API in general.
I was able to:
- import existing SCRIPT_API monitors into the state without tfstate discrepancies
- …
=> Add newrelic_synthetics_monitor and script resources

newrelic/resource_newrelic_nrql_alert_condition.go, newrelic/resource_newrelic_nrql_alert_condition_test.go, website/docs/r/nrql_alert_condition.html.markdown
The rest API asserts that `since_value` is `the timeframe (in minutes) in which to evaluate the specified NRQL query. since_value must be between 1 and 20.` 
However, the provider does not allow the number to be above `5`. 
`nrql[since_value]`  https://docs.newrelic.com/docs/alerts/rest-api-alerts/new-relic-alerts-rest-api/alerts-conditions-api-field-names 
For @SuperBadCode who said he needs it. 
Found out after the fact that it resolves #131 
It appears as though the newrelic API expects since_value to be a `string` instead of an `int` which prevents the use of [validate.IntBetween](https://godoc.org/github.com/hashicorp/terraform/helper/validation#IntBetween)
=> Modifies since_value's validation to match rest API's requirements

newrelic/resource_newrelic_alert_policy_channel_test.go, newrelic/resource_newrelic_nrql_alert_condition_test.go
A couple of the acceptance tests were failing.  This PR gets them working again.
`NEWRELIC_LICENSE_KEY=<valid_license_key> NEWRELIC_API_KEY=<valid_api_key> make testacc`
Sample test output before the fix:
```
=== RUN   TestAccNewRelicAlertChannelDataSource_Basic
--- PASS: TestAccNewRelicAlertChannelDataSource_Basic (5.41s)
=== RUN   TestAccNewRelicAlertPolicyDataSource_Basic
--- PASS: TestAccNewRelicAlertPolicyDataSource_Basic (2.18s)
=== RUN   TestAccNewRelicApplication_Basic
--- PASS: TestAccNewRelicApplication_Basic (1.68s)
=== RUN   TestAccNewRelicSyntheticsMonitorDataSource_Basic
--- PASS: TestAccNewRelicSyntheticsMonitorDataSource_Basic (3.28s)
=== RUN   TestParseIDs_Basic
--- PASS: TestParseIDs_Basic (0.00s)
=== RUN   TestSerializeIDs_Basic
--- PASS: TestSerializeIDs_Basic (0.00s) …
```
=> Fix some failing acceptance tests

website/docs/r/synthetics_monitor.html.markdown
I had to check the source to find valid values for the type parameter on `newrelic_synthetics_monitor`.
Valid values found here: https://github.com/terraform-providers/terraform-provider-newrelic/blob/master/newrelic/resource_newrelic_synthetics_monitor.go#L28-L31
Adding values to documentation.
=> adding values for type argument to docs

newrelic/resource_newrelic_alert_condition.go, newrelic/resource_newrelic_alert_condition_test.go, website/docs/r/alert_condition.html.markdown
=> fix: align alert condition duration constraints to NR's API constraints

website/docs/r/synthetics_monitor.html.markdown
There is a typo in the docs. Resource argument is spelt wrong.
=> Fixes typo in docs

newrelic/data_source_newrelic_alert_policy.go, newrelic/data_source_newrelic_alert_policy_test.go, newrelic/resource_newrelic_alert_policy_test.go
Fixes: #213 
**Tests**
- Adjust tests to follow conventions
- Add additional test cases for Alert Policies
**Improvements**
- Add ability to import `newrelic_alert_policy` data source
=> feat: add import newrelic_alert_policy data source, newrelic_alert_policy acceptance test updates

GNUmakefile, newrelic/helpers_test.go, newrelic/structures_newrelic_dashboard.go
This PR fixes the linter errors when building via `make`, and also introduces a run of `go mod tidy` after the linters run to avoid altering `go.mod` and `go.sum`.
=> fix: appease linter

website/docs/r/nrql_alert_condition.html.markdown
Support for different `type` args was added in #141 (Issue #50) but the docs need to be updated as well. This documents the possible values for `type`.
=> Document type arg

.travis.yml, newrelic/resource_newrelic_alert_condition_test.go, newrelic/resource_newrelic_alert_policy_test.go, newrelic/resource_newrelic_infra_alert_condition_test.go, newrelic/resource_newrelic_nrql_alert_condition_test.go, newrelic/resource_newrelic_synthetics_alert_condition_test.go
This PR fixes the linting errors generated by `tfproviderlint` and enables a full run of `make` in Travis.
=> fix linting issues and enable linting in CI

newrelic/data_source_newrelic_alert_channel.go, newrelic/data_source_newrelic_alert_channel_test.go, newrelic/resource_newrelic_alert_channel.go, newrelic/resource_newrelic_alert_channel_test.go, website/docs/d/alert_channel.html.markdown, website/docs/r/alert_channel.html.markdown
Resolves: #215 
IMPROVEMENTS:
* Add ability to import `newrelic_alert_channel` **data** source
* Minor updates to `newrelic_alert_channel` **data** source acceptance tests
* Increased test coverage for the different channels in `newrelic_alert_channel` **resource**
=> feat: ability to import newrelic_alert_channel data source, update acceptance tests

newrelic/helpers_test.go, newrelic/provider_test.go, newrelic/resource_newrelic_alert_condition_test.go, newrelic/resource_newrelic_infra_alert_condition_test.go, newrelic/resource_newrelic_nrql_alert_condition_test.go, newrelic/resource_newrelic_synthetics_alert_condition_test.go
Resolves #214.
This PR backfills acceptance test coverage for the alert conditions resource and refactors the existing test code for simplicity.
=> Backfill alert condition acceptance tests

newrelic/resource_newrelic_alert_policy_channel.go, newrelic/resource_newrelic_alert_policy_channel_test.go
Resolves #216.
This PR introduces importing for the alert policy channel resource, backfills acceptance test coverage, introduces parallel testing, and refactors the existing test code for simplicity.
=> Backfill alert policy channel acceptance tests

newrelic/resource_newrelic_infra_alert_condition.go, newrelic/resource_newrelic_infra_alert_condition_test.go, website/docs/r/infra_alert_condition.html.markdown
Resolves #220.
This PR introduces import for the `newrelic_infra_alert_condition` resource type, parallelizes its acceptance tests, refreshes its documentation, and backfills acceptance test coverage.
=> Acc testing infra conditions

newrelic/data_source_newrelic_alert_channel_test.go
This PR fixes a broken test on master.
Import tests don't make sense for a data source, so we are removing this one here.
=> test: fix failing data source test

newrelic/helpers.go, newrelic/resource_newrelic_nrql_alert_condition.go, newrelic/resource_newrelic_nrql_alert_condition_test.go, newrelic/structure_newrelic_nrql_alert_condition.go, newrelic/structure_newrelic_nrql_alert_condition_test.go, website/docs/r/nrql_alert_condition.html.markdown
Resolves: #219 
IMPROVEMENTS:
- add ability to import `newrelic_nrql_alert_condition`
- Note: this only for types `static` and `outlier` (type `baseline` is not enabled yet)
- additional acceptance test coverage of `newrelic_nrql_alert_condition`
=> feat: newrelic_nrql_alert_condition acc test updates

newrelic/resource_newrelic_nrql_alert_condition.go, newrelic/resource_newrelic_nrql_alert_condition_test.go, website/docs/r/nrql_alert_condition.html.markdown
Work in Progress. Blocked by https://github.com/paultyng/go-newrelic/pull/75.
A possible fix for https://github.com/terraform-providers/terraform-provider-newrelic/issues/157.
1. Adds `violation_limit_time_seconds` to NRQL Alerts Conditions to reflect updates to the New Relic API (see [documentation](https://docs.newrelic.com/docs/alerts/new-relic-alerts/reviewing-alert-incidents/how-alert-condition-violations-are-closed#time-limit) and [API details](https://rpm.newrelic.com/api/explore/alerts_nrql_conditions/list)).
2. Updates related tests. 
cc. @ctrombley
=> [WIP] add Violation Close timer for NRQL Alert Conditions

newrelic/data_source_newrelic_alert_channel.go, newrelic/data_source_newrelic_alert_channel_test.go, newrelic/data_source_newrelic_alert_policy.go, newrelic/data_source_newrelic_alert_policy_test.go
A possible fix for #165 .
- Implements a stricter matching on alert policy data sources.
=> fix issue #165 with strict name matching for alert policies

newrelic/data_source_newrelic_application.go
Resolves #176 .
This PR passes the `newrelic_application` data source's `name` attribute as a filter to the underlying API endpoint when refreshing the state.  This greatly reduces the amount of paging required for lookups in cases where an account has many applications.
=> fix: use name as filter in application lookup

newrelic/data_source_newrelic_key_transaction_test.go, website/docs/d/alert_channel.html.markdown, website/docs/d/alert_policy.html.markdown, website/docs/d/application.html.markdown, website/docs/d/key_transaction.html.markdown, website/docs/d/plugin.html.markdown, website/docs/d/plugin_component.html.markdown, website/docs/d/synthetics_monitor.html.markdown, website/docs/r/alert_channel.html.markdown, website/docs/r/alert_condition.html.markdown, website/docs/r/alert_policy.html.markdown, website/docs/r/alert_policy_channel.html.markdown, website/docs/r/dashboard.html.markdown, website/docs/r/infra_alert_condition.html.markdown, website/docs/r/nrql_alert_condition.html.markdown, website/docs/r/plugins_alert_condition.html.markdown, website/docs/r/synthetics_alert_condition.html.markdown, website/newrelic.erb
Resolves #218 .
This PR backfills acceptance testing for the key transactions data source.  This test has been restricted to the NR internal testing account since the key transaction is required to be preconfigured in that account.
It also removes an import test from the alert policy data source and updates various portions of the documentation site for consistency.
=> test: backfill acceptance tests for key transactions data source

newrelic/resource_newrelic_infra_alert_condition.go, newrelic/resource_newrelic_infra_alert_condition_test.go, website/docs/r/infra_alert_condition.html.markdown
Resolves #270 .
This PR resolves perpetual configuration drift for certain configurations of the `newrelic_infra_alert_condition` resource introduced in v1.9.0 of the provider.  
- fix: add attribute validation for infra condition types
- fix: loosen validation for threshold duration
- fix: make event a computed attribute
- docs: update documentation for newrelic_infra_alert_condition
=> fix: configuration drift in infra (#270)

CHANGELOG.md, newrelic/data_source_newrelic_alert_channel_test.go, newrelic/data_source_newrelic_alert_policy_test.go, newrelic/data_source_newrelic_plugin_component_test.go, newrelic/data_source_newrelic_synthetics_monitor_test.go, newrelic/resource_newrelic_alert_condition_test.go, newrelic/resource_newrelic_alert_policy_channel_test.go, newrelic/resource_newrelic_infra_alert_condition_test.go, newrelic/resource_newrelic_nrql_alert_condition_test.go, newrelic/resource_newrelic_plugins_alert_condition_test.go, newrelic/resource_newrelic_synthetics_alert_condition_test.go, newrelic/resource_newrelic_synthetics_monitor_script_test.go, website/docs/d/alert_channel.html.markdown, website/docs/d/alert_policy.html.markdown, website/docs/d/application.html.markdown, website/docs/d/key_transaction.html.markdown, website/docs/d/plugin.html.markdown, website/docs/d/plugin_component.html.markdown, website/docs/d/synthetics_monitor.html.markdown, website/docs/guides/getting_started.html.markdown, website/docs/index.html.markdown, website/docs/r/alert_condition.html.markdown, website/docs/r/alert_policy_channel.html.markdown, website/docs/r/dashboard.html.markdown, website/docs/r/infra_alert_condition.html.markdown, website/docs/r/nrql_alert_condition.html.markdown, website/docs/r/plugins_alert_condition.html.markdown, website/docs/r/synthetics_alert_condition.html.markdown, website/docs/r/synthetics_monitor_script.html.markdown
This PR contains some documentation site updates before the next release.  The largest change here is removing all the deprecated HCL from the docs and tests.
=> docs/test: remove usage of deprecated HCL & doc updates

newrelic/provider.go
Update the config passed to newrelic-client-go to call the correct function on the API key.
=> Fix API Key passing to newrelic-client-go

website/docs/guides/getting_started.html.markdown, website/docs/index.html.markdown, website/docs/r/alert_channel.html.markdown, website/docs/r/alert_policy_channel.html.markdown
I noticed some conflicting examples (`config` vs `configuration`) when I was trying out the provider.
=> docs: update alert-channel examples

newrelic/resource_newrelic_alert_condition.go, website/docs/r/alert_condition.html.markdown
resolves: #386
Without this change, the provider fores the user to set a condition_scope, which
is not a valid attribute on all alert condition types.  The apm_app_metric types
require it to be set, but the API throws back a message that we surface to the
user already.  Without this change though, users of other condition types, like
apm_kt_metric, are unable to get a clean run, because the condition_scope is not
valid for that type.
=> fix(alert_condition): mark condition_scope optional

go.mod, go.sum
Updating newrelic-client-go to v0.10.0
=> chore: update to newrelic-client-go v0.10.0

newrelic/helpers.go, newrelic/helpers_test.go, newrelic/provider_test.go, newrelic/resource_newrelic_alert_policy_channel.go, newrelic/resource_newrelic_alert_policy_channel_test.go, newrelic/structures_newrelic_alert_policy_channel.go, newrelic/structures_newrelic_alert_policy_channel_test.go, website/docs/r/alert_policy_channel.html.markdown
Resolves: #319 
This PR introduces the ability to provision multiple alert channels per a policy via the `/v2/alerts_policy_channels` endpoint. Prior to this, we could only provision a single channel per HCL block. This will greatly reduce the amount of HCL code required to accomplish adding multiple notification channels to a policy.
=> feat(alert_policy_channels): add ability to add multiple channels to a policy

CHANGELOG.md
BUG FIXES:
* fix(nrql_alert_condition): terms should be a TypeSet ([#421](https://github.com/terraform-providers/terraform-provider-newrelic/pull/421))
IMPROVEMENTS:
* feat(application_labels): Implementation of CRUD operations for NewRelic App Labels ([#417](https://github.com/terraform-providers/terraform-provider-newrelic/pull/417))
* feat(alert_policy_channels): add ability to add multiple channels to a policy ([#365](https://github.com/terraform-providers/terraform-provider-newrelic/pull/365))
* docs(newrelic_alert_condition): list of potential metrics for newrelic_alert_condition ([#431](https://github.com/terraform-providers/terraform-provider-newrelic/pull/431))
=> Prepare v1.15.0 release

go.mod, go.sum, newrelic/resource_newrelic_alert_condition_test.go, vendor/github.com/newrelic/newrelic-client-go/internal/version/version.go, vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/serialization.go, vendor/modules.txt
Resolves #432 .
This PR integrates newrelic-client-go v0.17.1, which contains custom unmarshaling rules to deal with more formats for alert condition threshold values.
=> fix: import condition terms regardless of threshold format

website/docs/guides/getting_started.html.markdown
Found a couple inconsistencies in the Getting Started guide, and a deprecated field used for the latest version.  Update to current standards / all examples work.
=> docs: Update getting started guide

website/docs/index.html.markdown, website/docs/r/alert_condition.html.markdown
Resolves: #481 
This PR also removes the inaccessible alert condition type `apm_jvm_metric` from the docs.
=> docs: use correct default synthetics_api_url in config docs

newrelic/config.go, newrelic/provider.go, newrelic/provider_test.go
This PR adds `AccountID` and `PersonalAPIKey` to `ProviderConfig` to facilitate logic for selecting which API to call (REST APIs or NerdGraph) via the helper method `ProviderConfig.hasNerdGraphCredentials()`.
=> chore(provider): add personal_api_key and account_id to provider schema and ProviderConfig

website/docs/index.html.markdown, website/docs/r/workload.html.markdown
This PR fixes a typo in the workload docs.
=> docs(workloads): fix api key attribute name

newrelic/resource_newrelic_alert_condition.go, newrelic/structures_newrelic_alert_condition.go
Previously, violation_close_timer was not validated to be only applied when condition_scope was properly set. The [docs](https://docs.newrelic.com/docs/alerts/rest-api-alerts/new-relic-alerts-rest-api/alerts-conditions-api-field-names#violation_close_timer) state that this option is only valid when targeting `instance` not `application`, and the result was constant drift in the resource.
```
resource "newrelic_alert_condition" "test" {
name = "test"
   
  condition_scope = "application"
  enabled         = true
  entities = [
    data.newrelic_application.test.id,
  ]
  metric                      = "user_defined"
  policy_id                   = newrelic_alert_policy.test.id
  type                        = "apm_app_metric"
  user_defined_metric         = "Go/Runtime/Goroutines"
  …
```
=> Fix: violation_close_timer only applies to condition_scope instance

website/docs/r/alert_channel.html.markdown
This PR fixes a broken link within the `newrelic_alert_channel` resource documentation.
=> docs(alert_channel): fix broken 'nested config' anchor link

website/docs/guides/getting_started.html.markdown
Rename "my_alert_policy_name" to "alert_policy_name" in the Getting Started guide.
Previously both names were used, resulting in errors
when trying to run terraform after pasting the code from docs.
`alert_policy_name` was used on line 105, while other lines used `my_alert_policy_name`.
Since no other resource names start with `my_`, I've decided to keep it as `alert_policy_name`.
=> docs(getting started): fix resource naming

.github/renovate.json
So the `release/v1.x` branch does not get out of date while we aren't looking.
=> chore(build): Ask renovate to track release/v1.x branch too

newrelic/resource_newrelic_application_settings_test.go, website/docs/index.html.markdown
Stop updating the application name under test since it is shared by all the other tests.
=> tests: fix integration tests

examples/modules/golden-signal-alerts/main.tf, newrelic/resource_newrelic_nrql_alert_condition.go, newrelic/structures_newrelic_nrql_alert_condition.go, newrelic/structures_newrelic_nrql_alert_condition_test.go, website/docs/r/nrql_alert_condition.html.markdown
resolves: #631
The named condition priorities "warning" and "critical" are promoted to replace the use of "terms" on a `newrelic_nrql_alert_condition` resource.
=> chore(alerts): deprecation notice for direct use of "terms"

website/docs/guides/provider_configuration.markdown
This PR adds a table displaying the provider's environment variables, how they map to their associated schema attributes, and descriptions.
=> docs(provider): add environment variables and schema attribute table

.github/stale.yml
Shortening `daysUntilStale` and `daysUntilClose` just a bit to help lighten the repo maintenance workload.
=> chore(stalebot): shorter daysUntilStale, shorter daysUntilClose

go.mod, go.sum, newrelic/resource_newrelic_nrql_alert_condition.go, newrelic/resource_newrelic_nrql_alert_condition_test.go, newrelic/structures_newrelic_nrql_alert_condition.go, newrelic/structures_newrelic_nrql_alert_condition_test.go, website/docs/r/nrql_alert_condition.html.markdown
Without this change, the term operator incorrectly uses the word "equal" when
the API requires the use of "equals".  Here we make the necessary code, test,
and docs updates to ensure users are able to make use of the "equal" term
operator on their static conditions.
=> fix(nrql_alert_condition): use better term operator

.githooks/pre-push
Integration tests are timing out git push operations on account of how long they run.  This PR removes them from the pre-push git hook.
=> chore: remove integration tests from push hook

.github/workflows/test.yml
The PR should provide a slight boost in CI efficiency by parallelizing the `test-unit` job by removing a dependency on the `lint` job.
=> chore(ci): remove lint job as dependency on test-unit job

newrelic/resource_newrelic_alert_condition_integration_test.go, newrelic/resource_newrelic_alert_condition_test.go, newrelic/structures_newrelic_alert_condition.go
Resolves #795.
Scoping this validation to `apm_app_metric` condition type only so it doesn't affect users of `jvm_app_metric`. 
This also uncovered a state flattening bug for conditions of type `apm_jvm_metric` that could cause drift.  The state flattening required some additional logic since the underlying API fails to return the `condition_scope` field when that condition type is provisioned.
https://docs.newrelic.com/docs/alerts/rest-api-alerts/new-relic-alerts-rest-api/alerts-conditions-api-field-names#violation_close_timer
=> fix(newrelic_alert_condition): allow instance scope for JVM app metrics

CHANGELOG.md, build/document.mk, go.mod, go.sum, tools/tools.go
The PR also fixes our CHANGELOG by swapping out `git-chglog/git-chglog` for `newrelic-forks/git-chglog`
=> chore(changelog): Update CHANGELOG for v2.4.1

newrelic/data_source_newrelic_alert_policy.go, newrelic/helpers.go, newrelic/resource_newrelic_alert_policy.go, newrelic/resource_newrelic_nrql_alert_condition.go, newrelic/structures_newrelic_alert_policy.go
=> fix: avoid perpetual drift due to `account_id` inheritance from the provider block

.github/workflows/changelog.yml
Without this change, the pull-request action doesn't have a valid base due to
the detached head state when the tag is checked out.  Here we use the upload and
download artifact actions around switch to the master branch before we submit a
pull request.  This should result in the desired behavior, accounting for the
needs of the pull-request action.
=> fix(changelog): ensure proper branch to base from

CONTRIBUTING.md, README.md
=> chore(contrib): include a contribution guide

newrelic/provider_test.go, newrelic/resource_newrelic_nrql_alert_condition.go, newrelic/resource_newrelic_nrql_alert_condition_test.go, newrelic/structures_newrelic_nrql_alert_condition.go
When excluding `fill_option` an API error would be returned. This PR fixes that issue.
```
Error: Argument "condition" has invalid value $condition.
In field "signal": Expected type "AlertsNrqlConditionSignalInput", found {fillOption: "", fillValue: null}.
In field "fillOption": Expected type "AlertsFillOption", found ""., null
```
=> Fixed an issue with empty extrapolation settings causing API errors

.github/workflows/changelog.yml, go.mod, go.sum
Resolves: #860 
- #860 is fixed per a [fix in newrelic-client-go](https://github.com/newrelic/newrelic-client-go/pull/478)
- This PR also includes a fix for the `create-pull-request` GitHub Action (adds `base` to the config)
=> chore(deps): update newrelic/newrelic-client-go to v0.41.2

newrelic/structures_newrelic_nrql_alert_condition.go, newrelic/structures_newrelic_nrql_alert_condition_test.go
Without this change, cases where the configured number of terms differ from that
in the API, we incorrectly reference an index that doesn't exist.  This also
looks to be the condition when we deprecate an item, and the state has
half-moved over to the new values.  Here we ensure that we check the length of
the conditions before we attempt to use the values and avoid a bad index
reference.
fixes: #882
=> fix(alerts): avoid bad index reference

newrelic/resource_helpers.go, newrelic/resource_newrelic_alert_condition.go, newrelic/resource_newrelic_infra_alert_condition.go, newrelic/resource_newrelic_nrql_alert_condition.go, newrelic/resource_newrelic_plugins_alert_condition.go
Without this change, in large environments it appears that we place too much
load on the backing services, which can cause sporadic behavior.  With recent
API key changes, we are now in a position to straddle the line between REST and
Nerdgraph for a single resource, and so here we use Nerdgraph to replace the
GetPolicy calls, which perform a list to detect if the policy in question exists
before throwing away the response.
=> chore: replace some v2 GetPolicy() with nerdgrpah QueryPolicy()

.github/ISSUE_TEMPLATE/bug_report.md
Due to the amount of issues (bug reports) we've been receiving without enough information to debug, we need to adjust some wording to be more explicit about what information is required when submitting a bug report. Hopefully this change will help us better assist users and facilitate more efficient resolution.
=> chore(issues): update bug report template

go.mod, go.sum
By enabling Personal API Key authorization in v0.43.0 of the client, we can enable this feature for Dashboards and partially for Synthetics.
=> feat(dashboard): enable Personal API Key auth for dashboards and some sythentics resources

.github/workflows/test.yml, README.md, build/test.mk, newrelic/provider_integration_test.go, newrelic/provider_test.go, newrelic/resource_newrelic_alert_policy_integration_test.go, newrelic/resource_newrelic_application_settings_test.go
- suppress integration tests on PRs initiated from a fork
- suppress JUnit test reporting on PRs initiated from a fork
- fix test-integration make target
- allow integration test suite to pass if environment has not been configured, skipping the tests inside
- update readme
=> chore: integration test improvements

build/test.mk, newrelic/resource_newrelic_alert_condition_integration_test.go, newrelic/resource_newrelic_entity_tags_test.go, newrelic/resource_newrelic_infra_alert_condition_test.go, newrelic/resource_newrelic_workload_test.go
To test, point the integration suite at an account other than the DTK test account and run.
DTK team members will need to set NR_ACC_TESTING=1 locally to run the entire suite after this is merged.
=> chore: allow integration tests to run for non-DTK accounts

newrelic/data_source_newrelic_account_test.go, newrelic/resource_newrelic_workload_test.go
This time fixing some tests so they no longer have to be run in a sub of account 1.
=> chore: allow integration tests to run for all accounts

website/docs/r/nrql_alert_condition.html.markdown
This PR adds documentation for newrelic_nrql_alert_condition aggregation window. It also reformats a few of the entries that had drifted a bit so that they match the predominant style.
=> docs: add website documentation for nrql_alert aggregation_window

website/docs/guides/getting_started.html.markdown
Because there is no Web UI for New Relic One users to get access to their personal API key, they need to execute a query to do so.  The official New Relic docs are in flux and don't show the correct instructions.
=> Add instructions for New Relic One users to get an api key

newrelic/resource_newrelic_dashboard.go, newrelic/resource_newrelic_dashboard_test.go, newrelic/structures_newrelic_dashboard.go, website/docs/r/dashboard.html.markdown
Resolves: #923 
Steps to manually test locally:
1. Using v2.7.5 of the provider, configure and provision a dashboard with multiple widgets with at least one widget being something more complex like displaying the apdex is an app with a `metric_line_chart` visualization.
```hcl
provider "newrelic" {
version = "2.7.5"
}
resource newrelic_dashboard" "foo" {
// ... configuration w/ widgets 'n such (no cross-account widgets)
}
```
2. Install the latest local version of the provider (the code in this PR) by commenting out the `version` part of the provider configuration.
```hcl
provider "newrelic" {
}
// ...
```
- Run ` rm -rf .terraform && rm terraform-provider-newrelic && go build && tf init` to reinitialize and install the provider using the local binary. **IMPORTANT: DO NOT DELETE THE STATE …
=> fix(dashboard): use state migration to fix 500 error when upgrading from v2.7.5 to v2.8+

.goreleaser.yml, main.go, newrelic/provider.go, version/version.go
Testing it out (easiest to test locally with Terraform version 0.12.x)
Create a .tf file with a simple provider configuration and do not add a `version` argument. 
```
provider "newrelic" {}
```
```
go build -ldflags "-s -w -X main.ProviderVersion=99999999" && terraform init && TF_LOG=debug terraform plan
```
Then search for `99999999`. It should exist in the logs somewhere 😎
=> chore(build): add temporary workaround for -ldflags to ProviderVersion during releases

CHANGELOG.md
This PR represents an update that contains work done under the hood and docs chore, hence no additions to the CHANGELOG.
=> chore(changelog): Update CHANGELOG for v2.13.1

website/docs/r/alert_policy_channel.html.markdown
The docs refer to data objects instead of resources, a small oversight but may be confusing for some users.
=> Fix docs for alert_policy_channel

newrelic/structures_newrelic_nrql_alert_condition.go, newrelic/structures_newrelic_nrql_alert_condition_test.go
Without this change, the deprecated attributes are preferred when they are found
within the state.  Here we reverse the order that the attributes are read to
determine if the particular resource has been migrated to the new API values.
This should ensure a clean migration from 1.x to 2.x in the case of an outlier
condition.
=> fix(nrql_alert_condition): reverse attribute detection for migration

newrelic/resource_newrelic_nrql_alert_condition.go, newrelic/resource_newrelic_nrql_alert_condition_test.go, newrelic/structures_newrelic_nrql_alert_condition.go, website/docs/d/entity.html.markdown, website/docs/guides/getting_started.html.markdown, website/docs/index.html.markdown, website/docs/r/nrql_alert_condition.html.markdown
Depends on https://github.com/newrelic/newrelic-client-go/pull/550
With the addition of `violation_time_limit_seconds` to NerdGraph's NRQL Alert Condition models, we now have a first class `seconds` field where users can choose an arbitrary value between 300s (5 minutes) and 2592000s (30 days). 
The old enum field `violation_time_limit` is restricted to a much smaller selection of values and is now deprecated in NerdGraph. 
Previously, a field `violation_time_limit_seconds` existed that accepted the same limited range of values as `violation_time_limit`, expressed as seconds. 
This PR deprecates the `violation_time_limit` field in favor of `violation_time_limit_seconds` to  align the NR terraform provider's representation of violationTTL with NerdGraph. 
Note to reviewer:
The fields …
=> Swap deprecation of violation_time_limit fields for NRQL alert condition

GNUmakefile, build/deps.mk, build/lint.mk, build/tools.mk, tools/go.mod, tools/go.sum
Cleanup a bit more, ensure that `make` now scans `tools/` for outdated packages as well.
=> chore(build): Add go-mod-outdated for tools/ to make

CONTRIBUTING.md, go.mod, go.sum, website/docs/guides/getting_started.html.markdown, website/docs/guides/migration_guide_v2.html.markdown, website/docs/guides/provider_configuration.html.markdown, website/docs/r/api_access_key.html.markdown, website/docs/r/dashboard.html.markdown, website/docs/r/workload.html.markdown
=> fix(config): update misleading missing API key error message

go.mod, go.sum, newrelic/resource_newrelic_one_dashboard.go, newrelic/resource_newrelic_one_dashboard_test.go, newrelic/structures_newrelic_one_dashboard.go, website/docs/r/one_dashboard.html.markdown
**Note:** These changes are for a CLOSED BETA feature, where breaking changes are expected.
The NerdGraph Dashboard API has change shape slightly to be more consistent with other areas of the API.  Updates to the HCL have also been driven down for consistency.
Existing API will be removed on Jan 22, 20201
Here's an example of the change to end-users:
```hcl
resource "newrelic_one_dashboard" "bar" {
name = "bar dashboard"
permissions = "private"
page {
name = "bar dashboard"
widget_bar {
title = "foo"
row = 4
column = 1
query {
account_id = 12345
nrql      = "FROM Transaction SELECT count(*) FACET name"
}
}
}
}
```
```hcl
resource "newrelic_one_dashboard" "bar" {
name = "bar dashboard"
permissions = "private"
page {
name = "bar dashboard"
widget_bar {
title = "foo"
row = 4
column = 1 …
```
=> Update for Dashboard API change [CLOSED BETA]

tools/go.mod, tools/go.sum, website/docs/r/one_dashboard.html.markdown
The example code for the `newrelic_one_dashboard` resource had an unused `newrelic_entity` section.
FYI: @jsbnr
=> Update one_dashboard docs

newrelic/resource_newrelic_nrql_alert_condition.go, website/docs/r/nrql_alert_condition.html.markdown
Better align the documentation about NRQL condition terms threshold validation with how they are being validated by the downstream service that registers them.
- _Only_ updates documentation; no "code" changes
- Calls out that:
- Terms thresholds are validated against the aggregation window
- That different NRQL condition types have different validation applied to their durations
**Open question:** this raises a question about whether the [`ValidateFunc` for `threshold_duration`](https://github.com/newrelic/terraform-provider-newrelic/blob/bcf78ca22ff40f5a398e99cd3ac833fe938c1d52/newrelic/resource_newrelic_nrql_alert_condition.go#L73,L92) is generating false positives _and_ false negatives during the `plan` phase. I'm a newcomer to Terraform, so I may be misinterpreting what's happening …
=> docs(nrql_alert_condition): Amends threshold_duration constraints for NRQL alert conditions

go.mod, go.sum, tools/go.mod, tools/go.sum
- Update newrelic-client-go to v0.57.0 (Removes unused Queries field)
=> Update for NR1 Dashboards

go.mod, go.sum, newrelic/resource_newrelic_one_dashboard.go, newrelic/resource_newrelic_one_dashboard_test.go, newrelic/structures_newrelic_one_dashboard.go, website/docs/r/one_dashboard.html.markdown
Fixes: #1128 
As it stands right now, the new `linked_entity_guids` attribute will only be supported by the following widgets: `bar`, `line`, and `pie`.
Checklist
=> feat(one_dashboard): add linked entities to widget schema

newrelic/structures_newrelic_nrql_alert_condition.go, newrelic/structures_newrelic_nrql_alert_condition_test.go
fixes #1157
Without this change, we attempt to set an invalid operator on baseline and
outlier conditions.  This looks to be a change in the upstream API to perform
more validation, which is then surfaced as an API error to the Terraform user,
but without the needed context about why the call was invalid.  Here we catch
this condition during the expandNrqlConditionTerm code to ensure that we don't
attempt to make the call, and give back a reasonable error to the user.
=> fix(nrql_alert_condition): validate operator based on condition type

newrelic/resource_newrelic_alert_muting_rule.go, newrelic/resource_newrelic_alert_muting_rule_test.go
fixes [issue #1153](https://github.com/newrelic/terraform-provider-newrelic/issues/1153)
muting rule condition tags have a special format that's parsed out before matching. They need to be in the format of `tag.some_value`.
The StringInSlice validation was treating tags like a normal attribute name, so any correctly configured tag was failing, and only the incorrectly formatted condition of `tag` would pass.
More details and repro steps [in the issue](https://github.com/newrelic/terraform-provider-newrelic/issues/1153)
=> fix (newrelic_alert_muting_rule): condition tag validation

go.mod, go.sum, newrelic/data_source_newrelic_entity_test.go, newrelic/resource_newrelic_alert_muting_rule.go, newrelic/resource_newrelic_alert_muting_rule_test.go, newrelic/structures_newrelic_alert_muting_rule.go, newrelic/structures_newrelic_alert_muting_rule_test.go, website/docs/r/alert_muting_rule.html.markdown
Add support for configuration of `newrelic_alert_muting_rule schedule` fields with Terraform. 
Closes #1156
Requires https://github.com/newrelic/newrelic-client-go/pull/652. 
I've bumped the client version here to .57.2, so this should also close out #1162 
Add new MutingRuleScheduleSchema struct & field validation:
* Add validateNaiveDateTime struct for testing conversion from go's time.time to an "offsetless" NaiveDateTime in NerdGraph
Add expand and flatten funcs for the schedule. Please note the following idiosyncracies which were accounted for in the funcs:
* Nerdgraph only accepts a NaiveDateTime but returns a full 8601 dateTime with an offset. To prevent drift, this offset must be removed before any of these dateTime fields are stored in state
* It's possible to configure a WEEKLY …
=> feat(alert_muting_rule): add schedule support

newrelic/resource_newrelic_alert_muting_rule_test.go
Fix broken muting Rule tag validation test - 
Test output string needs to include `resourceName`
=> fix(alert_muting_rule): update test expectation to match input

go.sum, newrelic/resource_newrelic_alert_muting_rule.go, newrelic/resource_newrelic_alert_muting_rule_test.go, newrelic/resource_newrelic_one_dashboard.go, newrelic/resource_newrelic_one_dashboard_test.go, newrelic/structures_newrelic_alert_muting_rule_test.go, newrelic/structures_newrelic_one_dashboard.go, website/docs/r/one_dashboard.html.markdown
Currently you must specify the `account_id` for every `nrql_query`.  This change follows the rest of the provider in allowing that value to be inherited from the `account_id` of the dashboard (which is inherited from the API key used).
Resolves #1174
=> [one_dashboard]: Inherit nrql_query account_id from parent dashboard

newrelic/resource_newrelic_one_dashboard.go, newrelic/resource_newrelic_one_dashboard_test.go
Some widgets validate NRQL and return errors on invalid syntax.  This PR includes additional error checks on Create to ensure we got a GUID back, and if not return any errors that the API gave us to the user.
Includes a working test with `widget_line` and invalid NRQL.
Resolves #1248
=> chore(one_dashboard): additional error catching on create + test

newrelic/data_source_newrelic_entity.go, newrelic/data_source_newrelic_entity_integration_test.go, website/docs/d/entity.html.markdown
The API does not enforce case, though the provider comparison does.  Keep the previous behavior (case-sensitive) and add a new schema attribute `ignore_case`.
Resolves: #1214
=> feat(newrelic_entity): Add ignore_case to name search for entity

CHANGELOG.md
- **alert_channel:** Ensure include_json_attachment is sent to API as `true` or `false` string
- **alert_policy_channel:** Ignore configured channel_id order  (convert to Set)
- Add NRQL Drop Rule support
=> chore(changelog): Update CHANGELOG for v2.21.0

scripts/release.sh, tools/go.mod, tools/go.sum, tools/tools.go
Now that our pull request ([#78](https://github.com/git-chglog/git-chglog/pull/78)) has been merged into the `git-chglog`, we can use the `--sort` flag to sort our tags/releases by semver version. We were originally accomplishing this by using a fork of `git-chlog` 😎
=> chore(build): update git-chglog now that --sort flag has been implemented

newrelic/structures_newrelic_infra_alert_condition.go, newrelic/structures_newrelic_infra_alert_condition_test.go
`expandInfraAlertThreshold` assumes we have data, so validate the length of data passed is greater than zero, otherwise return `nil`
Reported in #606
=> fix(newrelic_infra_alert_condition): Prevent index out of range

website/docs/guides/migration_guide_newrelic_dashboard.html.markdown
Added a couple of links to our docs that provide more information on how to migrate certain visualisations.
=> feat(docs): added documentation links to the dashboard migration guide

build/compile.mk
The `compile-only` and `compile-all` targets were not working for this repo.  This PR fixes them so that they can be used to build a local binary that can be used during development with a `.terraformrc` file that looks like this:
```
provider_installation {
dev_overrides {
"newrelic/newrelic" = "/path/to/src/terraform-provider-newrelic/bin/darwin"
}
direct {}
}
```
=> fix(build): fix compile-only and compile-all build targets to aid with local development

newrelic/resource_newrelic_nrql_alert_condition.go, newrelic/resource_newrelic_nrql_alert_condition_test.go, newrelic/structures_newrelic_nrql_alert_condition.go, newrelic/structures_newrelic_nrql_alert_condition_test.go, website/docs/r/nrql_alert_condition.html.markdown
[Jira Ticket](https://newrelic.atlassian.net/browse/AINTER-7816)
[Docs Update Ticket](https://newrelic.atlassian.net/browse/AINTER-7817)
-----
[Corresponding Go Client PR](https://github.com/newrelic/newrelic-client-go/pull/805)
**Description:**
This ticket adds [Streaming Methods](https://nerdlife.datanerd.us/new-relic/two-new-aggregation-methods-in-incident-detection-3d2007fb-e9b5-42b2-9001-3abbe242e4bf) support to Alerts NRQL conditions including three new fields: `AggregationMethod`, `AggregationDelay`, and `AggregationTimer`.
It also maintains backwards compatibility for `nrql.evaluationOffset`
Example TF Config to create a condition with streaming methods:
```
resource "newrelic_nrql_alert_condition" "streaming-methods-condition" {
name = "Streaming methods"
policy_id = 1220119
nrql …
```
=> feat(Alerts): Add streaming methods fields to nrql alert conditions

newrelic/resource_newrelic_nrql_alert_condition.go, website/docs/r/nrql_alert_condition.html.markdown
Outlier conditions are deprecated. All outlier conditions will be removed Feb 1, 2022.
This PR adds a warning to notify users to this upcoming deadline, with a link to an informational post.
Anyone interacting with an `outlier` condition type will see this message:
This also updates the docs and resource description. See AINTER-8224 for more details
=> chore(nrql_alert_condition) add eol warning for outlier type

website/docs/r/service_level.html.markdown
- Remove name and description for the SLO in the example of the docs. It is not documented in the docs, it is ignored on the UI and it is not required in the API.
=> docs(servicelevel): Fix example in the docs

newrelic/structures_newrelic_nrql_alert_condition.go
Fixes issue #1433
When importing a condition, no resource exists in TF state and the check for `violation_time_limit_seconds` will always fail, causing the deprecated `violation_time_limit` field to be used instead. This change specifically checks for `violation_time_limit`, and if both fields are missing we will import the new field for `violation_time_limit_seconds`
=> fix: use violation_time_limit_seconds on condition import

newrelic/structures_newrelic_alert_muting_rule.go
This resolves issue https://github.com/newrelic/terraform-provider-newrelic/issues/1542
If a Muting Rule has a `schedule` block and both `WeeklyRepeatDays` and `Repeat` are nil, this was crashing the plugin on `terraform apply`. The changes here prevent this from crashing by verifying that `Repeat` is not nil before checking the value.
=> fix: muting rule with repeat = null crashes plugin

newrelic/resource_newrelic_nrql_alert_condition.go, newrelic/structures_newrelic_nrql_alert_condition.go
This fixes issue https://github.com/newrelic/terraform-provider-newrelic/issues/1544
When the `aggregation_method`, `aggregation_delay`, and `aggregation_timer` fields are not provided in Terraform config we use default values. This currently shows a diff when running `terraform plan` even though the values are not changing. This PR adds a check to see if those fields were provided in Terraform, and if not we do not show the difference.
=> aggregation_method and aggregation_delay show diff when not provided and default values are used

newrelic/resource_newrelic_synthetics_monitor_script.go
According to the steps in the [documentation](https://newrelic.zendesk.com/hc/en-us/articles/1500005170762-Calculating-the-HMAC-value-for-a-VSE-Password-on-your-private-location) for computing the HMAC for use with Synthetic scripts, the algorithm for computing the HMAC requires base64 encoding the _hexadecimal encoded_ HMAC. The previously implemented algorithm skipped the hexadecimal encoding resulting in incorrect values.
Fixes #1578
=> Correct the HMAC calculation using VSE password

newrelic/resource_newrelic_alert_condition.go, newrelic/resource_newrelic_alert_condition_unit_test.go
The Terraform provider is currently validating the length of the condition name for `resource_newrelic_alert_condition`, but this validation also happens in the Condition API. We are removing the TF validation to defer to the Condition API validation instead. This makes `resource_newrelic_alert_condition` match the other alert condition types that do not have validation in TF.
=> fix: Remove condition name length validation

newrelic/resource_newrelic_service_level.go, website/docs/index.html.markdown, website/docs/r/service_level.html.markdown
- Update docs and validation since SLO periods now only include complete weeks. The API is no longer accepting a 30 days period.
- Update index to add the service level resource.
=> docs(servicelevel): SLO periods now include complete weeks

newrelic/structures_newrelic_nrql_alert_condition.go
This fixes an issue in 2.36.0 where unset slideBy values were being represented as 0 in state. This caused some confusing diffs as slide_by=0 was added to state.
=> fix(rql_alert_condition): Add nil check when flattening slide_by

newrelic/resource_newrelic_service_level.go, website/docs/r/service_level.html.markdown
This option would be removed in favour of 1, 7 and 28 days.
We have not detected usage of this particular value.
=> fix(service_levels): Removing an option of 14 days for trailing windows

newrelic/resource_newrelic_nrql_alert_condition.go, website/docs/r/nrql_alert_condition.html.markdown
This removes the `computed` designation from nrql_alert_condition's slide_by field, which was preventing the field from being nulled out if removed from the local TF config.
It also includes docs updates for slide_by that @akane opened in #1624
=> Remove computed slideby

newrelic/resource_newrelic_nrql_alert_condition.go
https://github.com/newrelic/terraform-provider-newrelic/issues/1613
* Remove incorrect validation logic for `threshold_duration` from `newrelic_nrql_alert_condition`. This makes Condition API validate for the correct `aggregation_window` and `threshold_duration` values.
**Valid Condition**
1. Create a valid condition whose critical or warning `threshold_duration` is not evenly divisible by 60. 
2. Expect that the condition can be created well. 
Example resource
```
resource "newrelic_alert_policy" "foo" {
name = "foo"
}
resource "newrelic_nrql_alert_condition" "foo" {
policy_id                    = newrelic_alert_policy.foo.id
name                         = "myname"
violation_time_limit_seconds = 3600
aggregation_window           = 59
aggregation_delay            = 120
value_function …
```
=> fix(nrql_alert_condition): Move condition validation to API

website/docs/guides/getting_started.html.markdown
This change fixes a broken link in the docs
=> docs: fix broken link to terraform docs

website/docs/r/nrql_drop_rule.html.markdown
We are preparing general release of drop rules for metric aggregate attributes, so this PR removes the beta-specific blurb.
=> docs: remove beta info ahead of general release

website/docs/d/entity.html.markdown, website/docs/r/alert_muting_rule.html.markdown, website/docs/r/entity_tags.html.markdown, website/docs/r/events_to_metrics_rule.html.markdown, website/docs/r/nrql_alert_condition.html.markdown, website/docs/r/nrql_drop_rule.html.markdown
The links in the docs are broken: https://registry.terraform.io/docs/providers/newrelic/index. The PR links to migration V2 guid correctly.
Via testing new link: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/migration_guide_v2
=> Fix broken V2 migration links

newrelic/resource_newrelic_nrql_alert_condition.go, newrelic/resource_newrelic_nrql_alert_condition_test.go, newrelic/structures_newrelic_nrql_alert_condition.go, newrelic/structures_newrelic_nrql_alert_condition_test.go, website/docs/d/entity.html.markdown, website/docs/guides/getting_started.html.markdown, website/docs/index.html.markdown, website/docs/r/nrql_alert_condition.html.markdown
https://newrelic.atlassian.net/browse/AINTER-8206
Corresponding Go Client ticket https://github.com/newrelic/newrelic-client-go/pull/850
**This PR requires a MINOR release and should ensure the changelog has an entry noting NRQL condition  deprecation of fields `value_function`, `sum`, and `single_value`.**
This PR should:
- Make nrql condition `value_function` optional for create and update
- Add deprecation warning messages for `sum`, `single_value`, and `value_function`
- Update documentation
- Ensure the changelog has an entry noting the deprecation
- Be released as a MINOR release
Deprecation warning example:
I added integration tests.  Also, please manually test.  See below.
To manually test:
- …
=> feat(Alerts): deprecate nrql condition value_function, sum, single_value

newrelic/resource_newrelic_service_level.go, website/docs/r/service_level.html.markdown
Due to upcoming changes in the service levels product, SLIs should contain one and only one objective.
The [release notes](https://github.com/helenapm/docs-website/blob/b57d2faa0e7eabb968d9e38baebfb9307473655a/src/content/docs/release-notes/service-levels-release-notes/service-levels-20220225.mdx) with the breaking changes in the docs-website will be published in the next hours.
=> feat(servicelevel): SLI should contain one and only one objective

newrelic/structures_newrelic_one_dashboard.go
This change handles reading `linked_entity_guids` after they've been set through `filter_current_dashboard`
Fixes #1494 
Use the following HCL config
```
resource "newrelic_one_dashboard" "default" {
name        = "Ticket 1494"
description = "Managed via Terraform"
page {
name        = "Simple Page"
description = "Simple Page"
widget_pie {
title                    = "Filter Example"
row                      = 1
column                   = 1
width                    = 5
height                   = 5
linked_entity_guids      = null
filter_current_dashboard = true
nrql_query {
query = "FROM K8sClusterSample select uniqueCount(hostname) FACET clusterName limit max since 5 minutes ago"
}
}
widget_pie {
title                    = "Target Example"
row …
```
=> Handle setting linked_entity_guids

website/docs/r/alert_channel.html.markdown, website/docs/r/alert_policy_channel.html.markdown
Fixed two incorrect warnings for accountID. In these two cases the accountID can be set in the resource. 
=> fix(docs): removed two accountID warnings that were incorrect

newrelic/resource_newrelic_nrql_alert_condition.go
This fix will force TF to create a new condition if the type changes. 
Fixes #1744 
1. Create an alert policy & condition using the following HCL file
```
resource "newrelic_alert_policy" "policy" {
name                = "alert-policy"
incident_preference = "PER_POLICY"
}
resource "newrelic_nrql_alert_condition" "condition" {
policy_id                      = newrelic_alert_policy.policy.id
type                           = "static"
name                           = "foo"
description                    = "Alert when transactions are taking too long"
runbook_url                    = "https://www.example.com"
enabled                        = true
violation_time_limit_seconds   = 3600
fill_option …
```
=> Force to create new alert condition if type changes

newrelic/resource_newrelic_nrql_alert_condition.go
* Removed non-existent `signal` block from deprecation message for `since_value` and `evaluation_offset`
* Fix typo
=> docs: Remove signal block from deprecation message

newrelic/resource_newrelic_service_level.go, website/docs/r/service_level.html.markdown
Since some time 14 days SLIs are not allowed anymore, this was out of date in the provider, so 14 days was accepted by terraform but then receiving an error when going to the APi.
- [X ] Bug fix (non-breaking change which fixes an issue)
-
=> fix: remove 14 days deprecated option from service levels

newrelic/resource_newrelic_entity_tags.go
Very often tags resource is used referencing the dependency (i.e. entity) implicitly. If that entity is re-created, the tags resource doesn't refresh and continues referencing to the old entity GUID.
I believe that the fix should also address the following issue: https://github.com/newrelic/terraform-provider-newrelic/issues/1556
=> fix: Tags resource implicit dependency

newrelic/structures_newrelic_alert_channel.go
Updating newrelic_alert_channel read to correctly import the payload_string field when importing an Alerts Notification Channel. `payload` and `payload_string` were both previously ignored when importing because neither field was already set on the resource data.
This is always imported as the `payload_string` field because all payloads are valid in the `payload_string`, but more complex payloads are not valid in the `payload` field.
Fixes #1142 
- Create a webhook notification channel and enter a custom payload
- Import this channel into Terraform
- Check terraform state to verify that the …
=> fix: Import payload_string when importing webhook channel

newrelic/data_source_newrelic_alert_channel.go
The "data_source_newrelic_alert_channel" started failing to retrieve channel data after the changes made in https://github.com/newrelic/terraform-provider-newrelic/pull/1755
This was happening because the `payload_string` field used when reading data for a resource that does not exist in Terraform yet did not exist on the data_source version of alerts channels. Adding this field allowed me to use "data_source_newrelic_alert_channel" successfully again.
Fixes #1761 
- Create a webhook Alert channel in the UI
- Create a "data_source_newrelic_alert_channel" in terraform config that references the …
=> fix: Add payload_string to channel data source

newrelic/resource_newrelic_nrql_alert_condition.go, newrelic/structures_newrelic_nrql_alert_condition.go, newrelic/structures_newrelic_nrql_alert_condition_test.go, website/docs/r/nrql_alert_condition.html.markdown
Exposes the EntityGUID on NRQL Conditions to enable tagging of conditions via terraform.
Fixes https://newrelic.atlassian.net/browse/AINTER-8514
* Create a NRQL Alert Condition and add tags to it using the `newrelic_entity_tag` resource
```
variable "nr_api_key" {
type = string
description = "your new relic API key"
}
variable "account_id" {
type = number
description = "your new relic account"
}
variable "region" {
type = string
description = "the region you're using."
}
provider newrelic {
api_key = var.nr_api_key
account_id = var.account_id
region = var.region
}
resource "newrelic_alert_policy" "alex_terraform" {
name = "Alex Terraform Test Policy"
account_id = 400304
}
// Create a new condition and link it directly to an entity tag thing. …
```
=> feat: Expose NRQL Condition EntityGUID on conditions

newrelic/resource_newrelic_nrql_alert_condition.go, website/docs/r/nrql_alert_condition.html.markdown
Remove validation that prevents creating a negative NRQL condition threshold. This brings the provider in-line with the UI and API.
Fixes #1643
- Use the `newrelic_nrql_alert_condition` resource to create a non-baseline NRQL condition with a negative threshold e.g. 
```
critical {
operator              = "above"
threshold             = -9.987
threshold_duration    = 300
threshold_occurrences = "ALL"
}
```
=> fix(alerts): Allow negative threshold values for non-baseline NRQL conditions

README.md
Small fix to README to remove broken Terraform logo
=> chore(docs): removed broken Terraform logo

newrelic/resource_newrelic_service_level.go
After the creation of the SLI instead of reading the resource (that is causing issues cause in some cases is still not indexed in Entity Platform, causing the creation to fail) we are using the answer of the create mutation to write the state, since is the same resource returned
https://github.com/newrelic/terraform-provider-newrelic/issues/1792
- [X ] My commit message follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- Create N SLI
- All the SLIS should succeed
=> fix: remove unnecesary read of service level entity after creation

newrelic/resource_newrelic_service_level.go, website/docs/r/service_level.html.markdown
Force service level recreation when updating account_id.
Today is not possible to change the account id of a service level, so when changing the account in the terraform the resources are shown as updated, but in the API is a no-operation.
- Create an SLI
- Change account_id
- New SLI should be created
=> fix: force service level when changing account id

newrelic/resource_newrelic_notifications_channel_test.go, newrelic/resource_newrelic_notifications_destination_test.go
⚠️ Notifications and Destinations need additional work to be feature complete. The PR is skipping the integration tests to allow the test suite to continue.
=> chore(notifications): temporarily skip notifications and destinations

website/docs/r/synthetics_multilocation_alert_condition.markdown
Documentation improvement to remove confusion on entities
Fixes #1929 
Documentation change to clarify which GUID to use in `synthetics_multilocation_alert`.
Tested with manually creating Synthetics check in UI, and the following code:
```
resource "newrelic_alert_policy" "ssl_certs" {
name                = "SSL Certificates PROD"
incident_preference = "PER_CONDITION_AND_TARGET"
}
resource "newrelic_synthetics_multilocation_alert_condition" "ssl_cond" {
policy_id = newrelic_alert_policy.ssl_certs.id
name                         = "SSL CDN (W/TF)"
enabled                      = true
violation_time_limit_seconds = "43200" #3 days
entities = ["monitor ID"]
warning { threshold = 1 }
critical { threshold = 2 }
depends_on = [ …
```
=> chore(docs): improved documentation for synthetics_multilocation_alert (fixes #1929)

newrelic/resource_newrelic_entity_tags.go
Having hard time reproducing #1556 It looks like the API takes some time to apply the tags, which makes Terraform think the tags haven't been applied. Adding this to check if an increased timeout removes the issue for the impacted users. 
=> fix(newrelic_entity_tags): extended timeout to see if it fixes not found errors

newrelic/resource_newrelic_service_level.go
Service level resource not getting create if deleted from UI #1906
1. Removed error return value from the read function.
- Step 1
- Step 2
- etc
=> chore: resolved service level issue NR-39929

newrelic/resource_newrelic_notifications_destination.go
fix(src): Delete exactlyOne validation in scheme of Notification Destination
An error occurs when not supplying a block for either auth_basic or auth_token in the newrelic_notification_destination resource, even when auth is not required.
#1963 newrelic_notification_destination requires an authentication type even if no auth is required
- Step 1
- Step 2
- etc
=> fix(src): Delete exactlyOne validation in scheme 

newrelic/resource_newrelic_notifications_channel.go
Fixes #1994 
Configured the account_id field of newrelic_resource_notifications_channel to be an optional, computed field.  This should result in the account_id now being optional, which matches the documentation.  I've tried to follow the established patterns I've seen in similar fixes.  
(This is also my first PR on GitHub, please forgive any PR related faux pas!)
- Create a Terraform configuration that defines a newrelic_resource_notifications_channel resource.
- Verify the account_id attribute is _not_ set in the resource block.
- Verify the account_id is defined in either the provider block …
=> fix(notifications): made account_id optional #1994

newrelic/structures_newrelic_synthetics_simple_monitor.go
Updated the "buildSyntheticsSimpleMonitorUpdateStruct" function so the uri and custom_header fields are set on the "SyntheticsUpdateSimpleMonitorInput" struct that is returned.  This results in those fields being sent to the GraphQL endpoint and updated with any changes.  I believe the uri not being populated was the root cause of the linked issue.
Fixes #1984 
- Use the configuration from the [gist](https://gist.github.com/usfdmiller/a8f362bd96d5d0e32d00e81fbe27785f).
- Run "terraform apply"
- Verify the monitors were created on the New Relic website.
- Change the custom_header and uri attributes.
- Run "terraform apply" again.
- Verify on the New Relic website the values have been …
=> fix(simple_monitor): #1984 populating uri and custom headers

website/docs/r/one_dashboard.html.markdown
The provided example for [newrelic_one_dashboard](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/one_dashboard) has an incorrect value for permissions.  Currently set to 'public_read' and should be 'public_read_only'.
- [x ] This change requires a documentation update
=> Fix incorrect permission value in dashboard docs

website/docs/guides/migration_guide_v3.html.markdown
The upgrade pathway is currently broken. Users can upgrade safely using terraform commands to temporarily exclude monitors from Terraform.
Fixes #1987
Refer to GitHub issue
=> fix(docs): Add safe migration pathway for monitors

newrelic/resource_newrelic_notifications_destination.go, newrelic/resource_newrelic_workflow.go, newrelic/structures_newrelic_workflow.go, newrelic/structures_newrelic_workflow_test.go
Currently, if workflow does not have any enrichments we show a bogus diff in TF plan even if nothing has actually been changed:
```
resource "newrelic_workflow" "workflow-example" {
id                    = <UUID>
name                  = <name>
- enrichments {
}
}
```
The root cause of this problem is the difference in how we treat a workflow with no enrichments when we create a new workflow vs. when we retrieve the current state of the workflow:
- For new workflows, workflow resource's `enrichments` field is not set if the workflow has no enrichments
- When retrieving the state, `enrichments` field is set to an empty set if the workflow has no enrichments
This PR changes the retrieval logic to mimic the new state logic. This should retroactively fix bogus `plan` diffs for all customers …
=> fix(workflows): fix bogus diff for workflows with empty enrichments

newrelic/resource_newrelic_application_settings.go
Use the same logic as data_source_newrelic_application for finding the correct APM app in resource_newrelic_application_settings. This resolves the issue of the resource failing to find an application that uses a name that's a substring of another app. E.g. "api" would previously not be found if another app was called "privateapi" because multiple results were returned by the APM client.
Fixes #2013
- Create an application in newrelic called "app"
- Create a second application in newrelic called "appduplicate"
- Apply the terraform change that will set the apdex threshold on the first …
=> Stop fuzzy search on resource_newrelic_application_settings failing applies

website/docs/r/synthetics_monitor.html.markdown, website/docs/r/synthetics_monitor_broken_links.html.markdown, website/docs/r/synthetics_monitor_cert_check.html.markdown, website/docs/r/synthetics_monitor_step.html.markdown, website/docs/r/synthetics_script_monitor.html.markdown
Makes it explicit that NerdGraph is used and that the `AWS_` prefix should be removed.
Came across an issue where the link mentioned using a specific region, so created a copy+paste error as we didn't know NerdGraph was used under the hood until we compared the example and assumed that must be the issue.
- Copy text of documentation.
- Paste into https://registry.terraform.io/tools/doc-preview
- Verify documentation layout.
=> docs(synthetics_monitor): mentions NerdGraph is used.

newrelic/resource_newrelic_synthetics_secure_credential.go, newrelic/resource_newrelic_synthetics_secure_credential_test.go
This PR increases the timeout for the resource_secure_credential test to give the entity a chance to index.
Secure credentials test should stop failing intermittently with `"Error: entity not found, or found more than one"` message
=> fix: up timeout to give entity chance to index

newrelic/structures_newrelic_service_level.go
Adding validation for the case were the select is not defined in the TF but was modified via API or UI, so we can distinguish the change in TF.
=> fix: add check of default answer of the API for service level select

go.mod, go.sum, newrelic/resource_newrelic_service_level.go, newrelic/resource_newrelic_service_level_test.go, newrelic/structures_newrelic_service_level.go, website/docs/r/service_level.html.markdown
Added the capability to define the select field in the event queries of the service levels, to allow the usage of the SUM function.
- [ X] New feature (non-breaking change which adds functionality)
- 
- [X ] I have performed a self-review of my own code
- [X ] I have added tests that prove my fix is effective or that my feature works
- [X ] New and existing unit tests pass locally with my changes. Go [here](https://github.com/newrelic/terraform-provider-newrelic#testing) for instructions on running tests locally.
```
resource "newrelic_service_level" "foo" {
guid = $someEntityGuid
name = "TF PROVIDER TEST"
description = "TF PROVIDER TEST."
events {
account_id = $accountId
valid_events {
from = "Transaction"
where = "(transactionType='Web')" …
```
=> feat: bump of new-relic-client-go and add service level capability to use select field for event queries

newrelic/resource_newrelic_workflow.go, newrelic/resource_newrelic_workflow_test.go
Each workflow is assigned to a specific NewRelic account, no matter whether or not you define account_id in the workflow resource. If not defined explicitly, workflow account_id is just set to the account_id configured in the provider settings.
Currently workflow.account_id is optional but not marked as computed. This results in a situation where you can create a workflow without specifying account_id explicitly, but all subsequent applies fail because TF thinks that we want to change account_id to `null`.
This PR marks the field as "computed" and thus telling TF that it should not consider an empty account_id as an account_id change.
Fixes https://github.com/newrelic/terraform-provider-newrelic/issues/2032 (partially)
Please delete options …
=> fix(workflows): stop forcing workflow recreation when using default account id

newrelic/config.go, newrelic/data_source_newrelic_alert_policy.go, newrelic/provider.go, newrelic/provider_unit_test.go, newrelic/resource_newrelic_alert_policy.go, newrelic/resource_newrelic_entity_tags.go, newrelic/resource_newrelic_events_to_metrics_rule.go, newrelic/resource_newrelic_nrql_drop_rule.go, newrelic/resource_newrelic_one_dashboard.go, newrelic/resource_newrelic_one_dashboard_json.go, newrelic/resource_newrelic_one_dashboard_raw.go
Removed some outdated code to check if an API_KEY was set (User API Key). Most of our resources now use GraphQL and the field was already set to `required` in the docs. 
This change removes a check from the resources and makes the field `required` in provider configuration.
=> Removed deprecated api_key check and made api_key required

newrelic/resource_newrelic_notifications_channel.go, newrelic/resource_newrelic_notifications_channel_test.go, newrelic/resource_newrelic_workflow_test.go
Currently, if TF expects a channel with a given ID to exist but it does not, instead of reporting that the remote object does not exist we return an error.
In practice, the current behaviour results in two problems:
1. If a channel was already created/imported into your TF state but then deleted externally, the state would get corrupted and `plan`, `refresh`, and `apply` would just start failing
2. If you try to import a channel using a wrong ID, you would get a weird error instead of the standard "Cannot import non-existent remote object"
The second problem is fairly minor. 
The first one is not only a major issue, it also happens very often because of how workflows interact with channels. Namely, if you delete a workflow, it automatically deletes the associated channel. 
If you only …
=> fix(workflows): correctly handle notification channels deleted outside TF

website/docs/r/one_dashboard.html.markdown
When importing a New Relic One dashboard I was really confused by the example as I couldn't see the GUID. After guessing hey it's probably imported by GUID I was okay, but the docs should be fixed.
It's not clear to me why it was broken so my idea was to find one that is visible:
https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/cloud_aws_govcloud_link_account#import
And copy that code style (add bash descriptor + use lower case text) to:
https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/one_dashboard#import
Not quite sure but hopefully someone from the docs team will know how we can test this or notify me of any changes required :)
=> fix: dashboard import statement missing guid

go.mod, go.sum, newrelic/resource_newrelic_workflow_test.go, newrelic/structures_newrelic_workflow.go
Once you have added at least one enrichment to a workflow, it is currently impossible to remove all of them without deleting the entire workflow. 
I also did a tiny refactoring in a couple of methods.
The main fix was in the newrelic client, this PR just updates the client version and adds tests to reproduce the issue and verify the fix.
You can use the examples added in integration tests to reproduce the problem manually as well.
=> fix(workflows): make it possible to remove all workflow enrichments

newrelic/resource_newrelic_alert_policy_channel.go, newrelic/resource_newrelic_nrql_alert_condition.go
Change to read function to avoid setId("") happening. I think we need to verify the resource has been created by reading it back before setting the Id.
=> chore(newrelic_nrql_alert_condition): move read to create function to avoid root resource not found

newrelic/data_source_newrelic_synthetics_private_location.go, newrelic/data_source_newrelic_synthetics_private_location_test.go, website/docs/d/synthetics_private_location.html.markdown
This makes the private location search more specific by including account ID as a search parameter
=> Add optional account_id parameter to private location data source

newrelic/resource_newrelic_alert_condition.go, newrelic/resource_newrelic_alert_muting_rule.go, newrelic/resource_newrelic_infra_alert_condition.go, newrelic/resource_newrelic_nrql_alert_condition.go, newrelic/resource_newrelic_synthetics_multilocation_alert_condition.go, website/docs/r/alert_condition.html.markdown, website/docs/r/alert_muting_rule.html.markdown, website/docs/r/infra_alert_condition.html.markdown, website/docs/r/nrql_alert_condition.html.markdown
Updating instances of "violation" to be "incident" in the Alerts resources documentation. This reflects a change in nomenclature that is represented elsewhere (e.g., New Relic's public documentation, UI copy in the web app). Note that this **does not** update instances of "violation" in any API field names.
Changes are only to documentation.
=> docs: Update 'violations' to 'incidents' in Alerts docs

newrelic/data_source_newrelic_entity.go, newrelic/data_source_newrelic_entity_integration_test.go, website/docs/d/entity.html.markdown
This PR removes the limit on tags that can be given as search parameters for the entity data source
Fixes #2095 
Add more than 1 tag when using the entity data source and TF should not throw any errors and find the entity you're looking for.
=> feat(data_source_entity): remove limit on tags

newrelic/resource_helpers_synthetics.go, newrelic/resource_newrelic_synthetics_script_monitor.go, newrelic/resource_newrelic_synthetics_script_monitor_integration_test.go
This pull request facilitates setting the following additional schema attributes for the `newrelic_synthetics_script_monitor` resource. 
- `period`
- `runtime_type`
- `runtime_type_version`
- `script_language` 
- `status`
Fixes: #2078
=> fix(synthetics): set additional attribute values on import

newrelic/resource_newrelic_synthetics_monitor.go, newrelic/resource_newrelic_synthetics_monitor_test.go
Extension of #2117 
This pull request facilitates setting the following additional schema attributes for SIMPLE and SIMPLE_BROWSER monitor types on the `newrelic_synthetics_monitor` resource. 
- `period`
- `status`
- `verify_ssl` 
- `validation_string` 
- `runtime_type` (browser only)
- `runtime_type_version` (browser only)
- `script_language` (browser only)
Fixes: #2078
=> fix(synthetics): set period and status during read/import operations

newrelic/resource_newrelic_nrql_alert_condition_test.go, newrelic/resource_newrelic_service_level_test.go, newrelic/resource_newrelic_synthetics_alert_condition_test.go, newrelic/resource_newrelic_workflow_test.go
This PR introduces the following updates:
- uses `testAccPreCheckEnvVars()` instead of `testAccPreCheck()` in some tests that do not require an application entity to be created. This reduces associated test execution times.
- fixes an HCL syntax issue in some workflow tests
- adds a cleanup/sweeper function to delete any dangling service level resources so we don't exceed the limit for service level rules in our integration testing account
=> tests: fix service level and workflow tests

newrelic/resource_newrelic_nrql_alert_condition.go
Fixes issue created in https://github.com/newrelic/terraform-provider-newrelic/pull/2082 where the `entity_guid` property is no longer set when a newrelic_nrql_alert_condition has been created.
Restores the call to `flattenNrqlAlertCondition` which was lost when `resourceNewRelicAlertPolicyChannelRead` stopped being called. `flattenNrqlAlertCondition` sets a number of properties on the resource including the `entity_guid`.
Fixes #2150 #2115
- Create a `newrelic_nrql_alert_condition` and assign tags to it using `newrelic_entity_tags`
```
resource "newrelic_alert_policy" "foo" {
name = "foo"
} …
```
=> Set entity_guid after creating NRQL alert condition

newrelic/resource_newrelic_notifications_channel_test.go, newrelic/resource_newrelic_workflow.go, newrelic/resource_newrelic_workflow_test.go
Currently, if we delete a workflow or update the list of channels it uses, the provider will automatically delete the channels that are no longer used. This behaviour goes against users' IaC intuition because the deleted channels are **still defined** in the TF config and lead to non-empty TF plan.
This PR makes the behaviour more intuitive: if you delete workflow without removing its channel from your config, the channel remains until you remove it from your config as well. Same goes for workflow updates that remove some of the channels from workflow configuration.
Please see the added workflow resource tests
=> fix(workflows): stop silently removing channels on workflow updates/deletes

go.mod, go.sum, newrelic/resource_newrelic_workflow_test.go
Currently, if you try to create a disabled workflow it would be still created in an enabled state.
So it order to disable it, you have to run `terraform apply` one more time.
This PR fixes this problem and adds test to verify the fix.
Fixes #1964 
See the added integration tests
=> fix(workflows): fix a bug preventing creation of disabled workflows

newrelic/provider_test.go, newrelic/provider_unit_test.go, newrelic/resource_newrelic_alert_channel_test.go, newrelic/resource_newrelic_service_level_test.go, newrelic/resource_newrelic_synthetics_alert_condition_test.go, newrelic/resource_newrelic_synthetics_broken_links_monitor_test.go, newrelic/resource_newrelic_synthetics_cert_check_test.go, newrelic/resource_newrelic_synthetics_monitor_test.go, newrelic/resource_newrelic_synthetics_multilocation_alert_condition_integration_test.go, newrelic/resource_newrelic_synthetics_private_location_test.go, newrelic/resource_newrelic_synthetics_script_monitor_integration_test.go, newrelic/resource_newrelic_synthetics_secure_credential_test.go, newrelic/resource_newrelic_synthetics_step_monitor_test.go, newrelic/resource_newrelic_workflow_test.go, newrelic/resource_newrelic_workload_test.go
This PR also includes a new helper function 
- `generateNameForIntegrationTestResource()`: Facilitates standardizing the names of our test resources. This will help ensure we only delete dangling extraneous resources with names that start with "tf-test-". This helps avoid deleting any resources that might be cross-account, such as service levels, workflows, workloads, etc.
=> tests: add sweeper function for dangling workload resources, add test resource name helper

website/docs/r/synthetics_monitor.html.markdown, website/docs/r/synthetics_monitor_broken_links.html.markdown, website/docs/r/synthetics_monitor_cert_check.html.markdown, website/docs/r/synthetics_monitor_step.html.markdown, website/docs/r/synthetics_script_monitor.html.markdown
This PR removes the quotes around private location GUID references in Synthetics docs examples
Fixes #2168
=> docs(synthetics): remove unnecessary quotes around private location guid

newrelic/resource_newrelic_one_dashboard_json.go
Fix for #2175
This change adds a retry mechanism to the create/update functions in dashboard_json to check if the updatedAt returned by create/update matches the get calls value. This was added because there's a delay in the get call returning the correct value as there is an async behaviour on the API side (distributed systems are hard). 
Check #2175
=> fix(one_dashboard_json): added retry mechanism to create/update to handle updateAt changes

newrelic/structures_newrelic_one_dashboard.go, newrelic/structures_newrelic_one_dashboard_test.go
Possible fix for #2204. More details in ticket where the bug is coming from. 
I was unable to reproduce it locally because it looks like an API issue. Other dashboards remove the thresholds instead of setting a null value. The result is the same so the code now checks for nil value before resuming. 
As I was unable to reproduce, the code is a blind fix which needs to be confirmed with customer. 
=> fix(newrelic_one_dashboard): fix for null pointer when using thresholds in widget_billboard

newrelic/resource_newrelic_nrql_alert_condition.go, newrelic/resource_newrelic_nrql_alert_condition_test.go, website/docs/r/nrql_alert_condition.html.markdown
Updates the documentation for NRQL alert conditions to reflect up-coming updates to the maximum allowed threshold duration.
Previous maxima:
- **3600** seconds for baseline NRQL conditions
- **7200** seconds for static NRQL conditions
Updated maxima:
- **86_400** seconds for baseline NRQL conditions
- **86_400** seconds for static NRQL conditions
Fixes [NR-69147](https://issues.newrelic.com/browse/NR-69147)
Automated tests in `newrelic/resource_newrelic_nrql_alert_condition_test.go` (specifically `testAccNewRelicNrqlAlertConditionNerdGraphConfig`) will reflect this.
**Note:**
Given that the test is verifying validation of the field's defined maximum, it will pass in the feature's current state; …
=> docs(alert): Updated NRQL condition term duration max

website/docs/r/workflow.html.markdown
Automatic channel deletion has been disabled starting from v3.10.0, but the docs were not updated to reflect that
=> chore(workflows): remove outdated workflow documentation block

build/test.mk, go.mod, go.sum, newrelic/data_source_newrelic_notifications_destination_test.go, newrelic/resource_newrelic_alert_channel_test.go, newrelic/resource_newrelic_alert_condition_integration_test.go, newrelic/resource_newrelic_entity_tags_test.go, newrelic/resource_newrelic_nrql_alert_condition_test.go, newrelic/resource_newrelic_synthetics_script_monitor_integration_test.go, newrelic/resource_newrelic_workflow_test.go, newrelic/structures_newrelic_nrql_alert_condition.go
This PR contains an adjustment in newrelic-client-go for a breaking change made in the synthetics API for the `runtime` field and how they read the legacy runtime values.
Fixes: #2232 
Fixes: #2228
=> chore(deps): upgrade newrelic-client-go to v2.11.2

go.mod, go.sum, newrelic/resource_newrelic_workflow.go, newrelic/resource_newrelic_workflow_test.go, newrelic/structures_newrelic_workflow.go, newrelic/structures_newrelic_workflow_test.go
In future, this GUID can be used to assign tags to workflows though TF. 
For now though, this is now really feasible as indexing lag can reach several minutes.
I will not be updating documentation with tagging examples until it works quickly and reliably.
- And workflow should now have a computed GUID field that can be used in the script
=> feat(workflows): expose workflow entity guid

website/docs/r/synthetics_step_monitor.html.markdown
Noticed that a list of valid values for the `type` argument under the `steps` nested block were incorrectly placed under the `values` argument.  Have moved the list to be under the `type` argument. Also corrected a capitalised `O` to lowercase.
=> docs(synthetics_step_monitor): moved list of valid values to correct argument

newrelic/data_source_newrelic_alert_channel.go, newrelic/resource_newrelic_alert_channel.go, newrelic/resource_newrelic_alert_condition.go, newrelic/resource_newrelic_infra_alert_condition.go, newrelic/resource_newrelic_synthetics_alert_condition.go, newrelic/resource_newrelic_synthetics_multilocation_alert_condition.go, website/docs/d/alert_channel.html.markdown, website/docs/r/alert_channel.html.markdown, website/docs/r/alert_condition.html.markdown, website/docs/r/synthetics_alert_condition.html.markdown, website/docs/r/synthetics_multilocation_alert_condition.markdown
Deprecated Data Sources (EOL June 2023)
- `newrelic_alert_channel`
Deprecated Resources (EOL June 2023)
- `newrelic_alert_channel`
- `newrelic_alert_condition`
- `newrelic_infra_alert_condition`
- `newrelic_synthetics_alert_condition`
- `newrelic_synthetics_multilocation_alert_condition`
=> chore(alerts): deprecate legacy alert resources and data sources

newrelic/data_source_newrelic_entity.go, newrelic/data_source_newrelic_entity_integration_test.go, newrelic/data_source_newrelic_entity_test.go, newrelic/resource_newrelic_cloud_azure_link_account.go, newrelic/resource_newrelic_cloud_gcp_link_account.go, newrelic/resource_newrelic_synthetics_secure_credential_test.go
The PR replaces the use of `GetEntitySearchWithContext` with `GetEntitySearchByQueryWithContext`. This change provides us more precision with regard to querying for entity data. 
Under the hood, this means we're using `entitySearch.query` instead of `entitySearch.queryBuilder`. The `queryBuilder` was less precise due to loose comparisons in the query it constructs. 
👎  `queryBuilder` uses a fuzzy search with `LIKE` which is less precise. 🙁 
```
name LIKE 'app-name'
```
<br>
👍 `query` gives us more control because we can control the operators we use, such as `=` for better precision. 🙂 
```
name = 'app-name'
```
Note: This refactor should _not_ cause a breaking change.
=> refactor(entity): use GetEntitySearchByQuery instead of GetEntitySearch

website/docs/r/one_dashboard_json.html.markdown
This PR addresses [NR-97070](https://issues.newrelic.com/browse/NR-97070), documentation updates to be made to the `newrelic_one_dashboard_json` resource in the New Relic Terraform Registry, in order to add an additional example, to demonstrate the addition of thresholds, for instance, to the 'billboard' widget.
=> docs: add additional example to one_dashboard_json to demonstrate setting thresholds

newrelic/condition_helpers.go, newrelic/resource_newrelic_alert_condition.go, newrelic/resource_newrelic_infra_alert_condition.go, newrelic/resource_newrelic_synthetics_alert_condition.go, newrelic/resource_newrelic_synthetics_multilocation_alert_condition.go, newrelic/structures_newrelic_alert_condition.go, newrelic/structures_newrelic_infra_alert_condition.go, newrelic/structures_newrelic_synthetics_multilocation_alert_condition.go, newrelic/structures_newrelic_synthetics_multilocation_alert_condition_test.go, website/docs/r/alert_condition.html.markdown, website/docs/r/infra_alert_condition.html.markdown, website/docs/r/synthetics_alert_condition.html.markdown, website/docs/r/synthetics_multilocation_alert_condition.markdown
This PR generates and exposes the `entity_guid` for the following condition types:
- newrelic_alert_condition
- newrelic_infra_alert_condition
- newrelic_synthetics_alert_condition
- newrelic_synthetics_multilocation_alert_condition
This will allow users to add tags to these condition types via the terraform provider `newrelic_entity_tags` resource which requires an `entity_guid`:
https://issues.newrelic.com/browse/NR-98729
The resources changed in this PR are not well tested and these are legacy alert conditions which will are already somewhat obsolete and will be fully deprecated soon, so I opted not to write new tests for the changes included in this PR.
To manually test, run this PR locally and create each of the following resources and then attempt to add tags to …
=> feat(Alerts): Expose entity_guid for legacy alert conditions

website/docs/r/alert_channel.html.markdown
This PR addresses [NR-104181](https://issues.newrelic.com/browse/NR-104181), a fix to the issue mentioned below, comprising a correction to a Slack article used a reference in the resource `newrelic_alert_channel` that no longer exists, and addition of another reference.
Fixes 
#2313
=> docs: correct references to slack webhooks in newrelic_alert_channel

website/docs/guides/migration_guide_v3.html.markdown
This PR addresses and issue with our synthetics migration guide that was brought to our attention via our help channel. The docs referenced the new resource name when it needed to reference the _old_ resource name in the `terraform state rm` command.
=> docs(guide): update synthetics migration guide with correct resource reference to remove state

newrelic/resource_newrelic_nrql_alert_condition.go
- Addresses [NR-97003](https://issues.newrelic.com/browse/NR-97003)
- Adds a default 'violation_time_limit_seconds' of 259200 seconds to the `newrelic_nrql_alert_condition` resource
- Fixes issues identified with re-applying `terraform plan` after the first `terraform apply` is executed, because a null `violation_time_limit_seconds` is defaulted to 259200 seconds (3 days), which is expected behaviour, as specified [here](https://issues.newrelic.com/browse/NR-97003).
Fixes #2245
=> fix(newrelic_nrql_alert_condition): add default 'violation_time_limit_seconds'

website/docs/r/one_dashboard.html.markdown
This PR addresses the following via [NR-105334](https://issues.newrelic.com/browse/NR-105334) - 
- A documentation change as specified in this [Slack thread](https://newrelic.slack.com/archives/CP9Q30JDC/p1680705711944979?thread_ts=1680641253.804079&cid=CP9Q30JDC), about the need to let users know about the right use of `default_values` in the `variable` block in the resource `newrelic_one_dashboard`; especially, the use of `*` in `default_values`.
=> docs: add note on 'default_values' to one_dashboard

go.mod, go.sum
Update the dependency **newrelic-client-go** to the recently release v2.17.1.
=> chore(deps): update newrelic-client-go version to 2.17.1

newrelic/resource_newrelic_account_management_test.go, newrelic/structures_newrelic_one_dashboard.go
This PR addresses changes to be made to the Provider for [NR-106304](https://issues.newrelic.com/browse/NR-106304), an issue with the attribute `y_axis_left_min=0` not getting applied to the API request sent by client-go (since this attribute is omitted from the request if it is 0).
To fix this, a parallel change has been made to client-go to remove the "omitempty" condition from this attribute - and the changes in this PR ensure that in the event of absence of `y_axis_left_min` in the Terraform Config, the attribute is defaulted to 0 and sent to go-client, ensuring that the equivalent JSON attribute in go-client always receives a value from the calling Terraform Provider, thereby, needing no "omitempty" condition, which would help fix this issue.
Fixes 
- …
=> fix(one_dashboard): code changes to support y_axis_left_min=0

newrelic/resource_newrelic_synthetics_script_monitor.go, newrelic/resource_newrelic_synthetics_script_monitor_integration_test.go
Provider v3+ doesn't show the script argument differences for newrelic_synthetics_script_monitor resources #2241
Create a newrelic_synthetics_script_monitor.test resource with type SCRIPT_BROWSER
Modify its script using the New Relic UI
Run terraform plan and expect to see No changes. Your infrastructure matches the configuration.
I expect to receive the difference between the script saved as the code and the script saved in New Relic after its manual update, just as it was on the New Relic Terraform Provider v2.
=> fix(newrelic_synthetics_script_monitor): Populate script argument changes upon modifications.

newrelic/resource_newrelic_one_dashboard.go, newrelic/resource_newrelic_one_dashboard_test.go, newrelic/structures_newrelic_one_dashboard.go, website/docs/r/one_dashboard.html.markdown
[NEW PR] This PR addresses [NR-108075](https://issues.newrelic.com/browse/NR-108075), comprising of the following changes - 
- Addition of an argument `y_axis_left_zero` to the Schema of Line Widgets, which would be mapped to the attribute `Zero` in the API, that supports the option to fit the graph to scale, or render values in within the specified range (`y_axis_left_min` to `y_axis_left_max` ; or 0 to `y_axis_left_max` if `y_axis_left_min` is not specified).
- Associated code changes to conditionally send the attribute `Zero` to the API request based on the calling widget, and conditionally send the attribute `Min` only when `y_axis_left_zero` is `true`.
- Documentation change describing the attribute `y_axis_left_zero`.
Linked changes in dependencies
**newrelic-client-go** : …
=> feat(one_dashboard): addition of the attribute zero to widget_line

terraform-registry-manifest.json
The Terraform registry now requires a manifest file for enable release hooks for [publishing new releases to the registry](https://developer.hashicorp.com/terraform/registry/providers/publishing).
=> chore(release): add terraform registry manifest file for release hooks

go.mod, go.sum, newrelic/resource_newrelic_cloud_aws_govcloud_link_account.go, newrelic/resource_newrelic_cloud_azure_integrations.go, newrelic/resource_newrelic_cloud_azure_integrations_test.go, website/docs/r/cloud_azure_integrations.html.markdown
This PR addresses the addition of a new Azure Integration **azureMonitor** to the resource **newrelic_cloud_azure_integrations**.
#2254
=> feat(newrelic_cloud_azure_integrations): addition of the integration 'azureMonitor'

website/docs/d/service_level_alert_helper.html.markdown
via @NilVentosa (original PR : https://github.com/newrelic/terraform-provider-newrelic/pull/2360)
We changed the recommended alert for service level and the documentation of the service level alert helper data source has an example that became outdated.
No testing needed, only a documentation change
=> docs(service_level_alert_helper): update to documentation

newrelic/data_source_newrelic_account.go, newrelic/data_source_newrelic_account_test.go, website/docs/d/account.html.markdown
Right now there doesn't look to be a way to determine what `account_id` is being used by default with the provider. Right now `newrelic_api_access_key` requires specifying the `account_id` but there isn't an easy way to get this information without it being passed along correctly.
With this change, the `newrelic_account` resource would default to the `account_id` of the provider allowing easy access to this information in contexts that might not have easy access (nested modules).
- Create a data resource like the following: `data "newrelic_account" "acc" {}`
- Note that the …
=> feat(data/account): Allow reading the provider's `account_id`.

.gitignore
This PR addresses the addition of file formats that could contain credentials to the list of files to be ignored in **.gitignore** (belonging to directories with Terraform executables) to prevent credentials seeping into commits.
=> chore(cloud_integrations): update gitignore to ignore files with credentials

website/docs/r/notification_channel.html.markdown, website/docs/r/one_dashboard_json.html.markdown
This PR addresses [NR-108017](https://issues.newrelic.com/browse/NR-108017)
- Addition of an example to demonstrate creating a dashboard with multiple pages, using the resource **newrelic_one_dashboard_json**
- A tiny correction to a link in **newrelic_notification_channel**. Despite the presence of the right Slack sample URL in the following code snippet (with \<userId>/\<channelId>) 
https://github.com/newrelic/terraform-provider-newrelic/blob/77bab1b281a8ad5882956b39d5a1644e16d37028/website/docs/r/notification_channel.html.markdown?plain=1#L80
, the link is [seen to be rendered incorrect](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/notification_channel#SLACK) in the docs of **newrelic_notification_channel**. An escape character has been added to the …
=> docs(one_dashboard_json): addition of a multipage dashboard example and other corrections

website/docs/r/synthetics_script_monitor.html.markdown
This PR corrects `locations_public` and `location_private` arguments in the docs of the `newrelic_synthetics_script_monitor` resource
=> docs(script_monitor): corrections to details on private, public locations

newrelic/data_source_newrelic_obfuscation_expression.go, newrelic/data_source_newrelic_obfuscation_expression_test.go, newrelic/data_source_newrelic_test_grok_pattern.go, newrelic/data_source_newrelic_test_grok_pattern_test.go, newrelic/resource_newrelic_log_parsing_rule.go, newrelic/resource_newrelic_synthetics_private_location.go, newrelic/resource_newrelic_synthetics_secure_credential.go, newrelic/structures_newrelic_notifications_destination.go
This PR addresses refactoring of imports in resource/data source files in the `newrelic` directory of the provider which currently show lint warnings and corrections, upon running `make lint` locally. 
The corrections made by `make lint` have been rechecked using the **sort imports** feature in the GoLand IDE.
=> chore(imports): refactoring imports in files showing lint warnings

website/docs/r/one_dashboard_json.html.markdown
This PR adds documentation for the optional `account_id` argument to `newrelic_one_dashboard_json`. This parameter is already documented in the other two dashboard resources, I just copied the documentation from there.
=> docs: account_id param for newrelic_one_dashboard_json

examples/modules/cloud-integrations/aws/main.tf
This PR comprises changes made to the AWS integration example to adapt to the new AWS provider (5.0.0)
Two major changes - 
1. The block `s3_configuration` is now expected to be a nested block within the block `http_endpoint_configuration`, as per the updated documentation of the `aws_kinesis_firehose_delivery_stream` resource.
2. The attributes `buffer_size` and `buffer_interval` have been renamed to `buffering_size` and `buffering_interval`.
=> chore(aws): update to aws example in cloud integrations

.github/workflows/test.yml, newrelic/data_source_newrelic_cloud_account_test.go, newrelic/provider_test.go, newrelic/resource_newrelic_cloud_aws_integrations_test.go, newrelic/resource_newrelic_cloud_aws_link_account_test.go, newrelic/resource_newrelic_cloud_azure_integrations_test.go, newrelic/resource_newrelic_cloud_azure_link_account_test.go, newrelic/resource_newrelic_cloud_gcp_integrations_test.go, newrelic/resource_newrelic_cloud_gcp_link_account_test.go
The changes in this PR propose a solution to failing AWS/Azure/GCP integration tests which currently seem to happen because
- We have one set of credentials per linked account (AWS/Azure/GCP)
- If integration tests are run with the same account and a link/integration exists in the associated New Relic account, this would lead to failing tests, stating that the specified AWs/Azure/GCP account is already linked.
- In order to keep the main account we use for integration tests untouched by cloud integration tests, **tests relating to cloud providers have been modified to use an alternate subaccount**. This would ensure that any integrations set up with the original account (from outside these test cases to any manual feature exploration or testing) would not cause test failures, while the …
=> fix(cloud_tests): adds precheck to cloud tests to delink accounts before test run

newrelic/data_source_newrelic_entity.go, newrelic/data_source_newrelic_entity_integration_test.go
This PR addresses a fix to the `newrelic_entity` data source to
- filter the list of entities obtained from the API response based on the `account_id` specified in `provider{}`
- return the correct entity (associated with the `account_id` specified in `provider{}`)
and also adds test cases to validate these changes.
=> fix(newrelic_entity): filtering entites returned based on account_id

go.mod, go.sum, newrelic/data_source_newrelic_notifications_destination.go, newrelic/data_source_newrelic_notifications_destination_test.go, website/docs/d/notification_destination.html.markdown
Add support for creating destination data sources by name. Jira ticket link [here](https://issues.newrelic.com/browse/NR-88092).
- Create a destination with a specific name via New Relic notifications destination UI - in the Alerts tab
- Add this code to your terraform file with the name of the destination:
```
data "newrelic_notification_destination" "foo" {
name = <destination_name>
}
```
=> feat(data_source_newrelic_notifications_destination): Support name in destination data source

website/docs/guides/cloud_integrations_guide.html.markdown
Added missing `"` that causes syntax error.
N/A
N/A
=> docs(cloud_integrations_guide): Fix missing a quote at cloud_integrations_guide.html.markdown

newrelic/resource_newrelic_one_dashboard.go
Update to the `text` field in `widget_markdown` in `one_dashboard` to avoid the following error seen when the field `text` is not specified in the configuration, or is specified as an empty string.
```
╷
│ Error: query error; Text field in markdown configuration can't be null
│ 
│   with newrelic_one_dashboard.foo,
│   on newrelic.tf line 13, in resource "newrelic_one_dashboard" "foo":
│   13: resource "newrelic_one_dashboard" "foo" {
│ 
╵
```
=> fix(dashboards): update to 'text' field schema in widget_markdown

website/docs/guides/cloud_integrations_guide.html.markdown, website/docs/r/cloud_aws_integrations.html.markdown, website/docs/r/cloud_gcp_integrations.html.markdown
This PR addresses (the following changes made to the Cloud Providers Guide in the Terraform Provider's docs)
- recent feedback received on changing the supported services by an integration (AWS/Azure/GCP) from a **list** to a **table**, to make it slightly more readable
- few corrections made to the services supported (typos corrected and missing services added)
- rephrasing of a few sentences to support the changes listed above
=> docs(cloud_guides): beautification of cloud provider docs

website/docs/r/account_management.html.markdown, website/docs/r/notification_channel.html.markdown
- Fix typo in `notification_channel` docs.
- Add `id` as an exported attribute in the `account_management` resource. This fixes #2405
=> docs: updates and typo fixes to resource docs

newrelic/resource_newrelic_alert_condition.go, website/docs/r/alert_condition.html.markdown
Updates behavior of `violation_close_timer` field for `newrelic_alert_condition` to reflect the actual behavior. Validation looks for a number of hours between 1 and 720, and defaults to 72. This makes it consistent with the underlying API.
Fixes #2398 
- Creating an `newrelic_alert_condition` with type of `apm_jvm_metric` _or_ type of `apm_app_metric` with `condition_scope` set to `instance`
- Can create the condition with `violation_close_timer` set to any integer between 1 and 720
- Can create the condition _without_ `violation_close_timer` being set, and should default to 72
=> refactor(alerts): Amend validation for violation_close_timer

newrelic/resource_newrelic_synthetics_alert_condition.go, newrelic/resource_newrelic_synthetics_alert_condition_test.go
added error handling for monitor id when it is empty
https://issues.newrelic.com/browse/NR-140492
- Step 1
- Step 2
- etc
=> fix(synthetics): added error handling for monitor id when it is empty

website/docs/r/nrql_drop_rule.html.markdown
Documentation update to the docs of the `newrelic_nrql_drop_rule` resource to add information on the new CLI command to print droprules, `newrelic nrql droprules` (changes in the following PR that has been approved)
https://github.com/newrelic/newrelic-cli/pull/1476
=> docs: info on CLI command to print NRQL droprules

newrelic/data_source_newrelic_service_level_alert_helper.go, newrelic/data_source_newrelic_service_level_alert_helper_integration_test.go, website/docs/d/service_level_alert_helper.html.markdown
Service Levels can be set up using good or bad events. Until now the newrelic_service_level_alert_helper only considered good events. We added the boolean field `is_bad_events` as a optional field that defaults to false, as the most common case is good events.
Use the helper with bad events, for example using the updated example in the documentation
=> fix(service_level_alert_helper): Add bad events support

newrelic/resource_newrelic_alert_condition.go, website/docs/r/alert_condition.html.markdown
This PR fixes the following linked issue that was caused by a PR merged earlier (https://github.com/newrelic/terraform-provider-newrelic/pull/2402/files), which is now leading to an issue in which the attribute `violation_close_timer` is defaulting to 72 for all types of conditions, which is not expected, and is hence, leading to an API validation issue.
Since the approach towards conditionally varying this default value only in two cases (when `type` is `apm_jvm_metric` (OR) when `type` is `apm_app_metric` and `condition_scope` is `instance`) is not straightforward yet (this might need modifications directly in the create/update functions to set defaults only when these conditions are true, and proper state management upon read, to infer that 72 is the default value and is expected to …
=> fix(alert_condition): reverting default violation_close_timer 72 to prevent failures

newrelic/resource_newrelic_account_management.go
- A GTSE finds creating >10 accounts using this resource fails using the **context deadline exceeded** error.
- The cause of this has been verified to be the `Create` timeout added, so this has been removed, and its reference in `RetryContext` has been replaced with a direct specification of time in seconds.
- [GTSE](https://issues.newrelic.com/browse/NR-141995)
- [Ticket with all of the below observations elaborated](https://issues.newrelic.com/browse/NR-142169)
As per a recent GTSE received, when trying to create >10 accounts via the `newrelic_account_management` resource, a user sees the **context deadline exceeded** error, 
```
╷
│ Error: context deadline exceeded
│ 
│   with newrelic_account_management.foo[7],
│   on newrelic.tf line 13, in resource "newrelic_account_management" …
```
=> fix(account_management): refactored timeout to discard limit on create

go.mod, go.sum, newrelic/resource_newrelic_cloud_aws_link_account.go
As observed in a recent GTSE, the `newrelic_cloud_aws_link_account` resource usually works fine when the ARN it takes is hardcoded; however, when the ARN is generated by other AWS resources, such as in this sample configuration
https://github.com/newrelic/terraform-provider-newrelic/blob/refactor/update-aws-example/examples/modules/cloud-integrations/aws/main.tf#L71-L80
because AWS takes time to validate the ARN created, the API that is called when a `newrelic_cloud_aws_link_account` resource needs to be created returns a **failed** status for the first few times, suggesting the ARN is invalid (because AWS hasn't yet validated this ARN, as it has just been created via some other AWS resource). Because the method to create is wrapped in `RetryContext`, the API is called until it succeeds, …
=> fix(cloud_aws_link_account): refactored timeout to discard limit on create

CONTRIBUTING.md, newrelic/data_source_newrelic_entity.go, newrelic/data_source_newrelic_entity_integration_test.go, website/docs/d/entity.html.markdown
By default `newrelic_entity` data source returns an entity from the same account as provider's one. This change provides an option to override this behaviour by setting `account_id` attribute, which allows to fetch entity from the different account. For example, if provider has been configured with a parent account to deploy a new sub-account it still can fetch sub-account entity in the same configuration:
```hcl
provider "newrelic" {
account_id = "12345" # parent account
}
resource "newrelic_account_management" "default" { # sub-account
name   = "Acme Inc"
region = "us01"
}
data "newrelic_entity" "app" { # sub-account
account_id = newrelic_account_management.default.id # without explicit attribute setting this entity won't be found
name       = "my-app"
domain     = "APM"
type       = …
```
=> feat(newrelic_entity): fetch entity in different account

newrelic/resource_newrelic_workflow_test.go, newrelic/structures_newrelic_workflow.go
Workflow notification triggers is an ordered set that is currently represented in Terraform as an ordered list.
Our backend does not preserve the order of the given notification triggers.
As a result, if a workflow resource notification trigger does not match the order returned by NR API, Terraform reports a state drift when there isn't any.
This PR makes sure to keep the notification trigger order the same as in the existing state.
I could not use `DiffSuppressFunc` because notification triggers are a part of another property that itself is a set. Because Terraform uses a hash of the set item as its key, if notification triggers changes, TF thinks that the entire parent set item was removed and then the new one was added. So diff suppressing would only work for the entire parent set …
=> fix(workflows): ignore notification trigger order when comparing state

newrelic/resource_newrelic_synthetics_monitor.go, newrelic/resource_newrelic_synthetics_monitor_test.go, newrelic/structures_newrelic_synthetics_simple_browser_monitor.go
Update the simple monitor resource, `newrelic_synthetics_monitor`, with the `device emulation` options. 
Ref: [NR-90076](https://issues.newrelic.com/browse/NR-90076)
Use the `device orientation` and `device type` options as in this test configuration below. Verify in NR1 that your monitor was created and the device emulation options are set according to your specified configuration:
```tf
terraform {
required_providers {
newrelic = {
source = "newrelic/newrelic"
}
}
}
provider "newrelic" {
account_id = ...
api_key    = "NRAK-..."
region     = "US"
}
resource "newrelic_synthetics_monitor" "test_monitor" {
status           = "DISABLED"
name             = "test_monitor"
period           = "EVERY_MINUTE" …
```
=> feat(synthetics): Enable device emulation for simple browser synthetics

newrelic/data_source_newrelic_synthetics_private_location.go, website/docs/d/synthetics_private_location.html.markdown
This PR addresses the addition of the **key** of the private location to the list of attributes exported by the data source **newrelic_synthetics_private_location**.
depends on changes in **newrelic-client-go** https://github.com/newrelic/newrelic-client-go/pull/1051
=> fix(private_location): addition of key to attributes exported by the data source

newrelic/data_source_newrelic_synthetics_private_location.go, website/docs/d/synthetics_private_location.html.markdown
Reversal of change made via #2446, as this was merged after approval, but is being reverted as the PR depends on the next release of **newrelic-client-go** and this feature depends on that change to be out with the next release. 
Please see the linked PR for the newrelic-client-go changes mentioned.
=> chore(synthetics): revert change to export private location key

go.mod, go.sum, newrelic/resource_helpers_synthetics.go, newrelic/resource_newrelic_synthetics_monitor.go, newrelic/resource_newrelic_synthetics_monitor_test.go
Trying to fix `TestAccNewRelicSyntheticsSimpleBrowserMonitor` test.
=> fix(tests): Ignore device emulation attributes in Simple Monitor test

newrelic/structures_newrelic_synthetics_simple_browser_monitor.go
This PR removes setting default values for deviceEmulation fields on Browser monitors
Fixes #2464
Create a Browser type monitor without setting any values for deviceEmulation fields. 
The monitor should be created successfully.
=> fix: Remove setting default empty values for device emulation

newrelic/provider_integration_test.go
Update to the `TestAccNewRelicProvider_Region` integration test as there is a difference in the error message being returned currently ("Access denied.") as opposed to what it previously was ("403 response returned"), which is causing this test to fail.
=> fix(tests): change to expected error message in provider region integration test

newrelic/resource_newrelic_cloud_aws_integrations.go, newrelic/resource_newrelic_cloud_aws_link_account.go, newrelic/resource_newrelic_cloud_azure_integrations.go, newrelic/resource_newrelic_cloud_azure_link_account.go, newrelic/resource_newrelic_cloud_gcp_integrations.go, newrelic/resource_newrelic_cloud_gcp_link_account.go, website/docs/r/cloud_aws_integrations.html.markdown, website/docs/r/cloud_aws_link_account.html.markdown, website/docs/r/cloud_azure_integrations.html.markdown, website/docs/r/cloud_azure_link_account.html.markdown, website/docs/r/cloud_gcp_integrations.html.markdown, website/docs/r/cloud_gcp_link_account.html.markdown
This PR updates all attributes in AWS, Azure and GCP Cloud Link Account Resources to have `ForceNew: true` against all attributes (but not `name`) as the update function of these resources can only rename the linked accounts, given that these resources do not have an associated **update** mutation but instead, contain a **rename** mutation.
https://github.com/newrelic/terraform-provider-newrelic/blob/main/newrelic/resource_newrelic_cloud_aws_link_account.go#L165
https://github.com/newrelic/terraform-provider-newrelic/blob/main/newrelic/resource_newrelic_cloud_azure_link_account.go#L158
https://github.com/newrelic/terraform-provider-newrelic/blob/main/newrelic/resource_newrelic_cloud_gcp_link_account.go#L157
=> fix(cloud_link_account): addition of ForceNew to attributes other than name

newrelic/resource_newrelic_log_parsing_rule.go, newrelic/resource_newrelic_log_parsing_rule_test.go
It was identified via a recent support case that if a log parsing rule (that has already been applied) has its arguments updated other than name and a re-apply is performed, it fails with the following error.
```
│ Error: name is already in use by another rule
│
│   with newrelic_log_parsing_rule.foo,
│   on log-parsing-rule.tf line 1, in resource "newrelic_log_parsing_rule" "foo":
│    1: resource "newrelic_log_parsing_rule" "foo"{
```
The cause of this was traced to the following code snippet in the **Update** function of the resource.
https://github.com/newrelic/terraform-provider-newrelic/blob/95cba5c2f360dfec53392542708668a9e1684758/newrelic/resource_newrelic_log_parsing_rule.go#L174-L179
The method called in the above snippet is intended to find if log parsing rules already exist …
=> fix(log_parsing): fix to the update method to discard checking for existing rules with the name

newrelic/resource_helpers.go, newrelic/resource_newrelic_nrql_alert_condition.go, newrelic/resource_newrelic_synthetics_multilocation_alert_condition.go, website/docs/r/synthetics_multilocation_alert_condition.markdown
=> fix(multilocation_alert_condition): make violation_time_limit_seconds nearly consistent with its usage in nrql_alert_condition

website/docs/guides/upcoming_synthetics_muted_status_eol_guide.html.markdown
This PR changes the following in #2505 
- refactor indentation of the **description** block in the Muted Status EOL Guide
- shorten the title of the page to 78 characters (the earlier one was 100 characters long)
- an auxiliary change: change all **behaviour**s to **behavior**s
- an auxiliary change: add a H2 header with a one-line description at the beginning of the guide
After #2505 was merged to `main` and a release was performed, in v3.27.5 of the Terraform Provider, the guide looked like the following in the navbar. 
Either of the first two points above should be the cause of this, which is why they have been corrected in this PR.
=> docs(synthetics): refactor title and vocabulary of the muted status EOL guide

go.mod, go.sum, newrelic/resource_helpers_synthetics.go, newrelic/resource_newrelic_synthetics_cert_check_monitor.go, newrelic/resource_newrelic_synthetics_monitor.go, website/docs/r/synthetics_broken_links_monitor.html.markdown, website/docs/r/synthetics_cert_check_monitor.html.markdown, website/docs/r/synthetics_monitor.html.markdown, website/docs/r/synthetics_script_monitor.html.markdown, website/docs/r/synthetics_step_monitor.html.markdown
This PR addresses the following - 
- modifying the validate function of the status attribute of all Synthetic Monitor resources to a new function, `validateSyntheticMonitorStatus`. This function checks if the status is valid (similar to current behaviour) but also helps throw a warning if the status is `MUTED`. Examples below.
- making consistent the statement talking about the deprecation across docs, the warning message and the description of the `status` attribute in the code
Case 1: If one tries creating a monitor with status `MUTED` with these new changes
Case 2: If one tries modifying a monitor with status `MUTED` (with `MUTED` in the configuration)
However, this is shown only if the current status in the configuration is `MUTED` and not if we try changing it to `ENABLED` or …
=> chore(synthetics): refactor validate method to throw a deprecation warning with MUTED status

newrelic/resource_newrelic_nrql_alert_condition.go, website/docs/r/nrql_alert_condition.html.markdown
The documentation for NRQL alert conditions should be updated to reflect the updated allowed maximum for `aggregation_window` and the corresponding `slide-by` changes.
Fixes [(issue)](https://issues.newrelic.com/browse/NR-113483)
Ensure updated documentation makes sense and reflects the goals described in the ticket.
=> feat: Update docs for slow burn alerts

newrelic/data_source_newrelic_synthetics_secure_credential_test.go, newrelic/provider_test.go, newrelic/resource_newrelic_synthetics_monitor_test.go
It was recently noticed in an account internal to New Relic that Synthetic Monitors were failing to be created, which was traced to a breach of the limit of Synthetic Checks in the account. 
This took place owing to a large number of Synthetics entities (Private Locations, Monitors and Secure Credentials) which failed to be deleted owing to API errors/flakey API behaviour/interruptions caused to running integration tests. Such entities were accumulated over a large time frame and led to an enormous number of Synthetic Checks being triggered, eventually leading to the limit breach.
All of these redundant monitors/private locations/secure credentials have been deleted via the cleanup function written in this PR - the objective of these code changes, however, is to prevent such situations in …
=> chore: add cleanup function to delete redundant synthetic entities

newrelic/resource_newrelic_alert_condition.go, newrelic/resource_newrelic_infra_alert_condition.go, newrelic/resource_newrelic_synthetics_alert_condition.go
Marks the following resources as deprecated:
- newrelic_alert_condition
- newrelic_infra_alert_condition
- newrelic_synthetics_alert_condition
=> chore: Mark resources for deprecation

newrelic/resource_newrelic_api_access_key.go
If error `maximum retries reached: Key not found.` is returned for resource newrelic_api_access_key, assume the resource was deleted outside terraform and trigger a recreation of the resource.
Fixes #2519 
Without Patch:
- Step 1: Create a resource using Terraform of type `newrelic_api_access_key`
- Step 2: Delete the API key in the NewRelic web UI
- Step 3: Generate a Terraform plan (returns error): `maximum retries reached: Key not found.`
With PR:
- Step 1: Create a resource using Terraform of type `newrelic_api_access_key`
- Step 2: Delete the API key in the NewRelic web UI
- Step 3: …
=> Fix missing resource newrelic_api_access_key error

go.mod, go.sum, newrelic/provider.go, newrelic/resource_newrelic_monitor_downtime.go, newrelic/resource_newrelic_monitor_downtime_test.go, newrelic/structures_newrelic_monitor_downtime.go, website/docs/guides/upcoming_synthetics_muted_status_eol_guide.html.markdown, website/docs/r/monitor_downtime.html.markdown
This PR adds a resource `newrelic_monitor_downtime` to support the creation/updates to Monitor Downtimes in New Relic Synthetics.
For a quick gist of arguments supported by this to-be resource and sample configuration, please take a look at this README file.
https://github.com/newrelic/terraform-provider-newrelic/blob/feat/monitor-downtime-v2/website/docs/r/monitor_downtime.html.markdown
All test cases added are seen to pass, latest run 12:30 PDT - https://github.com/newrelic/terraform-provider-newrelic/actions/runs/7169338620/job/19524783432
=> feat(synthetics): addition of a resource for monitor downtimes

website/docs/guides/cloud_integrations_guide.html.markdown
Sub directories must be referenced using a special double-slash syntax:
https://developer.hashicorp.com/terraform/language/modules/sources#modules-in-package-sub-directories
Without double-slash syntax, dependabot will fail to run.
- Step 1
- Step 2
- etc
=> fix(docs): fix the URL in newrelic-aws-cloud-integrations module

website/docs/r/nrql_alert_condition.html.markdown, website/docs/r/one_dashboard.html.markdown
Signed-off-by: smcavallo <smcavallo@hotmail.com>
standardize account_id format in a few docs - the <> are non-standard
* `newrelic_nrql_alert_condition` - use 12345678 format similar to other documentation
* `one_dashboard` - use a friendlier format for the account IDs
in both cases the updated format is more clear.  this is a documentation only change
- Step 1
- Step 2
- etc
=> docs: standardize account_id format in a few docs

website/docs/r/alert_condition.html.markdown, website/docs/r/infra_alert_condition.html.markdown, website/docs/r/monitor_downtime.html.markdown, website/docs/r/synthetics_alert_condition.html.markdown
This PR aims at correcting 
- the note in legacy alert condition resources `newrelic_alert_condition`, `newrelic_infra_alert_condition` and `newrelic_synthetics_alert_condition` to make clear that these resources have been deprecated, as a deprecation message has been added to these three resources in the latest release, v3.28.0
- a few typographical errors made in the documentation of the `newrelic_monitor_downtime` resource
=> docs: fine tune legacy alert condition docs and monitor downtime docs

website/docs/guides/migration_guide_alert_conditions.html.markdown, website/docs/guides/migration_guide_v4.html.markdown
This PR adds a migration guide for Alert Conditions. Subtypes of Alert Conditions have been remove in favor of NRQL Alert Conditions.
It details examples of converting Alert and Synthetics Alert Conditions to NRQL Alert Conditions.
=> chore: alert conditions migration guide

newrelic/data_source_newrelic_service_level_alert_helper.go, newrelic/data_source_newrelic_service_level_alert_helper_integration_test.go, website/docs/d/service_level_alert_helper.html.markdown
Add `slow_burn` to the default alert types the helper provides help for.
Following the instructions in the readme for the data source and creating one for `slow_burn`, then verify the exported fields are correct. There are integration tests that do this, so those can be taken as an example.
=> feat(sl_alert_helper): add slow_burn service levels alert helper

build/tools.mk, newrelic/resource_newrelic_monitor_downtime.go, newrelic/structures_newrelic_monitor_downtime.go
This PR aims at fixing the following - 
- Issue noticed in https://github.com/newrelic/terraform-provider-newrelic/issues/2546; the `account_id` attribute of the resource would need to default to `account_id` in the `provider{}` block and not directly depend on `NEW_RELIC_ACCOUNT_ID` in the environment (given, `NEW_RELIC_ACCOUNT_ID` in the environment would be taken up by `account_id` in the `provider{}` block anyway, unless the `account_id` in the `provider{}` block is overridden, which is the expected outcome of this fix)
- A few fixes to error handling
=> chore(monitor_downtime): fixes to error handling, `account_id` default to that in `provider{}`

newrelic/data_source_newrelic_service_level_alert_helper.go, newrelic/data_source_newrelic_service_level_alert_helper_integration_test.go, newrelic/data_source_newrelic_service_level_alert_helper_unit_test.go, website/docs/d/service_level_alert_helper.html.markdown
There was a issue with the value returned for `evaluation_period`, it was returned in minutes and what the alert needs is seconds. Fixed that and updated documentation accordingly.
Use the example on the documentation to create a slow_burn or a fast_burn alert for a service level. All the code needed to do so is in the documentation
=> fix(service_level_alert_helper): fix value returned by evaluation_period

newrelic/data_source_newrelic_service_level_alert_helper.go, newrelic/data_source_newrelic_service_level_alert_helper_integration_test.go
Until now the UI and the provider were suggesting two different queries (with the same result). We decided to unify them for a more consistent experience.
=> fix(service_levels_alert_helper): Unify suggested queries with the UI

newrelic/resource_newrelic_one_dashboard.go, newrelic/structures_newrelic_one_dashboard.go
Via a recent support case, it was observed that if the `name` of a dashboard is updated, it wouldn't get updated (neither in the Terraform state, nor in the UI) while all other attributes would. 
Upon further investigation (lots of trial and error), it was identified that this was happening because two API calls went out  when Terraform would try updating configuration, which made obvious that the following section of the code was the culprit (as this comprises the **second** update call performed within the update function). 
This also made clear that the failure of the dashboard's name getting updated was seen only upon using the attribute `filter_current_dashboard` as control flow would only then enter the following section of code as the number of widgets to filter would be > 0. In …
=> fix(dashboards): fix to dashboard name update failure with filter_current_dashboard

newrelic/resource_newrelic_workload.go, newrelic/resource_newrelic_workload_test.go, website/docs/r/workload.html.markdown
Fixes #2591 
The following code should fail with a more clear message:
```hcl
resource "newrelic_workload" "workload" {
account_id  = var.account_id
name        = var.workload_name
description = var.description
scope_account_ids = var.scope_account_ids
entity_guids = var.entity_guids
entity_search_query {
query = ""
}
}
```
=> fix(workloads): Add validation on required fields

newrelic/data_source_newrelic_entity.go, website/docs/d/entity.html.markdown
[Jira](https://new-relic.atlassian.net/browse/NR-250438)
This PR proposes the addition of a new attribute `ignore_not_found` to the `newrelic_entity` data source in order to "ignore" not found errors if set `true` in the configuration, thereby stopping automated Terraform pipelines from halting if the entity is lost, which is useful in cases when the entity abruptly expires (see original usecase proposed by the customer in #2599).
The changes have been manually verified multifold. The test cases could not be updated because they fail with an `"id" not found error`, since the data source fetches no entity, which we try validating (without the expectation of an error being thrown, instead).
=> fix(entity): add argument `ignore_not_found` to ignore "not found" errors

newrelic/resource_helpers_synthetics.go, newrelic/resource_newrelic_synthetics_cert_check_monitor.go
This PR will add missing tags updated in the API for the `newrelic_synthetics_cert_check_monitor`
Fixes # ([issue](https://github.com/newrelic/terraform-provider-newrelic/issues/2510))
=> fix(synthetics): Add missing tags for newrelic_synthetics_cert_check_monitor

newrelic/resource_newrelic_cloud_gcp_integrations.go
This PR will fix error handling upon trying to run `terraform apply` (in Staging) with the resource `newrelic_cloud_gcp_integrations`.
Ticket : [NR-262901](https://new-relic.atlassian.net/browse/NR-262901)
[NR-262901]: https://new-relic.atlassian.net/browse/NR-262901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=>  fix(cloud-integrations): Add error handling in the resource newrelic_cloud_gcp_integrations

website/docs/r/cloud_aws_integrations.html.markdown, website/docs/r/cloud_azure_integrations.html.markdown, website/docs/r/cloud_gcp_integrations.html.markdown
This PR will enhance the documentation of all of the cloud integration resources by placing realistic values of metric polling intervals.
JIRA: [NR-262902](https://new-relic.atlassian.net/browse/NR-262902)
Metric polling interval values for the resources located in [newrelic-terraform](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs) docs has been updated referencing UI and [NR docs](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/get-started/introduction-aws-integrations/)
[NR-262902]: https://new-relic.atlassian.net/browse/NR-262902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs(cloud-integration): Fix documentation defects cloud integration resources

website/docs/r/synthetics_broken_links_monitor.html.markdown, website/docs/r/synthetics_cert_check_monitor.html.markdown, website/docs/r/synthetics_monitor.html.markdown, website/docs/r/synthetics_script_monitor.html.markdown, website/docs/r/synthetics_step_monitor.html.markdown
Ref: https://forum.newrelic.com/s/hubtopic/aAXPh0000001brxOAA/upcoming-endoflife-legacy-synthetics-runtimes-and-cpm
Adds documentation changes to add a EOL notice specifying the EOL of the legacy runtime of Synthetic Monitors, slated to be hit on October 22, 2024, and a link to resources.
Changes have been made just under the heading of the resource and later, under the definition of the arguments `runtime_type` and `runtime_type_version`; for instance -
=> docs: Update Synthetic Monitor resources with Legacy Runtime EOL Notice

newrelic/structures_newrelic_one_dashboard.go
Fixes #2675
(fixes a mishandled condition in #2672)
_____________
It has been reported via #2675 that (with the latest release of the provider, `v3.37.0`) running a `terraform plan` on configuration comprising of `widget_billboard` in the resource `newrelic_one_dashboard` is running into panic, and is hence, failing.
```hcl
resource "newrelic_one_dashboard" "exampledash" {
name        = "THRESHOLD TEST DASHBOARD"
permissions = "public_read_only"
page {
name = "New Relic Terraform Example"
widget_billboard {
title  = "Billboard Widget 1"
row    = 1
column = 1
width  = 4
height = 4
nrql_query {
query = "FROM Transaction SELECT rate(count(*), 1 minute)"
}
}
widget_billboard {
title  = "Billboard Widget 2"
row    = 5
column = 1
width  = 4
height = 3
nrql_query {
query = "FROM Transaction …
```
=> fix(dashboards): fix broken condition when thresholds are nil with billboard widgets

newrelic/resource_newrelic_workflow.go, newrelic/resource_newrelic_workflow_test.go, newrelic/structures_newrelic_workflow.go, newrelic/structures_newrelic_workflow_test.go, website/docs/r/workflow.html.markdown
Approved, but needs tiny changes - **please do not merge right now**.
Added a new field to destination block called update_original_message which for the moment only works for Slack channels.
The test is solely minimal to see that a workflow can be created with the field, as it requires a slack channel for the field to change.
=> feat(destinations): add `update_original_message` to destination configurations

website/docs/r/synthetics_broken_links_monitor.html.markdown, website/docs/r/synthetics_cert_check_monitor.html.markdown, website/docs/r/synthetics_monitor.html.markdown, website/docs/r/synthetics_script_monitor.html.markdown, website/docs/r/synthetics_step_monitor.html.markdown
=> docs(synthetics): fixed documentation for synthetic monitor resources

newrelic/resource_newrelic_entity_tags.go, newrelic/resource_newrelic_entity_tags_test.go, website/docs/r/entity_tags.html.markdown
Currently, In newrelic_entity_tags resource there is improper error handling when we try to update reserved tags(default tags which will be added when we create entity). Please check out the below JIRA ticket for more info.
JIRA Ticket: https://new-relic.atlassian.net/browse/NR-273648
Added a new function CreateErrorDiagnostics which will print all errors if present in the response called nerdgraph APIs. The CreateErrorDiagnostics function is called in resourceNewRelicEntityTagsCreate, resourceNewRelicEntityTagsUpdate, resourceNewRelicEntityTagsDelete.
=> fix(entity_tags): fixed improper error handling in `newrelic_entity_tags` resource

newrelic/resource_newrelic_notifications_destination.go, website/docs/d/notification_destination.html.markdown, website/docs/r/notification_destination.html.markdown
This adds support for the Service Now Certified App integration, as an alternative to the legacy Service Now integration.
Create a `newrelic_notification_destination` with `type = SERVICE_NOW_APP`.
=> feat: add support for SERVICE_NOW_APP

newrelic/resource_newrelic_notifications_channel.go, newrelic/resource_newrelic_notifications_destination.go
The NG timeout for our schemas include a 15 seconds timeout, which is not exhibited by our TF schemas.
This change will allow users to create longer mutations and avoid retries when it's unneeded
=> feat(notifications): increase timeout on mutations

newrelic/resource_newrelic_notifications_channel.go, newrelic/resource_newrelic_workflow.go, website/docs/r/notification_channel.html.markdown
Added SNow channel type. Follow up to adding SNow destination type [here](https://github.com/newrelic/terraform-provider-newrelic/pull/2693) 
=> fix(notifications): Added servicenow app channel option to valid notification channels list

go.mod, go.sum, newrelic/resource_newrelic_synthetics_monitor_test.go, newrelic/structures_newrelic_synthetics_simple_browser_monitor.go, newrelic/structures_newrelic_synthetics_simple_monitor.go
Added the capability to delete all custom headers for simple/browser synthetic monitors.
Jira: [NR-296277](https://new-relic.atlassian.net/browse/NR-296277)
- passing an empty slice  in custom header for create/update of synthetic monitor when no custom header is provided in the TF config file
[NR-296277]: https://new-relic.atlassian.net/browse/NR-296277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Add creation/updation of synthetic(simple/browser) monitor with empty custom headers

go.mod, go.sum, newrelic/resource_newrelic_agent_application_browser.go
Currently, if user send the value for `cookiesEnabled` as false for browser agent, that is currently being ignored, and the default value of true is being used. Fixed it by changing the boolean field to a pointer. 
- Step 1
- Step 2
- etc
=> fix(browseragent): changing cookiesEnabled field to pointer type

go.mod, go.sum, newrelic/structures_newrelic_one_dashboard.go
Currently, if user send the value for legend_enabled as false while creating dashboards, that is currently being ignored, and the default value of true is being used. Fixed it by changing the boolean field to a pointer.
refere to old pr for comments : https://github.com/newrelic/terraform-provider-newrelic/pull/2737 (closed due to branch naming mistake)
Fixes https://github.com/newrelic/terraform-provider-newrelic/issues/2736
- Step 1
- Step 2
- etc
=> fix(dashboard):  changing legend_enabled/legend field to pointer type

newrelic/structures_newrelic_synthetics_script_api_monitor.go, newrelic/structures_newrelic_synthetics_script_browser_monitor.go, newrelic/structures_newrelic_synthetics_simple_browser_monitor.go
The "update" functions of resources which deal in Simple Browser, Scripted Browser and Scripted API monitors in our Terraform Provider do not seem to default to an empty runtime, if no runtime attributes are specified in the configuration, or if they are empty strings. This would cause customers to not be able to downgrade monitors from the new runtime to the legacy runtime (though this is not encouraged, given the context around the Legacy Runtime EOL, customers should be able to do this until the final EOL for new and existing monitors on October 22, 2024; hence this change).
This PR includes a tiny change for update functions to default `runtimeType` and `runtimeTypeVersion` to default to empty strings, if runtime attributes are absent in the configuration, or if they have empty …
=> fix(synthetics): allow new -> legacy runtime downgrade until Oct 22 for simple browser, scripted monitors

newrelic/data_source_newrelic_key_transaction.go, website/docs/d/key_transaction.html.markdown
Updated the key transaction data source to migrate from lagacy Rest Api to NerdGraph Api.
Added some featured as part of the update
* Added additional capability of filtering of the key transaction on the basis of guid id multiple key transaction have same same. 
* add newrelic_key_transaction data block in Config file
* perform terraform apply
* key transaction details should be visible in the state file
=> fix(key transaction): Migrate key transaction data source from Rest api to NerdGraph

go.mod, go.sum, newrelic/resource_newrelic_cloud_azure_link_account.go, newrelic/resource_newrelic_cloud_azure_link_account_test.go, website/docs/r/cloud_azure_link_account.html.markdown
earlier newrelic_azure_link_account resource was providing only renaming of the link account feature. This PR include changes which will allow users to update all the fields for the resource.
These changes are done as a part of this[ help request.](https://newrelic.slack.com/archives/CP9Q30JDC/p1725499613506239)
jira ticket: https://new-relic.atlassian.net/browse/NR-323227
=> feat(azure_link_account): adds ability to update credentials of azure link accounts

examples/modules/cloud-integrations/aws/main.tf, examples/modules/cloud-integrations/aws/variables.tf, website/docs/guides/cloud_integrations_guide.html.markdown
Adds support for inclusive and exclusive metric filters
Fixes #2765
Add the module using my fork and see what happens
```terraform
module "newrelic" {
source = "github.com/sjauld/terraform-provider-newrelic//examples/modules/cloud-integrations/aws"
newrelic_account_id     = "<your account ID>"
newrelic_account_region = "<your region>"
name                    = "a prefix for your resources"
include_metric_filters = {
"AWS/EC2"    = []
"AWS/ECS"    = []
"AWS/Lambda" = []
"AWS/RDS"    = []
}
}
```
=> Add support for metric filters

go.mod, go.sum, newrelic/helpers.go, newrelic/resource_newrelic_cloud_azure_integrations.go, newrelic/resource_newrelic_cloud_azure_integrations_test.go
- Refactored code to reduce code redundancy of schema attributes in the schema of the Azure Integrations Terraform
resource.
- Created wrapper function to replace repeated usages of d.GetOk()
- Create the Azure Link Account
- Update the Azure Link Account
- Destroy the Azure Link Account
=> refactor(azure-integration-resource): code refactor of azure integration resource to improve code readability

go.mod, go.sum, newrelic/resource_newrelic_alert_muting_rule.go, newrelic/resource_newrelic_alert_muting_rule_test.go, newrelic/structures_newrelic_alert_muting_rule.go, website/docs/r/alert_muting_rule.html.markdown
- The addition of the `action_on_muting_rule_window_ended` attribute in the `newrelic_alert_muting_rule` Terraform resource aims to enhance the functionality of muting rules within New Relic's alerting system using terraform.
- The attribute `action_on_muting_rule_window_ended` is added to MutingRule Schema Resource and handler methods.
- Link to GitHub Issue: https://github.com/newrelic/terraform-provider-newrelic/issues/2774
=> feat(alert_muting_rule): Add `action_on_muting_rule_window_ended` attribute in `newrelic_alert_muting_rule` Terraform Resource

examples/bulk_users_import/go.mod, examples/bulk_users_import/go.sum, go.mod, go.sum, website/docs/r/alert_muting_rule.html.markdown
=> chore: adding reference to new client-go version v2.52.0

examples/modules/cloud-integrations/aws-govcloud/main.tf, examples/modules/cloud-integrations/aws-govcloud/providers.tf, examples/modules/cloud-integrations/aws-govcloud/variables.tf
=> chore(aws_govcloud): create a AWS Govcloud replica module of AWS

newrelic/resource_newrelic_cloud_aws_govcloud_link_account.go, newrelic/structures_newrelic_cloud_aws_govcloud_link_account.go, website/docs/r/cloud_aws_govcloud_link_account.html.markdown
It has recently been identified by the Cloud Team at New Relic that for the AWS GovCloud integration to work, usage of the `awsGovcloud` type in the `cloudLinkAccount` mutation is no longer supported since it uses an outdated mechanism for authorization (that is based on `access_key_id` and `secret_access_key` which is no longer supported). Instead, the creation of a link would properly work if the AWS GovCloud integration is "also" done using the `aws` type in the `cloudLinkAccount` mutation, since this would use the `arn` of the AWS role for authorization, which is the supported mechanism today.
Given that this resource has not had any tangible customer usage, the change to include `arn` "instead of" (and not "alongside" the old parameters) has been made in this PR in order to allow for …
=> feat(aws_govcloud): revamp of the resource to support ARN based authentication

examples/modules/cloud-integrations/aws-govcloud/README.md, examples/modules/cloud-integrations/aws-govcloud/main.tf, examples/modules/cloud-integrations/aws-govcloud/providers.tf, examples/modules/cloud-integrations/aws-govcloud/variables.tf
Original Author: @vivek-tech-exp (#2807, #2811)
With the AWS GovCloud Link Account resource that was recently fixed with v3.56.0 of the New Relic Terraform Provider (#2809), as a follow up, the objective of this PR is to convert the AWS GovCloud module into a working module that can help customers set up AWS GovCloud infrastructure needed to exchange metrics with New Relic, and leverage `newrelic_cloud_aws_govcloud_link_account` and `newrelic_cloud_aws_govcloud_integrations` to set up AWS GovCloud monitoring.
=> fix(aws_govcloud): define a working AWS GovCloud module for cloud integration prerequisites

go.mod, go.sum, newrelic/helpers.go, newrelic/resource_helpers_application_settings.go, newrelic/resource_newrelic_application_settings.go, newrelic/resource_newrelic_application_settings_test.go, newrelic/structures_newrelic_application_settings.go, testing/newrelic.tf, website/docs/r/application_settings.html.markdown
**_Right now, this TF resource only supports a subset of the application settings available on the APM UI .
This PR concludes the changes required for `newrelic_application_settings` resource to add the missing set of configuration settings that are available on the UI_**
```hcl
resource "newrelic_application_settings" "app" {
guid                   = "Mxxxxxxxxxxxxxxxxxxxx"
name                   = "XXXXXXXXXXXXXX"
app_apdex_threshold    = "0.8"
use_server_side_config = true
transaction_tracer {
explain_query_plans {
query_plan_threshold_type  = "VALUE"
query_plan_threshold_value = "0.8"
}
sql {
record_sql = "OBFUSCATED"
}
stack_trace_threshold_value = "0.3"
transaction_threshold_type  = "VALUE"
transaction_threshold_value = "0.9"
}
error_collector {
expected_error_classes = …
```
=> feat(application_settings) : Revamp application apm settings to sync with the latest features/functionalities in apm settings in ui

go.mod, go.sum, newrelic/resource_newrelic_nrql_alert_condition.go, newrelic/resource_newrelic_nrql_alert_condition_test.go, newrelic/structures_newrelic_nrql_alert_condition.go, newrelic/structures_newrelic_nrql_alert_condition_test.go, website/docs/r/nrql_alert_condition.html.markdown
- Adds support for `signal_seasonality` for baseline NRQL conditions
- See ticket: https://new-relic.atlassian.net/browse/NR-368788
Related to [Go Client PR](https://github.com/newrelic/newrelic-client-go/pull/1291)
- Try creating a `newrelic_nrql_alert_condition` of type `baseline`.
- Ensure you can set `signal_seasonality` successfully.
- Try creating a `newrelic_nrql_alert_condition` of type `static` without `signal_seasonality`.
E.g.
```
resource "newrelic_nrql_alert_condition" "baseline_condition" {
account_id                   = 400304
policy_id                    = 1514915
type …
```
=> feat(alerts): adds support for signal_seasonality for NRQL baseline conditions

go.mod, go.sum, newrelic/resource_newrelic_one_dashboard.go, newrelic/resource_newrelic_one_dashboard_test.go, newrelic/structures_newrelic_one_dashboard.go, website/docs/guides/newrelic_one_dashboard_multi_account_guide.html.markdown, website/docs/r/one_dashboard.html.markdown
TBD
Replaces #2912
```hcl
resource "newrelic_one_dashboard" "my_dashboard" {
name        = "Test Dashboard 2807"
permissions = "public_read_only"
page {
name = "Test Dashboard 2807"
widget_table {
title  = "List of Transactions"
row    = 1
column = 4
width  = 6
height = 3
nrql_query {
query      = "SELECT average(duration), max(duration), min(duration) FROM Transaction FACET name SINCE 1 day ago"
}
}
}
}
```
=> feat(dashboards): add support for multi account queries in widgets

website/docs/guides/aws_auto_discovery_integration_with_terraform.html.markdown
- The documentation for Auto-Discovery misplaced aws_account_id with provider_account_id. Hence corrected that out in the docuemtentation
- Corrected documentation
- Backward Compatible, Documentation Update
- Step 1
- Step 2
- etc
=> feat(cloud): corrected Documentation for Auto-Discovery

go.mod, go.sum, newrelic/resource_newrelic_nrql_drop_rule.go, newrelic/resource_newrelic_nrql_drop_rule_test.go, website/docs/guides/drop_rules_eol_guide.html.markdown, website/docs/r/nrql_drop_rule.html.markdown, website/docs/r/pipeline_cloud_rule.html.markdown
This PR implements comprehensive support for the upcoming NRQL Drop Rules end-of-life (EOL) on January 7, 2026, including deprecation warnings, migration utilities, and the new Pipeline Cloud Rules resource to replace the deprecated functionality.
New Relic has announced the EOL of the Drop Rules API effective January 7, 2026. Customers using the `newrelic_nrql_drop_rule` resource need a clear migration path to the new Pipeline Cloud Rules functionality while maintaining their existing infrastructure management workflows.
- **Deprecated `newrelic_nrql_drop_rule` resource** with clear deprecation messages and EOL timeline
- **Added new `newrelic_pipeline_cloud_rule` resource** as the replacement for drop rules functionality
- **Enhanced migration support** with …
=> feat(nrqldroprule): fully deprecate resource, add field to map to PCRs, update EOL guides

newrelic/resource_newrelic_one_dashboard.go, newrelic/resource_newrelic_one_dashboard_test.go, newrelic/structures_newrelic_one_dashboard.go, website/docs/r/one_dashboard.html.markdown
This PR aims to add a plan-time validation for the `account_ids` attribute inside the `nrql_query{}` for `variable{}` block. It ensures that `terraform plan` will fail if the attribute is either omitted or set to an empty list (`[]`).
=> fix(newrelic_one_dashboard): add plan-time validation for `account_ids` in `variable{}` block

go.mod, main.go, tools/go.mod
As suggested in #2769, this PR aims at upgrading the version tag in all `terraform-provider-newrelic/v*` references in the codebase, to ensure that the tags we're currently releasing versions with (i.e. `v3.*.*`) matches the semantic version inside these references, without which the versions are not being listed currently in go.dev.
=> fix(deps): upgrade v2 to v3 to allow go.dev listing
