newrelic/terraform-provider-newrelic

CHANGELOG.md

This updates the changelog for the 0.1.2 release.

Update changelog for 0.1.2 release

---

CHANGELOG.md

This updates the changelog for the 1.0.1 release.

Update changelog for 1.0.1 release

---

newrelic/resource_newrelic_dashboard.go
newrelic/resource_newrelic_dashboard_test.go

Addresses #40 
Will require PR in the Go SDK (https://github.com/paultyng/go-newrelic/pull/24) to be merged before this can be used

Add support for dashboard filters

---

newrelic/resource_newrelic_nrql_alert_condition.go
website/docs/r/nrql_alert_condition.html.markdown

Acceptable values range from 2-120 (inclusive).

fix nrql alert condition duration

---

newrelic/resource_newrelic_infra_alert_condition.go
newrelic/resource_newrelic_infra_alert_condition_test.go

Fixes https://github.com/terraform-providers/terraform-provider-newrelic/issues/99

support infrastructure alert condition runbook url

---

newrelic/helpers_test.go
newrelic/resource_newrelic_alert_condition.go
newrelic/resource_newrelic_alert_condition_test.go
newrelic/resource_newrelic_infra_alert_condition.go
newrelic/resource_newrelic_infra_alert_condition_test.go
newrelic/resource_newrelic_nrql_alert_condition.go
newrelic/resource_newrelic_nrql_alert_condition_test.go
newrelic/resource_newrelic_synthetics_alert_condition.go
newrelic/resource_newrelic_synthetics_alert_condition_test.go

Check if alert policy exists before retrieving

---

.travis.yml
newrelic/data_source_newrelic_alert_channel.go
newrelic/data_source_newrelic_alert_policy.go
newrelic/data_source_newrelic_application.go
newrelic/data_source_newrelic_key_transaction.go
newrelic/data_source_newrelic_synthetics_monitor.go
newrelic/resource_newrelic_synthetics_monitor.go

Linter fixes and CI config updates.

Linter and CI updates 

---

newrelic/resource_newrelic_alert_condition.go

Fix for https://github.com/terraform-providers/terraform-provider-newrelic/issues/137

newrelic_alert_condition - use TypeSet for entities list

---

CHANGELOG.md
README.md

chore: update CHANGELOG and README

---

newrelic/resource_newrelic_alert_policy.go
newrelic/resource_newrelic_alert_policy_test.go
website/docs/r/alert_policy.html.markdown

fix: align alert policy validation with NR's API validation

---

newrelic/resource_newrelic_dashboard_test.go

This PR adds a test to check if a dashboard can be recreated after manually deleting the resource.  The functionality has been fixed upstream in paultyng/go-newrelic#73 (released in [v4.7.0](https://github.com/paultyng/go-newrelic/releases/tag/v4.7.0)).

Acceptance test for manually deleted resource

---

website/docs/r/infra_alert_condition.html.markdown

see [New Relic Infra Alert Condition Resource](https://github.com/terraform-providers/terraform-provider-newrelic/blob/master/newrelic/resource_newrelic_nrql_alert_condition.go#L33-L35)

update alert infra condition docs to include runbook url argument

---

newrelic/config_test.go
newrelic/helpers_test.go
newrelic/resource_newrelic_dashboard.go
newrelic/structure_test.go
newrelic/validation.go
newrelic/validation_test.go

Add tests around a few sections that are not specific resources.

Additional test coverage

---

website/docs/r/dashboard.html.markdown

Quick fix for the formatting in the `newrelic_dashboard` resource docs:
https://www.terraform.io/docs/providers/newrelic/r/dashboard.html#nested-filter-block

docs: fix formatting in dashboard docs

---

newrelic/data_source_newrelic_application.go
newrelic/data_source_newrelic_application_test.go

Resolves #217.
This PR refactors the acceptance tests for the application data source.

Refactor application data source tests

---

newrelic/resource_newrelic_synthetics_monitor_script_test.go

Resolves: #223 
IMPROVEMENTS:
- update acceptance tests for `newrelic_synthetics_monitor_script`
- include `import` test for `newrelic_synthetics_monitor_script`

feat: update newrelic_synthetics_monitor_script acceptance tests

---

newrelic/resource_newrelic_synthetics_alert_condition.go
newrelic/resource_newrelic_synthetics_alert_condition_test.go

Resolves: #221 
IMPROVEMENTS:
- update acceptance tests for `newrelic_synthetics_alert_condition`
- include `import` test for `newrelic_synthetics_alert_condition`

feat: update newrelic_synthetics_alert_condition acceptance tests

---

website/docs/d/alert_channel.html.markdown
website/docs/d/alert_policy.html.markdown
website/docs/d/application.html.markdown
website/docs/d/key_transaction.html.markdown
website/docs/d/plugin.html.markdown
website/docs/d/plugin_component.html.markdown
website/docs/d/synthetics_monitor.html.markdown
website/docs/r/alert_channel.html.markdown
website/docs/r/alert_condition.html.markdown
website/docs/r/alert_policy.html.markdown
website/docs/r/alert_policy_channel.html.markdown
website/docs/r/dashboard.html.markdown
website/docs/r/infra_alert_condition.html.markdown
website/docs/r/insights_event.html.markdown
website/docs/r/nrql_alert_condition.html.markdown
website/docs/r/plugins_alert_condition.html.markdown
website/docs/r/synthetics_alert_condition.html.markdown
website/docs/r/synthetics_monitor.html.markdown
website/docs/r/synthetics_monitor_script.html.markdown

This PR updates the website documentation for clarity and consistency.

docs: update for clarity and consistency

---

website/docs/r/insights_event.html.markdown
website/newrelic.erb

This PR adds some missing resources and data sources to the documentation sidebar.

docs: add missing resources and data source to sidebar

---

newrelic/resource_newrelic_synthetics_monitor.go
newrelic/resource_newrelic_synthetics_monitor_test.go
website/docs/r/synthetics_monitor.html.markdown

Resolves: #222 
IMPROVEMENTS:
- update `newrelic_synthetics_monitor` acceptance tests to use our design pattern
- add additional test coverage for `newrelic_synthetics_monitor`
- add `import` test for `newrelic_synthetics_monitor`

feat: add ability to import update newrelic_synthetics_monitor, update acceptance tests

---

newrelic/resource_newrelic_dashboard.go
website/docs/r/dashboard.html.markdown

fix(dashboards): application_breakdown is a valid visualization

---

go.mod
go.sum
newrelic/provider.go
vendor/github.com/newrelic/newrelic-client-go/internal/version/version.go
vendor/github.com/newrelic/newrelic-client-go/newrelic/newrelic.go
vendor/github.com/newrelic/newrelic-client-go/pkg/entities/entities.go
vendor/github.com/newrelic/newrelic-client-go/pkg/entities/entities_types.go
vendor/github.com/newrelic/newrelic-client-go/pkg/entities/tags.go
vendor/modules.txt

Updating newrelic-client-go to v0.5.0.

chore(deps): update module newrelic/newrelic-client-go to v0.5.0

---

go.mod
go.sum
newrelic/data_source_newrelic_alert_policy.go
newrelic/resource_newrelic_alert_policy.go
newrelic/structures_newrelic_alert_policy.go
vendor/github.com/newrelic/newrelic-client-go/internal/version/version.go
vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/alerts_types.go
vendor/modules.txt

Resolves #330.
This PR also introduces a small performance gain by [passing the provided policy name to the `ListPolicies` method](https://github.com/terraform-providers/terraform-provider-newrelic/pull/341/files#diff-aeec28b1d8b1291479da7e18996858e1R42-R48).

refactor: rebase newrelic_alert_policy resource on newrelic-client-go

---

CHANGELOG.md

chore(release): prep for v1.12.1 release

---

newrelic/resource_newrelic_nrql_alert_condition.go
newrelic/structures_newrelic_nrql_alert_condition.go
newrelic/structures_newrelic_nrql_alert_condition_test.go

refactor(alerts): update resource_newrelic_nrql_alert_condition to use new client

---

newrelic/data_source_newrelic_application.go

refactor: rebase applications on newrelic-client-go

---

newrelic/data_source_newrelic_key_transaction.go
newrelic/data_source_newrelic_key_transaction_test.go

refactor: rebase key txns on newrelic-client-go

---

go.mod
go.sum
newrelic/resource_newrelic_synthetics_alert_condition.go
vendor/github.com/newrelic/newrelic-client-go/internal/version/version.go
vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/synthetics_conditions.go
vendor/modules.txt

refactor: rebase synthetics conditions on newrelic-client-go

---

newrelic/resource_newrelic_dashboard.go
newrelic/structures_newrelic_dashboard.go

refactor: rebase newrelic_dashboard resource on newrelic-client-go

---

newrelic/data_source_newrelic_plugin.go
newrelic/data_source_newrelic_plugin_component.go
newrelic/resource_newrelic_plugins_alert_condition.go
newrelic/structures_newrelic_plugins_alert_condition.go
newrelic/structures_newrelic_plugins_alert_condition_test.go

Resolves #333 .
This PR also introduces a couple of small performance gains by [passing the provided plugin GUID to the `ListPlugins` method](https://github.com/terraform-providers/terraform-provider-newrelic/pull/344/files#diff-b71ebd84dacb14aa656c9ddcbd4d367aR34-R40), and [passing the provided plugin ID and component name to the `ListComponents` method](https://github.com/terraform-providers/terraform-provider-newrelic/pull/344/files#diff-7e14da499ae44802482a96dbca38162fR42-R50).

refactor: rebase plugins resources on newrelic-client-go

---

newrelic/data_source_newrelic_synthetics_monitor_test.go
newrelic/helpers_test.go
newrelic/resource_newrelic_alert_policy_channel.go
newrelic/resource_newrelic_alert_policy_channel_test.go

refactor: rebase alerts policy channels on newrelic-client-go

---

newrelic/provider_test.go

refactor(tests): cleanup old applications generated by acceptance test suite

---

go.mod
go.sum
newrelic/structures_newrelic_alert_channel.go
vendor/github.com/newrelic/newrelic-client-go/internal/http/client.go
vendor/github.com/newrelic/newrelic-client-go/internal/http/graphql_client.go
vendor/github.com/newrelic/newrelic-client-go/internal/logging/structured_logger.go
vendor/github.com/newrelic/newrelic-client-go/internal/version/version.go
vendor/github.com/newrelic/newrelic-client-go/newrelic/newrelic.go
vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/alerts.go
vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/alerts_types.go
vendor/github.com/newrelic/newrelic-client-go/pkg/config/config.go
vendor/github.com/newrelic/newrelic-client-go/pkg/entities/entities.go
vendor/github.com/newrelic/newrelic-client-go/pkg/synthetics/synthetics.go
vendor/modules.txt

fix(alert_channels): handle more complex JSON structures in payload or headers

---

website/docs/guides/getting_started.html.markdown

resolves: #269 
Without this change, users could be left wondering why their resource keeps
getting marked as changed, though no change has been made out of band.  Here we
make a note about the reason a change gets marked, and include an example to
avoid this behavior.

docs: Make note about ignoring secrets

---

website/docs/index.html.markdown

Here we ensure there is enough information to point inquisitive users to
community resources, and to let folks know about our open source support.

docs: Make a note about community resources and support

---

newrelic/resource_newrelic_infra_alert_condition.go
newrelic/structures_newrelic_infra_alert_condition.go
newrelic/structures_newrelic_infra_alert_condition_test.go

feat(infra_alert_condition): add violation_close_timer to newrelic_infra_alert_condition resource

---

newrelic/resource_newrelic_alert_channel.go
newrelic/resource_newrelic_alert_channel_test.go
newrelic/structures_newrelic_alert_channel.go
website/docs/r/alert_channel.html.markdown

fix(alert_channel): validate payload also has payload_type specified

---

newrelic/provider.go
newrelic/resource_newrelic_synthetics_label.go
newrelic/resource_newrelic_synthetics_label_test.go
vendor/github.com/newrelic/newrelic-client-go/internal/http/client.go
vendor/github.com/newrelic/newrelic-client-go/internal/http/test_helpers.go
vendor/github.com/newrelic/newrelic-client-go/internal/version/version.go
vendor/github.com/newrelic/newrelic-client-go/pkg/config/config.go
vendor/github.com/newrelic/newrelic-client-go/pkg/synthetics/monitor_labels.go
vendor/github.com/newrelic/newrelic-client-go/pkg/synthetics/monitor_scripts.go
vendor/github.com/newrelic/newrelic-client-go/pkg/synthetics/monitors.go
vendor/github.com/newrelic/newrelic-client-go/pkg/synthetics/secure_credentials.go
vendor/github.com/newrelic/newrelic-client-go/pkg/synthetics/synthetics.go
vendor/github.com/newrelic/newrelic-client-go/pkg/synthetics/synthetics_types.go
vendor/modules.txt
website/docs/r/synthetics_label.html.markdown
website/newrelic.erb

Resolves #164.
This PR adds a new synthetics labels resource, following existing patterns.

feat(synthetics): add labels resource

---

CHANGELOG.md
go.sum

Preparing the v1.14.0 release.

chore: prepare v1.14.0 release

---

newrelic/provider.go
newrelic/resource_newrelic_app_label.go
newrelic/resource_newrelic_application_label.go
newrelic/resource_newrelic_application_label_test.go
website/docs/guides/getting_started.html.markdown
website/docs/r/application_label.html.markdown
website/newrelic.erb

Implementation of CRUD operations for NewRelic App Labels

---

newrelic/resource_newrelic_nrql_alert_condition.go
newrelic/structures_newrelic_nrql_alert_condition.go

fix(nrql_alert_condition): terms should be a TypeSet

---

newrelic/resource_newrelic_application_label.go
newrelic/resource_newrelic_application_label_test.go
website/docs/r/application_label.html.markdown

chore(application_label): deprecate resource_newrelic_application_label

---

.github/stale.yml

This PR configures and enables our newly installed GitHub app, [Stale](https://github.com/apps/stale).

chore: configure Stale bot for the repo

---

examples/README.md
examples/modules/golden-signal-alerts/main.tf
examples/modules/golden-signal-alerts/outputs.tf
examples/modules/golden-signal-alerts/variables.tf

docs(examples): add a golden signal alerting module example

---

CHANGELOG.md

release: v1.15.1

---

go.mod
go.sum
newrelic/config.go
newrelic/provider.go
newrelic/resource_newrelic_workload.go
newrelic/resource_newrelic_workload_test.go
newrelic/structures_newrelic_workload.go
vendor/github.com/newrelic/newrelic-client-go/internal/version/version.go
vendor/github.com/newrelic/newrelic-client-go/newrelic/newrelic.go
vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/muting_rules.go
vendor/github.com/newrelic/newrelic-client-go/pkg/workloads/doc.go
vendor/github.com/newrelic/newrelic-client-go/pkg/workloads/workload.go
vendor/github.com/newrelic/newrelic-client-go/pkg/workloads/workloads.go
vendor/modules.txt
website/docs/r/workload.html.markdown
website/newrelic.erb

Resolves: #436 
This PR adds support for New Relic One workloads.

feat(workloads): add a workloads resource

---

go.mod
go.sum
newrelic/resource_newrelic_workload.go
newrelic/structures_newrelic_workload.go
vendor/github.com/newrelic/newrelic-client-go/internal/version/version.go
vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/nrql_conditions.go
vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/policies.go
vendor/github.com/newrelic/newrelic-client-go/pkg/nerdgraph/nerdgraph.go
vendor/github.com/newrelic/newrelic-client-go/pkg/workloads/workload.go
vendor/modules.txt

This PR updates newrelic-client-go to v0.19.0.

chore(newrelic): update newrelic-client-go to v0.19.0

---

website/docs/r/infra_alert_condition.html.markdown

- changed warning threshold for "high_disk_usage"
- removed unnecessary criteria for "host_not_reporting"

updated example usage section

---

newrelic/data_source_newrelic_application.go
newrelic/data_source_newrelic_application_test.go
newrelic/provider.go
newrelic/resource_newrelic_application.go
newrelic/resource_newrelic_application_test.go
newrelic/structures_newrelic_application.go
website/docs/r/application.html.markdown

feat(application): implement newrelic_application resource

---

newrelic/data_source_newrelic_alert_policy.go
newrelic/helpers.go
newrelic/helpers_test.go
newrelic/provider_test.go
newrelic/resource_helpers.go
newrelic/resource_newrelic_alert_policy.go
newrelic/resource_newrelic_alert_policy_test.go
newrelic/resource_newrelic_nrql_alert_condition_test.go
newrelic/resource_newrelic_workload_test.go
newrelic/structures_newrelic_alert_policy.go
website/docs/r/alert_policy.html.markdown

feat(alerts): convert Alerts Policies to nerdgraph

---

newrelic/resource_newrelic_nrql_alert_condition.go
newrelic/resource_newrelic_nrql_alert_condition_test.go
website/docs/d/v1/alert_channel.html.markdown
website/docs/d/v1/alert_policy.html.markdown
website/docs/d/v1/application.html.markdown
website/docs/d/v1/key_transaction.html.markdown
website/docs/d/v1/plugin.html.markdown
website/docs/d/v1/plugin_component.html.markdown
website/docs/d/v1/synthetics_monitor.html.markdown
website/docs/d/v1/synthetics_secure_credential.html.markdown
website/docs/r/nrql_alert_condition.html.markdown
website/docs/r/v1/alert_channel.html.markdown
website/docs/r/v1/alert_condition.html.markdown
website/docs/r/v1/alert_policy.html.markdown
website/docs/r/v1/alert_policy_channel.html.markdown
website/docs/r/v1/application.html.markdown
website/docs/r/v1/application_label.html.markdown
website/docs/r/v1/dashboard.html.markdown
website/docs/r/v1/infra_alert_condition.html.markdown
website/docs/r/v1/insights_event.html.markdown
website/docs/r/v1/nrql_alert_condition.html.markdown
website/docs/r/v1/plugins_alert_condition.html.markdown
website/docs/r/v1/synthetics_alert_condition.html.markdown
website/docs/r/v1/synthetics_label.html.markdown
website/docs/r/v1/synthetics_monitor.html.markdown
website/docs/r/v1/synthetics_monitor_script.html.markdown
website/docs/r/v1/synthetics_secure_credential.html.markdown
website/docs/r/v1/workload.html.markdown
website/newrelic.erb

This PR updates the `resource_nrql_alert_condition` documentation to reflect NerdGraph integration. 
It also includes v2.x docs prep

docs(nrql_alert_condition): update docs to reflect version 2.0 changes

---

newrelic/resource_newrelic_dashboard.go
newrelic/resource_newrelic_dashboard_test.go
newrelic/structures_newrelic_dashboard.go
website/docs/r/dashboard.html.markdown

feat(dashboard): [v1.x] add grid_column_count to dashboard schema

---

newrelic/resource_newrelic_dashboard.go
newrelic/resource_newrelic_dashboard_test.go
newrelic/structures_newrelic_dashboard.go
website/docs/r/dashboard.html.markdown
website/docs/r/v1/dashboard.html.markdown

This was added to the **release/v1.x** branch as a new feature. This PR adds this functionality to the **master** branch.
Resolves: #523

feat(dashboard): add grid_column_count to dashboard schema

---

newrelic/structures_newrelic_alert_condition_test.go

related to: https://github.com/newrelic/newrelic-client-go/pull/249

test(alerts): include additional test condition for "equal" operator

---

newrelic/resource_newrelic_infra_alert_condition_test.go
newrelic/structures_newrelic_infra_alert_condition.go

fix(alerts): infra alert condition zero value detection

---

newrelic/resource_newrelic_alert_policy_test.go
newrelic/resource_newrelic_application_settings.go
newrelic/resource_newrelic_application_settings_test.go

Two testing updates to resolve integration issues:
* Unable to use fake email addresses in integration tests
* Application settings resource name changed

Test updates

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml

Add some doc / contact links to issue reporting, and fix the bug template.

chore(docs): Fix bug issue, add issue config

---

CHANGELOG.md

chore: update changelog for v2.1.0 release

---

CHANGELOG.md

chore(changelog): Update CHANGELOG for v2.1.1

---

website/docs/guides/getting_started.html.markdown
website/docs/guides/migration_guide_v2.html.markdown
website/docs/index.html.markdown
website/newrelic.erb

Resolves: #698 
Resolves: #702

docs(provider): additional v2 updates, migration guide updates

---

README.md

- adds a link in the README to latest provider docs
- adds "New Relic" name to the README heading

docs(readme): update title, add link to latest documentation

---

CHANGELOG.md

Releasing **v2.1.2**. This is primarily a documentation and bug fix release.

chore(changelog): Update CHANGELOG for v2.1.2

---

website/docs/guides/provider_configuration.markdown
website/docs/index.html.markdown

fix(docs): fixed markdown rendering for new website docs

---

website/docs/r/alert_policy.html.markdown

docs(alerts): include account_id attribute for alert_policy

---

newrelic/structures_newrelic_alert_condition.go

fix(alert_condition): avoid drift when using 'user_defined' attributes

---

go.mod
go.sum
newrelic/structures_newrelic_infra_alert_condition.go
newrelic/structures_newrelic_infra_alert_condition_test.go

fix(infra_alert_condition): support zero-value thresholds for infra_alert_condition resource

---

website/docs/index.html.markdown

Clarify some of the auth requirements / roles needed as we migrate to NerdGraph / Personal API Keys
Closes #794

chore(docs): Clarify authentication used

---

newrelic/resource_newrelic_dashboard.go
website/docs/r/dashboard.html.markdown

docs(dashboard): Improve docs for limit and order_by widget attributes

---

newrelic/data_source_newrelic_synthetics_monitor_location.go
newrelic/data_source_newrelic_synthetics_monitor_location_test.go
newrelic/provider.go
website/docs/d/synthetics_monitor_location.html.markdown
website/newrelic.erb

feat(synthetics_monitor_location): add data source newrelic_synthetics_monitor_location

---

newrelic/resource_newrelic_alert_channel.go
newrelic/resource_newrelic_alert_channel_test.go
newrelic/structures_newrelic_alert_channel.go
website/docs/r/alert_channel.html.markdown

Resolves: #763 
Resolves: #420

fix(alert_channel): avoid config drift

---

newrelic/resource_newrelic_events_to_metrics_rule.go
newrelic/resource_newrelic_workload.go

chore(account_id): standardize "account_id" attribute behavior

---

newrelic/resource_newrelic_nrql_alert_condition.go
newrelic/resource_newrelic_nrql_alert_condition_test.go
newrelic/structures_newrelic_nrql_alert_condition.go
newrelic/structures_newrelic_nrql_alert_condition_test.go

fix(alerts): ensure threshold_occurrences case fold comparison

---

go.mod
go.sum
newrelic/resource_newrelic_nrql_alert_condition.go
newrelic/resource_newrelic_nrql_alert_condition_test.go
newrelic/structures_newrelic_nrql_alert_condition.go
newrelic/structures_newrelic_nrql_alert_condition_test.go
website/docs/r/nrql_alert_condition.html.markdown

TODO: Update newrelic-client-go after https://github.com/newrelic/newrelic-client-go/pull/447 is merged
Closes #810
Closes #835

Added support for expiration (loss of signal) and extrapolation (gap filling) settings

---

website/docs/d/entity.html.markdown
website/docs/guides/getting_started.html.markdown
website/docs/index.html.markdown
website/docs/r/alert_condition.html.markdown
website/docs/r/dashboard.html.markdown

Documentation updates.
cc @Julien4218

docs: various updates

---

newrelic/resource_newrelic_nrql_alert_condition.go
newrelic/resource_newrelic_nrql_alert_condition_test.go
newrelic/structures_newrelic_nrql_alert_condition.go

fix(nrql_alert_condition): update validation for nrql conditions

---

website/docs/r/nrql_alert_condition.html.markdown

docs(nrql_condition): add some clarity to nrql condition attribute descriptions

---

website/docs/index.html.markdown

Update the api key type for infra alert conditions.

docs: update infra alert condition api key type

---

.github/workflows/compile.yml
README.md
go.mod

docs: update supported Go information and test config

---

README.md
newrelic/provider_test.go
newrelic/resource_newrelic_dashboard.go
newrelic/resource_newrelic_dashboard_test.go
newrelic/structures_newrelic_dashboard.go
website/docs/r/dashboard.html.markdown

feat(dashboard): support cross-account widgets :)

---

go.mod
go.sum
newrelic/resource_newrelic_nrql_alert_condition.go
newrelic/resource_newrelic_nrql_alert_condition_test.go
newrelic/structures_newrelic_nrql_alert_condition.go
newrelic/structures_newrelic_nrql_alert_condition_test.go

Goal: Add support for optional integer aggregation_window.
Prerequisite: https://github.com/newrelic/newrelic-client-go/pull/494

feat: Add newrelic_nrql_alert_condition.aggregation_window

---

website/docs/guides/migration_guide_v2.html.markdown

chore(docs): update migration guide regarding when admin API key was removed

---

newrelic/resource_newrelic_nrql_alert_condition.go

fix(nrql_alert_condition): fix fill_option DiffSuppressFunc

---

newrelic/data_source_newrelic_entity.go

fix(newrelic_entity): include additional ID attr for browser apps

---

website/docs/r/nrql_alert_condition.html.markdown

docs(nrql_alert_condition): include notes about upgrading from 1.x

---

website/docs/d/entity.html.markdown

correctly added the filter example this time.

chore: added filter example

---

go.mod
go.sum
newrelic/provider.go
newrelic/resource_newrelic_dashboard.go
newrelic/resource_newrelic_one_dashboard.go
newrelic/resource_newrelic_one_dashboard_test.go
newrelic/structures_newrelic_dashboard.go
newrelic/structures_newrelic_one_dashboard.go
website/docs/index.html.markdown
website/docs/r/one_dashboard.html.markdown

*Note:* Dashboard API via NerdGraph is in closed beta, this PR will not work for everyone at this time.
Refactor `newrelic_dashboard` to use the new GraphQL API, enabling all new dashboard features (pages/multi-query/etc)

Implement GraphQL Dashboard API

---

website/docs/r/one_dashboard.html.markdown

This PR updates the `nrql_query` samples  to use the correct attribute which is now `query`

chore: updated nrql_query examples

---

website/docs/r/one_dashboard.html.markdown

removes beta section from docs... 🥳

chore: removed beta section from docs

---

CHANGELOG.md

- Releases `newrelic_one_dashboard` to GA

chore(changelog): Update CHANGELOG for v2.16.0

---

go.sum
newrelic/resource_newrelic_one_dashboard.go
newrelic/resource_newrelic_one_dashboard_test.go
newrelic/structures_newrelic_one_dashboard.go
website/docs/r/one_dashboard.html.markdown

This may address the following issues, or if it gets too big, a few of them in the following order:
Added support for the additional 4 widget types (bullet, funnel, heatmap, histogram)

Improvements to newrelic_one_dashboard

---

CHANGELOG.md

- **one_dashboard:** Table Widget should have filter on them
- **one_dashboard:** Inherit nrql_query account_id from dashboard by default
- update changelog
- **one_dashboard:** Add support for widget_histogram
- **one_dashboard:** Add support for widget_funnel
- **one_dashboard:** Add support for widget_bullet
- **one_dashboard:** Add widget_heatmap

chore(changelog): Update CHANGELOG for v2.19.0

---

website/docs/r/infra_alert_condition.html.markdown

Fix for #1280 - Documentation needs updating for newrelic_infra_alert_condition to support 'description' field

fix(infra_alert_condition): Added missing documentation

---

newrelic/resource_newrelic_alert_condition.go
newrelic/resource_newrelic_alert_condition_unit_test.go

Fix condition name length to match API definition

---

go.mod
go.sum
newrelic/provider.go
newrelic/resource_newrelic_service_level.go
newrelic/resource_newrelic_service_level_test.go
newrelic/structures_newrelic_service_level.go

- Bump newrelic-client-go version
- Add new resource to manage service levels

feat(servicelevel): Add service level resource

---

website/docs/r/synthetics_multilocation_alert_condition.markdown

To fix #1519 
Sorry for recreating the PR @mbazhlekova but my git is quiet messed up since I started using gitlab and github in this PC, git reverts and git rebase sometimes go south :)

docs: Fix synthetics_multilocation_alert_condition.markdown

---

CHANGELOG.md
newrelic/resource_newrelic_one_dashboard.go
newrelic/resource_newrelic_one_dashboard_test.go

Surface error messages on dashboard update

---

newrelic/resource_newrelic_one_dashboard.go
newrelic/resource_newrelic_one_dashboard_test.go
newrelic/structures_newrelic_one_dashboard.go

Reverts newrelic/terraform-provider-newrelic#1524

Revert "fix: manually handled the state change for filter_current_dashboard. …"

---

website/docs/guides/getting_started.html.markdown

Fix broken link to "Install Terraform"

docs: Fix link to Install Terraform

---

newrelic/resource_newrelic_synthetics_multilocation_alert_condition.go
newrelic/resource_newrelic_synthetics_multilocation_alert_condition_integration_test.go

This will cause a breaking change and we should hold off not releasing for now.

Revert multilocation_violation_time_limit_seconds

---

website/docs/r/workload.html.markdown

Adding a workload example using tags in the dynamic query for more clarification in this topic.

docs: add example of workload using tags

---

newrelic/resource_newrelic_nrql_alert_condition.go

Update outlier condition EOL to new date of Mar 31, 2022 in nrql_alert_condition validation warning

chore(nrql_alert_condition): update outlier eol date

---

newrelic/resource_newrelic_nrql_alert_condition.go

This is a start to address #1635

Document allowed values for expiration_duration

---

newrelic/resource_newrelic_synthetics_monitor.go
website/docs/r/synthetics_monitor.html.markdown

Made some changes based on feedback from https://discuss.newrelic.com/t/explanation-for-sla-threshold-in-newrelic-synthetics-monitor-resource/175037/2
Documentation update

chore(newrelic_synthetics_monitor): improved documentation on sla_threshold

---

website/docs/guides/getting_started.html.markdown

This change fixes a broken link in the documentation

docs: fix broken link to data sources docs

---

newrelic/data_source_newrelic_cloud_account.go
newrelic/resource_newrelic_service_level_test.go

This PR fixes a failing tests for the Service Level resource

Fix failing tests

---

CHANGELOG.md

chore(changelog): Update CHANGELOG for v2.38.0

---

newrelic/resource_newrelic_nrql_alert_condition_test.go

chore: fix some alerts test

---

newrelic/resource_newrelic_one_dashboard_test.go
newrelic/structures_newrelic_one_dashboard.go

fix(dashboard): handle filter_current_dashboard on read

---

CHANGELOG.md
go.mod
go.sum

chore(changelog): Update CHANGELOG for v2.39.0

---

CHANGELOG.md

chore(changelog): Update CHANGELOG for v2.39.1

---

website/docs/r/alert_channel.html.markdown
website/docs/r/alert_policy_channel.html.markdown

Small change to add docs for #1676 

feat(docs): added accountID to alert_channel and alert_policy_channel

---

CHANGELOG.md

chore(changelog): Update CHANGELOG for v2.39.2

---

website/docs/index.html.markdown

This updates the guide sample config to version 2.37.0 since we're recommending all users upgrade.

Update TF Provider sample version in docs

---

CHANGELOG.md

Release/v2.41.0 beta.1

---

CHANGELOG.md

chore(changelog): Update CHANGELOG for v2.41.1

---

CHANGELOG.md

chore(changelog): Update CHANGELOG for v2.41.2

---

website/docs/r/service_level.html.markdown

Delete Beta banner for service level since we launched GA yesterday and adding an example of how to tags service levels given we received some questions about it. 
- [ X] This change requires a documentation update
- [ X] My commit message follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ X] I have performed a self-review of my own code
- [X ] I have made corresponding changes to the documentation
- [ X] New and existing unit tests pass locally with my changes. Go [here](https://github.com/newrelic/terraform-provider-newrelic#testing) for instructions on running tests locally.

docs: remove beta level and add an example with tags for service levels

---

CONTRIBUTING.md

- [ ✅] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ✅] My commit message follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ✅] My code is formatted to [Go standards](https://go.dev/blog/gofmt)
- [✅ ] I have performed a self-review of my own code
- [✅ ] I have made corresponding changes to the documentation
- [✅ ] I have added tests that prove my fix is effective or that my feature works
- [ ✅] New and existing unit tests pass locally with my changes. Go [here](https://github.com/newrelic/terraform-provider-newrelic#testin …

chore: removing the DTK reference in contributing file

---

.github/workflows/release.yml
scripts/release.sh

This PR allows the release workflow to be run from the GitHub UI

Allow release workflow to be triggered from GitHub UI

---

website/docs/index.html.markdown

Improved support for v2 message in docs

chore(docs): clarified support for v2

---

website/docs/r/one_dashboard.html.markdown

Add `filter_current_dashboard` doc for `widget_bar` and `widget_pie`.
N/A

docs(resource/one_dashboard): Add missing filter_current_dashboard doc

---

newrelic/resource_newrelic_cloud_azure_integrations.go
newrelic/resource_newrelic_cloud_azure_integrations_test.go
website/docs/r/cloud_azure_integrations.html.markdown

- [✅ ] Bug fix (non-breaking change which fixes an issue)
- [✅ ] My commit message follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [✅ ] My code is formatted to [Go standards](https://go.dev/blog/gofmt)
- [✅ ] I have performed a self-review of my own code
- [✅ ] I have made corresponding changes to the documentation
- [✅ ] I have added tests that prove my fix is effective or that my feature works
- [✅ ] New and existing unit tests pass locally with my changes. Go [here](https://github.com/newrelic/terraform-provider-newrelic#testing) for instructions on running tests locally. …

Removing the azure service fabric

---

newrelic/provider.go
newrelic/resource_newrelic_cloud_aws_govcloud_integrations.go
newrelic/resource_newrelic_cloud_aws_govcloud_integrations_test.go
website/docs/r/cloud_aws_govcloud_integrations.html.markdown

- [ ✅] New feature (non-breaking change which adds functionality)
- [✅ ] My commit message follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ✅] My code is formatted to [Go standards](https://go.dev/blog/gofmt)
- [ ✅] I have performed a self-review of my own code
- [✅ ] I have made corresponding changes to the documentation
- [ ✅] I have added tests that prove my fix is effective or that my feature works
- [ ✅] New and existing unit tests pass locally with my changes. Go [here](https://github.com/newrelic/terraform-provider-newrelic#testing) for instructions on running tests …

Awsgovcloud integrations

---

newrelic/resource_newrelic_cloud_azure_integrations.go
website/docs/r/cloud_azure_integrations.html.markdown

Fixes a couple of issues with azure integrations
Fixes #1771 
Fixes #1772

Update correct value for Azure Firewalls

---

examples/cloud-integrations-gcp.tf

feat: added gcp integrations test tf script

---

go.mod
go.sum

chore(deps): upgrade newrelic-client-go to v0.80.0

---

website/docs/r/cloud_aws_integrations.html.markdown
website/docs/r/cloud_aws_link_account.html.markdown
website/docs/r/cloud_azure_integrations.html.markdown
website/docs/r/cloud_azure_link_account.html.markdown
website/docs/r/cloud_gcp_integrations.html.markdown
website/docs/r/cloud_gcp_link_account.html.markdown

Brought forward the full examples we provide for cloud integrations on the resource pages.

chore: added link to guides from cloud resources

---

go.mod
go.sum

Update `newrelic-client-go` module including new retry feature.
- Updated and build locally
- Applied changes from the internal NR project  [SSRE Monitoring](https://source.datanerd.us/streaming-sre/monitoring) testing the change effectively resolved the issue.

chore(build): update newrelic-client-go module

---

newrelic/resource_newrelic_one_dashboard.go
newrelic/resource_newrelic_one_dashboard_test.go
newrelic/structures_newrelic_one_dashboard.go
website/docs/guides/cloud_integrations_guide.html.markdown
website/docs/r/one_dashboard.html.markdown

Added ignore time picker to newrelic_one_dashboard and added a test for the changes.
Fixes #1829 

Added ignore time picker to newrelic_one_dashboard

---

website/docs/r/one_dashboard.html.markdown

Small doc change to improve example with multi queries, and to make it a valid dashboard.

chore(docs): added and improved example for multiple queries

---

newrelic/resource_newrelic_one_dashboard.go
newrelic/resource_newrelic_one_dashboard_test.go
newrelic/structures_newrelic_one_dashboard.go
website/docs/r/one_dashboard.html.markdown

Adds a `widget_log_table` resource.
~⚠️ disclaimer, this probably doesn't work. This is the first time I've ever written Go, and I'm mostly just pattern matching here. If someone who is more familiar with this wants to point me in the right direction or take this PR over, I would love it.~
Edit: this now works, thanks to @kidk 's help! 😄 
Fixes #1831 
- Step 1
- Step 2
- etc

Add log table widget support

---

website/docs/r/one_dashboard.html.markdown

Documentation change to highlight functionality in the CLI to convert dashboards to HCL
Documentation update
Read it

chore(docs): added instructions on how to convert existing dashboard to HCL

---

website/docs/r/cloud_azure_integrations.html.markdown

- [ X] I have made corresponding changes to the documentation
- Step 1
- Step 2
- etc

Document changes in Azure metric polling interval

---

website/docs/r/synthetics_monitor_step.html.markdown

Added the step monitor documentation.

chore(docs): Added step monitor doc

---

website/docs/r/synthetics_monitor_broken_links.html.markdown

- [X ] My commit message follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [X ] I have performed a self-review of my own code
- [ X] I have made corresponding changes to the documentation
- Step 1
- Step 2
- etc

Documentation for broken link monitor

---

website/docs/r/synthetics_monitor.html.markdown
website/docs/r/synthetics_script_monitor.html.markdown

synthetic monitors doc

---

.github/ISSUE_TEMPLATE/config.yml
.github/SUPPORT.md
README.md
website/docs/index.html.markdown

Global technical support now officially supports Terraform 🥳 
Fixes #1914
Documentation update

Upgraded support status of Terraform

---

website/docs/guides/migration_guide_v3.html.markdown

docs: add v3 migration guide

---

go.mod
go.sum
newrelic/notifications_helpers.go
newrelic/resource_newrelic_notifications_channel.go
newrelic/resource_newrelic_notifications_destination.go

Add custom errors handling to notifications: destinations & channels.

fix(notifications): add custom errors handling to notifications

---

newrelic/structures_newrelic_notifications_channel.go
newrelic/structures_newrelic_notifications_destination.go

Add internal property for notifications monitoring.

fix(notifications): add internal property

---

.github/ISSUE_TEMPLATE/bug_report.md
.gitignore
CONTRIBUTING.md
README.md
testing/newrelic.tf

README and Contribution guide improvements

---

examples/modules/golden-signal-alerts/main.tf

Small fix in our golden signal example

chore: updated golden signal example

---

newrelic/resource_newrelic_workflow.go
website/docs/r/notification_channel.html.markdown
website/docs/r/notification_destination.html.markdown
website/docs/r/workflow.html.markdown

Update notifications & workflows docs according to schema changes.

chore(notifications): update docs

---

website/docs/r/alert_policy_channel.html.markdown

Corrected the docs of alert policy channel

chore(docs): updated alert policy channel example

---

newrelic/resource_newrelic_synthetics_broken_links_monitor.go
newrelic/resource_newrelic_synthetics_cert_check_monitor.go
newrelic/resource_newrelic_synthetics_monitor.go
newrelic/resource_newrelic_synthetics_script_monitor.go
newrelic/resource_newrelic_synthetics_step_monitor.go
testing/newrelic.tf
website/docs/r/synthetics_monitor_step.html.markdown

Found some issues here and there

Set of synthetic monitor improvements for read and delete

---

newrelic/resource_newrelic_entity_tags.go

fix(newrelic_entity_tags): increased timeout level

---

newrelic/resource_newrelic_notifications_destination.go

Fixes # (#1960 )
- Step 1
- Step 2
- etc

fix: made accountId optional in the schema

---

newrelic/resource_newrelic_cloud_aws_integrations.go

Fixes #1956 
- [] My commit message follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- Step 1
- Step 2
- etc

feat: add s3 and docDb to AWS integration

---

newrelic/resource_newrelic_alert_policy.go

fix(alert_policy): added computed to account_id

---

.gitignore
newrelic/resource_newrelic_one_dashboard.go
newrelic/structures_newrelic_one_dashboard.go
website/docs/r/one_dashboard.html.markdown

Fix for #1891 and a restructure of our dashboard resource to only use rawConfiguration. This will allow us to add a lot of new dashboard features. The new changes will be part of a different PR.

Restructuring dashboard code to remove use of configuration

---

website/docs/r/notification_destination.html.markdown

Fixes # ([2000](https://github.com/newrelic/terraform-provider-newrelic/issues/2000))
- Step 1
- Step 2
- etc

NR-51083: Added property block in docs of notification destinations

---

newrelic/provider.go
newrelic/resource_newrelic_one_dashboard_json.go
newrelic/resource_newrelic_one_dashboard_json_test.go
newrelic/structures_newrelic_one_dashboard_json.go
website/docs/index.html.markdown
website/docs/r/one_dashboard_json.html.markdown

Adding a `newrelic_one_dashboard_json` that uses an exported dashboard from UI. 
```
resource "newrelic_one_dashboard_json" "foo" {
json = file("dashboard1.json")
}
```
Possible fix for #540

newrelic_one_dashboard_json resource

---

website/docs/r/synthetics_monitor.html.markdown
website/docs/r/synthetics_monitor_broken_links.html.markdown
website/docs/r/synthetics_monitor_cert_check.html.markdown
website/docs/r/synthetics_monitor_step.html.markdown
website/docs/r/synthetics_script_monitor.html.markdown

This PR fixes some inconsistency in the synthetics monitors docs.
N/A

Fix issues with synthetics monitors docs

---

website/docs/r/synthetics_monitor.html.markdown
website/docs/r/synthetics_script_monitor.html.markdown

docs: update monitor with private location examples

---

website/docs/r/one_dashboard_json.html.markdown

chore(one_dashboard_json): fixed typo

---

newrelic/data_source_newrelic_entity.go

chore(entity): trim trailing and leading spaces in returned name

---

website/docs/r/workload.html.markdown

Updated docs on status config in workloads

NR-53341: Updated docs on status config

---

website/docs/d/entity.html.markdown

Update a page for https://github.com/newrelic/terraform-provider-newrelic/pull/1018
- Data Source
- `newrelic_entity`
- Attributes
- `serving_apm_application_id`
No added testing as it’s document update only

docs: Update reference for data.newrelic_entity

---

newrelic/resource_newrelic_workload_test.go
newrelic/structures_newrelic_workflow.go

Fix build after newrelic client version update

Fix build after newrelic client version update

---

go.mod
go.sum
newrelic/resource_newrelic_alert_condition.go
website/docs/r/alert_condition.html.markdown

NR-52189: mobile metric missing user def value funcs

---

website/docs/r/workflow.html.markdown

I added a way for users to get the workflow id needed in as shown in the previous documentation.
- Step 1
- Step 2
- etc

chore(Workflows): Add Copy workflow id button

---

newrelic/resource_newrelic_workflow.go
website/docs/r/workflow.html.markdown

This commit aims to provide some missing details, as well as improve examples to go inline with the intended way to use workflows

chore(workflows): update workflow documentation

---

go.mod
go.sum
newrelic/provider.go
newrelic/resource_newrelic_obfuscation_expression.go
newrelic/resource_newrelic_obfuscation_expression_test.go

This PR includes:
New Feat => Obfuscation expression
```
resource "newrelic_obfuscation_expression" "foo"{
name = "Testing"
description = "%[3]s"
regex = "(^http)"
}
```

NR-62325: Added Obfuscation expression and tests

---

website/docs/r/obfuscation_expression.html.markdown

This PR includes
* Doc for Obfuscation expression

NR-62326: added docs for obfuscation expression

---

website/docs/r/synthetics_monitor.html.markdown
website/docs/r/synthetics_monitor_broken_links.html.markdown
website/docs/r/synthetics_monitor_cert_check.html.markdown
website/docs/r/synthetics_monitor_step.html.markdown
website/docs/r/synthetics_private_location.html.markdown
website/docs/r/synthetics_script_monitor.html.markdown

docs: fix import command for script monitor

---

newrelic/resource_newrelic_obfuscation_rule.go
website/docs/r/obfuscation_rule.html.markdown

docs(obfuscation_rule): minor changes

---

newrelic/resource_newrelic_synthetics_private_location.go

fix(synthetics): prevent crash if private location response is nil

---

go.mod
go.sum
newrelic/resource_newrelic_one_dashboard.go
newrelic/resource_newrelic_one_dashboard_test.go
newrelic/structures_newrelic_one_dashboard.go
website/docs/r/one_dashboard.html.markdown

feat(one_dashboard): add variables

---

website/docs/r/entity_tags.html.markdown

docs(entity_tags): add example of applying tags to multiple entities using a dynamic block

---

website/docs/r/one_dashboard.html.markdown

updated variable argument placing for one dashboard example documentation
Fixes #2148

chore(docs): updated variable argument placing for one dashboard example doc |  NR-73279

---

go.mod
go.sum
newrelic/resource_newrelic_one_dashboard_json_test.go
newrelic/resource_newrelic_one_dashboard_test.go
newrelic/resource_newrelic_workflow.go
newrelic/structures_newrelic_one_dashboard.go

fix(dashboards): handle empty values returned from API

---

newrelic/resource_newrelic_service_level_test.go
newrelic/resource_newrelic_workload.go
newrelic/resource_newrelic_workload_test.go
website/docs/r/workload.html.markdown

Changes:
* Made At least one of either `entity_guids` or `entity_search_query` is required.
* Removed forceful creation.

NR-67725: Removed forcenew for entity guids and changed docs

---

website/docs/r/notification_channel.html.markdown

The given example is not working as has been reported few times: #2032 #1974

docs(notification_channel): fix email notification channel example

---

website/docs/r/alert_condition.html.markdown
website/docs/r/synthetics_alert_condition.html.markdown

chore(docs): updated docs from info to warning | NR-29881

---

website/docs/r/alert_channel.html.markdown
website/docs/r/alert_policy_channel.html.markdown
website/docs/r/notification_channel.html.markdown
website/docs/r/notification_destination.html.markdown

Jira tickets:
https://issues.newrelic.com/browse/NR-75434
https://issues.newrelic.com/browse/NR-72021
https://issues.newrelic.com/browse/NR-70234
Add more information to docs according to customer's questions.
Doc update

chore(docs): Update notifications docs with customer's questions

---

website/docs/index.html.markdown

chore(website): added links to public guides

---

website/docs/r/log_parsing_rule.html.markdown

NR-53374 documentation for log configuration parsing rule

---

newrelic/resource_newrelic_synthetics_private_location.go

fix(private_locations): returning the right err

---

tools/go.mod
tools/go.sum

chore(deps): update gotestsum

---

website/docs/r/one_dashboard.html.markdown

Improved the message after customer feedback

docs(dashboards): improved deprecation message to be less scary

---

website/docs/r/one_dashboard_raw.html.markdown

Seems I forgot to push one commit

chore(dashboard): updated dashboard_raw with same message as one_dashboard

---

website/docs/r/workflow.html.markdown

Update documentation on workflow filters

chore(workflows): update workflow filter documentation

---

website/docs/r/nrql_alert_condition.html.markdown

- Removing value_function from the docs
- Removing value_function from the docs
- The change only contains 2 line deletion in the markdown files. No Go code changes etc.

Removing value_function from the markdown docs

---

newrelic/data_source_newrelic_notifications_destination.go
newrelic/data_source_newrelic_notifications_destination_test.go
newrelic/provider.go
newrelic/resource_newrelic_notifications_channel_test.go
website/docs/d/notifications_destination.html.markdown

Add Notification Destination Data Source.
- Add data source:
```
data "newrelic_notification_destination" "foo-source" {
id = "<destination_id>"
}
```
- Run `terraform apply`

feat(notification_destination): add notification destination data source

---

website/docs/d/test_grok_pattern.html.markdown

chore: updated docs for test grok pattern

---

website/docs/index.html.markdown

Updated docs to clarify v2 and v3 support

docs: updated notice for v2 support and v3 details

---

newrelic/resource_newrelic_one_dashboard.go
newrelic/resource_newrelic_one_dashboard_test.go
newrelic/structures_newrelic_one_dashboard.go

Fix for https://github.com/newrelic/terraform-provider-newrelic/issues/2230

fix(one_dashboard): fix for updating with filter_current_dashboard

---

newrelic/resource_newrelic_cloud_aws_integrations.go
newrelic/resource_newrelic_cloud_aws_link_account.go
newrelic/resource_newrelic_cloud_azure_integrations.go
newrelic/resource_newrelic_cloud_azure_link_account.go
newrelic/resource_newrelic_cloud_gcp_integrations.go
newrelic/resource_newrelic_cloud_gcp_link_account.go

Resource persists through terraform even after deleting it from UI.
Fixes #2065 

fix(cloud): Reset id if resource not found

---

newrelic/resource_newrelic_alert_condition.go
newrelic/resource_newrelic_alert_policy.go
newrelic/resource_newrelic_alert_policy_channel.go
newrelic/resource_newrelic_infra_alert_condition.go
newrelic/resource_newrelic_synthetics_alert_condition.go
newrelic/resource_newrelic_synthetics_multilocation_alert_condition.go
website/docs/r/alert_condition.html.markdown
website/docs/r/alert_policy.html.markdown
website/docs/r/alert_policy_channel.html.markdown
website/docs/r/infra_alert_condition.html.markdown
website/docs/r/synthetics_alert_condition.html.markdown
website/docs/r/synthetics_multilocation_alert_condition.markdown

docs(alerts): adjustments to deprecation messages

---

go.mod
go.sum
newrelic/provider.go
newrelic/resource_newrelic_data_partition.go
newrelic/resource_newrelic_data_partition_test.go
website/docs/r/data_partition_rule.html.markdown

added data partition rules and tests

feat(data_partition): added data partition rules and tests

---

newrelic/data_source_newrelic_cloud_account_test.go
newrelic/resource_newrelic_cloud_aws_govcloud_integrations_test.go
newrelic/resource_newrelic_cloud_gcp_integrations_test.go
newrelic/resource_newrelic_cloud_gcp_link_account_test.go
newrelic/resource_newrelic_one_dashboard_test.go
website/docs/r/cloud_aws_govcloud_integrations.html.markdown

Updated the  accountId with new accountId
Need to update the required environment variables in the secrets and run the integration tests

chore(new_test_account): updated accountId with new account id

---

website/docs/index.html.markdown

This PR addresses [NR-96690](https://issues.newrelic.com/browse/NR-96990), changes made to the markdown file to be rendered to the webpage, comprising updates made to Resources and Data Sources on the NR Terraform Provider [Registry Page](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs).

docs: add/update resources and data sources in the NR terraform registry

---

go.mod
go.sum
newrelic/provider.go
newrelic/resource_newrelic_account_management.go
newrelic/resource_newrelic_account_management_test.go
website/docs/r/account_management.hmtl.markdown

Added new resource for the account management API's which contains create and update a sub account .
Added test cases  on the  update and import of the resource.
Added documentation on how to use this resource

feat: added account managent resource, docs, examples and test cases

---

website/docs/r/one_dashboard_json.html.markdown

Verify if the below documentation is updated with the import procedure.
https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/one_dashboard_json

docs: add examples to dashboard resource to demonstrate importing dashboards using GUID

---

website/docs/index.html.markdown

Update documentation with the new account management resource.

docs: update docs with newrelic_account_management resource

---

website/docs/r/synthetics_cert_check_monitor.html.markdown

Update newrelic_synthetics_cert_check_monitor example to use correct argument.

docs: update newrelic_synthetics_cert_check_monitor example to use correct argument.

---

website/docs/r/synthetics_monitor.html.markdown

docs: update synthetic monitor default runtime notes.

---

newrelic/resource_newrelic_synthetics_monitor_test.go

Revert previous commit [baea62f](https://github.com/newrelic/terraform-provider-newrelic/commit/baea62f0935f713e10a82c5487b8a8398ddbd316)

Revert "feat(synthetics): Synthetics monitor additional field to output period in minutes.

---

website/docs/r/one_dashboard.html.markdown

Small documentation change to bring forward the CLI as a conversion tool for dashboards.

docs(one_dashboard): added documentation on how to use the CLI to convert dashboards to HCL

---

newrelic/resource_newrelic_data_partition_test.go

Cleans up all the data partitions created during the integration tests before running the integration test
- Step 1
- Step 2
- etc

chore(data_partition): tests refactor

---

newrelic/resource_newrelic_cloud_aws_integrations.go
newrelic/resource_newrelic_cloud_aws_integrations_test.go
newrelic/resource_newrelic_obfuscation_expression_test.go
newrelic/resource_newrelic_obfuscation_rule_test.go
newrelic/structures_newrelic_nrql_alert_condition_test.go
newrelic/structures_newrelic_synthetics_multilocation_alert_condition_test.go

See #2253
Added:
* SQS
* Elasticache
* EBS
* ALB
- Step 1
- Step 2
- etc

feat: additional poll integrations (sqs, ebs, alb, elasticache)

---

website/docs/guides/continuos_validation_with_terraform_cloud.markdown

Example of the new Terraform checks feature
Download release candidate of terraform with tfenv: `tfenv use 1.5.0-rc2`

chore(docs): added Continuous Validation with Terraform Cloud guide

---

go.mod
go.sum
newrelic/resource_newrelic_one_dashboard_json_test.go
newrelic/resource_newrelic_one_dashboard_raw_test.go
newrelic/resource_newrelic_one_dashboard_test.go
newrelic/structures_newrelic_one_dashboard.go
newrelic/structures_newrelic_one_dashboard_raw.go

This PR addresses a fix to #2376 to enable creating dashboards with empty pages (i.e. with pages comprising no widgets) and tests to validate the same.
- The reason why a dashboard cannot be created with a page with no widgets is because an empty list needs to be sent to the API when there are no widgets; and the following explain the problems
- The attribute **[]DashboardWidgetInput** is configured to omit empty values in client-go; so sending an empty list would make it null, which is not expected by the API. If there are no widgets, the API expects to receive an empty list **[]**, to enable which **omitempty** in client-go has been removed in this PR: https://github.com/newrelic/newrelic-client-go/pull/1033/
- Even with the above fix, in the one_dashboard_raw and one_dashboard …

fix(dashboards): code changes to enable dashboards with empty pages

---

go.mod
go.sum

chore(deps): update go-client to v2.19.4

---

.github/PULL_REQUEST_TEMPLATE.md

fixes link in PULL_REQUEST_TEMPLATE.md

fix: link in PR template

---

website/docs/r/service_level.html.markdown

This is just a documentation change. CDF was not an open feature in service levels, we are opening it and we needed a documentation update.

docs: add documentation for the cdf functionality in Service Levels

---

website/docs/r/application_settings.html.markdown

Fix typo in application_settings doc.

docs: fix typo

---

website/docs/r/synthetics_monitor.html.markdown
website/docs/r/synthetics_script_monitor.html.markdown

Adding `device emulation` fields documentation references. Follow up of: [NR-90076](https://issues.newrelic.com/browse/NR-90076)
Documentation update.

docs(synthetics): Add device emulation fields reference

---

newrelic/structures_newrelic_cloud_aws_integrations.go

Reversal of a bug introduced by https://github.com/newrelic/terraform-provider-newrelic/pull/2289/files#r1318134653

fix(aws_cloud_integrations): condition change to fix a bug with disabling selected integrations

---

newrelic/resource_helpers_synthetics.go
newrelic/resource_newrelic_synthetics_cert_check_monitor.go
newrelic/resource_newrelic_synthetics_monitor.go
website/docs/r/synthetics_broken_links_monitor.html.markdown
website/docs/r/synthetics_cert_check_monitor.html.markdown
website/docs/r/synthetics_monitor.html.markdown
website/docs/r/synthetics_script_monitor.html.markdown
website/docs/r/synthetics_step_monitor.html.markdown

JIRA - https://issues.newrelic.com/browse/NR-167849 
Update MUTED status deprecation notice to the synthetic monitors.

docs(synthetics): update MUTED status deprecation notice to the synthetic monitors.

---

newrelic/resource_newrelic_alert_muting_rule.go
newrelic/structures_newrelic_alert_muting_rule.go
newrelic/structures_newrelic_alert_muting_rule_test.go

The error handling mechanism of `newrelic_alert_muting_rule` has a small issue; it currently doesn't throw errors which are not of the type `alerts.GraphQLErrorResponse`.
The changes in this PR wrap the block of code throwing the error around another condition which throws other errors too. (with an `else`
An issue identified by a customer points that the error handling mechanism of the resource `newrelic_alert_muting_rule` is broken. When a few types of errors are returned by the step in the code that creates a muting rule via NerdGraph, the error is not thrown; instead, the provider runs into a panic, and crashes.
```
Stack trace from the terraform-provider-newrelic_v3.21.3 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation …
```

fix(muting_rule): error handling update to throw non-GraphQL errors too

---

website/docs/d/entity.html.markdown

docs(newrelic_entity): typo correction and refactoring

---

tools/go.mod
tools/go.sum

Attempt to fix 
https://github.com/newrelic/terraform-provider-newrelic/security/dependabot/39
https://github.com/newrelic/terraform-provider-newrelic/security/dependabot/36
https://github.com/newrelic/terraform-provider-newrelic/security/dependabot/35

chore(deps): upgrade circl and crypto in tools (manual)

---

go.mod
go.sum
newrelic/data_source_newrelic_authentication_domain.go
newrelic/data_source_newrelic_authentication_domain_test.go
newrelic/provider.go
website/docs/d/authentication_domain.html.markdown

JIRA's -
https://new-relic.atlassian.net/browse/NR-76849
https://new-relic.atlassian.net/browse/NR-76868

feat(auth_domains): add data source to fetch auth domains

---

website/docs/r/cloud_azure_integrations.html.markdown
website/docs/r/user.html.markdown

Minor corrections (inclusive of a fix to #2530)

docs: minor corrections

---

go.mod
go.sum
newrelic/data_source_newrelic_alert_policy.go
newrelic/resource_newrelic_alert_policy.go
website/docs/d/alert_policy.html.markdown
website/docs/r/alert_policy.html.markdown

docs(alert_policy): make incident_preference types clear

---

newrelic/resource_newrelic_one_dashboard.go
newrelic/structures_newrelic_one_dashboard.go
website/docs/r/one_dashboard.html.markdown

fix(dashboards): tweaks to the ignore_time_range attribute added via #2597

---

tools/go.mod
tools/go.sum

Fixes
https://github.com/newrelic/terraform-provider-newrelic/security/dependabot/57
https://github.com/newrelic/terraform-provider-newrelic/security/dependabot/56
https://github.com/newrelic/terraform-provider-newrelic/security/dependabot/55
https://github.com/newrelic/terraform-provider-newrelic/security/dependabot/54

chore: bump up deps protobuf and docker

---

newrelic/resource_newrelic_workload_test.go

chore(workloads): alter test TestAccNewRelicWorkload_EntitySearchQueriesOnly to adapt to recent updates #2605 #2591

---

newrelic/resource_newrelic_agent_application_browser.go
newrelic/resource_newrelic_agent_application_browser_integration_test.go
website/docs/r/browser_application.html.markdown

fix(browserapplication): fixes to #2577, export application_id

---

go.mod
go.sum
newrelic/data_source_newrelic_notifications_destination.go
newrelic/data_source_newrelic_notifications_destination_test.go
newrelic/resource_newrelic_notifications_destination.go
newrelic/resource_newrelic_notifications_destination_test.go
newrelic/structures_newrelic_notifications_destination.go
newrelic/structures_newrelic_notifications_destination_test.go
website/docs/d/notification_destination.html.markdown
website/docs/r/notification_destination.html.markdown

This PR adds logic in regards to 2 new fields on destinations.
Custom Headers Auth- Another type of auth, which uses a list of key values.
SecureUrl- A new and secure way to add url to your destination, now separated into a a non-secure prefix and a secure suffix.
Requires https://github.com/newrelic/newrelic-client-go/pull/1122
- Step 1
- Step 2
- etc

feat(destinations): add new fields to destinations; secureUrl, custom headers auth and more

---

.github/workflows/changelog.yml
.github/workflows/compile.yml
.github/workflows/release.yml
.github/workflows/test.yml
.golangci.yml
build/tools.mk
go.mod
go.sum
testing/newrelic.tf
tools/go.mod
tools/go.sum

fix(build): upgrade to go1.21

---

CHANGELOG.md

chore(changelog): update CHANGELOG for v3.35.2

---

CHANGELOG.md

chore(changelog): restore changelog deleted by #35b51d26d7d72f8892dd040d2b262ebf2777aee3

---

CHANGELOG.md

chore(changelog): restore changelog deleted by  #fbebaced9e002a4f191487992fcfd4a5ca8baeee

---

go.mod
go.sum
newrelic/resource_newrelic_one_dashboard.go
newrelic/resource_newrelic_one_dashboard_test.go
newrelic/structures_newrelic_one_dashboard.go
newrelic/structures_newrelic_one_dashboard_helpers.go
website/docs/r/one_dashboard.html.markdown

This PR adds support for the following attributes to the resource `newrelic_one_dashboard`
- `y_axis_right`: This helps specify ranges of values and more of the "right" Y - Axis, currently available only to line widgets, and comprises nested attributes `y_axis_right_zero`, `y_axis_right_min`, `y_axis_right_max`, `y_axis_right_series`
- `is_label_visible`: This helps control the `Label Always Visible` toggle under the thresholds section in the settings of a widget, currently available only to line widgets.
- `threshold`: This helps specify thresholds with line and table widgets, on the basis of which the visual appearance of values in the ranges specified in these thresholds changes (e.g. warning, critical ranges). This is currently available to line and table widgets (is also available to …

feat(dashboards): add support for thresholds in line, table and yAxisRight in line widgets

---

go.mod
go.sum
newrelic/provider_test.go

chore: fix failing tests and more caused by the entities cleanup in client-go

---

website/docs/r/one_dashboard.html.markdown

Signed-off-by: smcavallo <smcavallo@hotmail.com>
fixes dashboard threshold documentation.
The current values (if used) generate an exception:
```
Attribute must be a whole number, got 0.5
Attribute must be a whole number, got 0.75
```
These must be `TypeInt`
https://github.com/newrelic/terraform-provider-newrelic/blob/main/newrelic/resource_newrelic_one_dashboard.go#L600-L610
- [X ] This change requires a documentation update
- [X ] My commit message follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [X ] I have performed a self-review of my own code
- [X ] I have made corresponding changes to the documentation
Please describe how to test your changes. …

docs: fix dashboard threshold

---

website/docs/guides/migration_guide_alert_conditions.html.markdown
website/docs/r/infra_alert_condition.html.markdown
website/docs/r/synthetics_alert_condition.html.markdown

Updated the references of migration examples from legacy alert conditions to NRQL alert conditions in synthetic and infra alert condition documents. Also updated headings in migration guide  to make it more meaningful.
Jira ticket:  https://new-relic.atlassian.net/browse/NR-285380
- Step 1
- Step 2
- etc

docs: Update  NRQL alert condition migration example references in legacy alert condition documents. 

---

website/docs/r/notification_channel.html.markdown

This is just a short documentation update to make a specific example clearer

docs(notifications): changed jira example comment

---

website/docs/r/cloud_aws_integrations.html.markdown

This PR is to refactor the AWS Cloud Integrations Resource Documentation inorder to make it more precise and elobarative for understanding.
- Step 1
- Step 2
- etc

docs(aws_cloud_integration): Refactor of the AWS Cloud Integrations Resource Documentation

---

go.mod
go.sum
newrelic/resource_newrelic_one_dashboard.go
newrelic/resource_newrelic_one_dashboard_test.go
newrelic/structures_newrelic_one_dashboard.go
website/docs/r/api_access_key.html.markdown
website/docs/r/one_dashboard.html.markdown

Adding Support for Data Format to the `newrelic_one_dashboard` Resource
- Step 1
- Step 2
- etc

feat(dashboards): addition of support for data format to the `newrelic_one_dashboard` Resource

---

go.mod
go.sum
newrelic/provider.go
newrelic/resource_newrelic_key_transaction.go
newrelic/resource_newrelic_key_transaction_test.go
website/docs/r/key_transaction.html.markdown

Added key transaction support in terraform.
to understand what is key transaction refer to [this](https://docs.newrelic.com/docs/apm/transactions/key-transactions/introduction-key-transactions/)
Create a new Key transaction
update the key transaction
delete the key transaction

feat(key_transaction): add new resource to manage key transactions

---

newrelic/resource_newrelic_key_transaction_test.go
newrelic/resource_newrelic_monitor_downtime_test.go

test: fixes to some broken integration tests

---

examples/bulk_users_import/README.md

Update Readme arguments section content.

fix(readme-update): readme content update

---

newrelic/resource_newrelic_key_transaction_test.go

[Jira Ticket](https://new-relic.atlassian.net/browse/NR-355734)
Issue :- Key Transaction Integration test was failing with the below error.
**Analysis:-** 
Due to a business constraint, only a single key transaction can exist for a particular metric. Previously, Terraform was unable to delete or destroy an already created key transaction during a subsequent terraform apply, which resulted in the failure of integration tests.
**Mitigation Steps:-**
Step 1:- Added a preCheck condition: this step will verifies if resource already exist, if yes then will destroy before running the integration test.
Step 2:- Added postDestroy: this step will destroy all the resources created as a part of the integration test.
After above changes, Key Transaction Integration test is successfully passed.
Please …

fix(key-transaction-integrations): Fixed key transaction integration test

---

examples/modules/cloud-integrations/aws/main.tf
examples/modules/cloud-integrations/aws/variables.tf

Added condition support for US GOV cloud

---

examples/modules/cloud-integrations/aws/main.tf
examples/modules/cloud-integrations/aws/variables.tf

chore(aws): added condition support for US GOV cloud

---

go.mod
go.sum
newrelic/resource_newrelic_workflow_test.go
website/docs/r/workflow.html.markdown

Description
[Related newrelic-client-go TF change](https://github.com/newrelic/newrelic-client-go/pull/1270)
Added new notification trigger type (INVESTIGATING) which is used to send notification when an issue is being investigated.
Type of change
New feature (non-breaking change which adds functionality)
Checklist:
My commit message follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
My code is formatted to [Go standards](https://go.dev/blog/gofmt)
I have performed a self-review of my own code
I have made corresponding changes to the documentation
I have added tests that prove my fix is effective or that my feature works
New and existing unit tests pass locally with my changes. Go …

feat(workflows): adds new `notification_trigger` type `INVESTIGATING`

---

website/docs/r/application_settings.html.markdown

follow up to #2799 since the release might not have fully worked (hence trying to use a `feat` keyword with a docs commit)

feat(app_settings): refine documentation

---

.github/workflows/changelog.yml

bumped up artifacts version (v3 -> v4)

fix(artifacts): updated to latest artifacts version 

---

build/release.mk

fixed goreleaser script to update release-notes

fix(release): fix goreleaser script to update release-notes

---

.githooks/commit-msg
.github/workflows/test_pr_conventional_commits.yml
.github/workflows/test_pull_request_title.yaml
CONTRIBUTING.md
build/lint.mk
testing/newrelic.tf
tools/go.mod
tools/go.sum
tools/tools.go

1. I have added following changes - PR title lint, Commit lint, recursive merge commit history lint
2. Added script for the new users to setup this commit linter
3. Update documentation to provide more info on this commit linter

fix(scripts): addition of new commit linter and restrictions on commit messages via workflows

---

.github/workflows/test_integration.yml
.github/workflows/test_integration_cron.yml
integration_test_utilities/integration_test_utilities_tag_mapper.sh

chore(test): refine integration test utilities cap mapper shell script

---

newrelic/resource_newrelic_synthetics_alert_condition_test.go
newrelic/resource_newrelic_synthetics_monitor.go
newrelic/resource_newrelic_synthetics_multilocation_alert_condition_test.go

TBD
https://new-relic.atlassian.net/browse/NR-407321

fix(synthetics): allow public locations of ping and browser monitors to be read

---

CHANGELOG.md

fix(release): revert v3.61.1, v3.62.2 changelog updates to trigger new release

---

newrelic/resource_newrelic_agent_application_browser.go
newrelic/resource_newrelic_agent_application_browser_integration_test.go
newrelic/resource_newrelic_application_settings_test.go

loader_type field in browser application was not getting updated, This was reported in this [GTSE](https://new-relic.atlassian.net/browse/NR-415935).
Updated the code to update the loader_ type for the browser application
🗒️  No test and documentation update required
Please refer to [this](https://new-relic.atlassian.net/browse/NR-416311) for the test validations
- create a browser application
- Update the loader_type feild

fix(browser-application): fix browser application loader_type not updating

---

examples/bulk_users_import/README.md

fix(user_module): minimal commit to trigger a release, v3.61.3

---

go.mod
go.sum
newrelic/resource_newrelic_agent_application_browser.go
newrelic/resource_newrelic_agent_application_browser_integration_test.go

GSTE: https://new-relic.atlassian.net/browse/NR-421126
Fixed a bug in the APM application browser package where distributed tracing's boolean was misfunctioning.
Dependent PR: https://github.com/newrelic/newrelic-client-go/pull/1304
- Step 1
- Step 2
- etc

fix: resolve distributed tracing flag misfunction bug

---

go.mod
go.sum
website/docs/guides/cloud_integrations_guide.html.markdown

fix(cloud): make subnet optional in oci module

---

examples/modules/cloud-integrations/oci/metrics-integration/main.tf
examples/modules/cloud-integrations/oci/metrics-integration/variables.tf
website/docs/guides/cloud_integrations_guide.html.markdown

This PR updates the public Docker image of the New Relic function and modifies the default values and validation for the New Relic metrics endpoint
- Step 1
- Step 2
- etc

fix(oci): update Docker image path and newrelic_endpoint validation
